// DSIZE1 (the delve arc, 2026-10-05 - Features-Arc.md's open door on Smaller Dungeons: "a size tier ... would earn the
// Enhanced label"): MEDIUM DUNGEONS.
//
// Over eight blocks, a dungeon is regenerated by GenerateSmallerDungeon's own law at the step between DFU's five and
// the whole: two interior blocks side by side (the start first) and the six border blocks that close them - the
// commonest shape MAPS.BSA has (AUDIT DELVE: the first cut's thirteen-block cross made the real big dungeons bigger
// inside) - from its own block list, DFRandom seeded on its MapId. Every guard Smaller Dungeons keeps, Medium keeps;
// Smaller Dungeons wins when both are on; the quest freeze and the save stamp carry it at a value appended past DFU's
// three (world/smallerDungeons.js); online the stamp is the room's size (E4); a quest whose markers were chosen
// through another quest's link takes that link's size where the medium size is either side (E5); a quest frozen at
// another size crossing online is re-laid on the room's build (E1, quest/questRepair.js). SD-ONLINE (PINS MOVED -
// bible/11-Multiplayer/Super-Dungeons.md section 13; test/sdonline.test.js holds the law itself): online every
// dungeon has the world's own size now - small, medium or large by its map id - where it was the whole dungeon. And
// DETECT-FINDS: a
// searched object's find is in the one loot walk (scenes/shared.js). bible/03-World/Delve-Arc.md, DSIZE1 and
// DETECT-FINDS; bible/01-Overview/Audit-Delve.md.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  SMALLER_DUNGEONS_STATE, MEDIUM_DUNGEON_THRESHOLD, MEDIUM_DUNGEONS_STATE, MEDIUM_DUNGEONS_PREF, MEDIUM_LAYOUT,
  ONLINE_DUNGEONS_STATE, onlineDungeonSize,
  mediumDungeonsWanted, smallerDungeonsStateNow, useSmallerDungeon, dungeonSizeFor, generateMediumDungeon,
  generateSmallerDungeon, isMediumDungeon, isSmallerDungeon, smallerDungeonsStamp, needsStartWarp, dungeonLocationFor,
  adoptLinkedDungeonSize,
} from '../src/world/smallerDungeons.js';
import { isMainStoryDungeon } from '../src/world/dungeonTextures.js';
import { QuestMachine } from '../src/systems/quest/machine.js';
import { Place } from '../src/systems/quest/place.js';
import { loadQuestTables } from '../src/systems/quest/tables.js';
import { relayOnlineDungeons } from '../src/systems/quest/questRepair.js';
import { RDB_RESOURCE_TYPES } from '../src/formats/blocksFile.js';
import { readdirSync } from 'node:fs';
import { setSeed, randomRange } from '../src/formats/dfRandom.js';
import { SITE_TYPES } from '../src/systems/quest/place.js';
import { setUiSkin, uiSkin } from '../src/systems/uiSkin.js';
import { getPref, setPref } from '../src/systems/uiPrefs.js';
import { nearbyLootRecords, searchedNearbyRecord } from '../src/scenes/shared.js';
import { getNearbyObjects, updateNearbyObjects, lootFlags, NEARBY } from '../src/systems/nearbyObjects.js';
import { FEATURES, FEATURE_PREF_DEFAULTS } from '../src/systems/features.js';

const src = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const PRIVATEERS_HOLD = 187853213;
{
  const dir = new URL('../vendor/dfu-quests/Tables/', import.meta.url);
  const sources = {};
  for (const f of readdirSync(dir)) if (f.endsWith('.txt')) sources[f.replace('.txt', '')] = readFileSync(new URL(f, dir), 'utf8').replace(/^\uFEFF/, '');
  loadQuestTables(sources);
}
const BARE_SRC = ['Quest: __DSZ', 'QRC:', 'Message:  1011', ' x', '', 'QBN:', 'variable _done_'];
const sym = (name) => ({ name, original: `_${name}_`, clone() { return sym(name); } });
const block = (name) => ({ blockName: name, x: 9, z: 9, isStartingBlock: false });
const loc = (n, mapId = 777) => ({
  name: 'T', hasDungeon: true, mapTableData: { mapId },
  dungeon: { blocks: Array.from({ length: n }, (_, i) => block(`${i % 3 === 0 ? 'B' : i % 3 === 1 ? 'N' : 'W'}00000${String(i).padStart(2, '0')}.RDB`)) },
});

test('DSIZE1: the constants - over eight, at a value past DFU\'s three, its own pref, off by default', () => {
  assert.equal(MEDIUM_DUNGEON_THRESHOLD, 8);
  assert.equal(MEDIUM_DUNGEONS_STATE, 3);
  assert.deepEqual(Object.values(SMALLER_DUNGEONS_STATE), [0, 1, 2], 'DFU\'s enum, untouched');
  assert.equal(MEDIUM_DUNGEONS_PREF, 'mediumDungeons');
  assert.equal(FEATURE_PREF_DEFAULTS.mediumDungeons, false);
  assert.equal(MEDIUM_LAYOUT.length, MEDIUM_DUNGEON_THRESHOLD, 'the layout is the threshold\'s size');
});

test('DSIZE1: the two and their ring - the start first, the interior side by side, every border block closes an interior and every open side is closed', () => {
  const at = new Map(MEDIUM_LAYOUT.map(([x, z, b]) => [`${x},${z}`, b]));
  assert.equal(at.size, 8, 'no two blocks share a place');
  const interior = MEDIUM_LAYOUT.filter(([, , b]) => !b), border = MEDIUM_LAYOUT.filter(([, , b]) => b);
  assert.deepEqual(MEDIUM_LAYOUT[0], [0, 0, false], 'the starting block first');
  assert.deepEqual(interior, [[0, 0, false], [1, 0, false]], 'two interior blocks, side by side');
  assert.equal(border.length, 6);
  const n4 = ([x, z]) => [[x + 1, z], [x - 1, z], [x, z + 1], [x, z - 1]];
  for (const b of border) assert.ok(n4(b).some(([x, z]) => at.get(`${x},${z}`) === false), `${b} borders an interior block`);
  for (const i of interior) for (const [x, z] of n4(i)) assert.ok(at.has(`${x},${z}`), `${i}'s side ${x},${z} is closed`);
});

test('DSIZE1: generated - the two from the interior pool, the ring from the border pool, the source untouched, seeded; the small plus draws through the same body, DFU\'s order', () => {
  const source = loc(20);
  const out = generateMediumDungeon(source);
  assert.notEqual(out, source);
  assert.equal(source.dungeon.blocks.length, 20, 'the cached location is never mutated');
  assert.equal(isMediumDungeon(out), true);
  assert.equal(isSmallerDungeon(out), false);
  assert.deepEqual(out.dungeon.blocks.map((b) => [b.x, b.z, b.isStartingBlock]), MEDIUM_LAYOUT.map(([x, z], i) => [x, z, i === 0]));
  out.dungeon.blocks.forEach((b, i) => assert.equal(/^b/i.test(b.blockName), MEDIUM_LAYOUT[i][2], `${i}: ${b.blockName}`));
  assert.deepEqual(generateMediumDungeon(loc(20)).dungeon.blocks, out.dungeon.blocks, 'the same every visit');
  // exactly GetRandomBlock's draws, in layout order, over the two filtered pools
  setSeed(777);
  const pools = { false: source.dungeon.blocks.filter((b) => !/^b/i.test(b.blockName)), true: source.dungeon.blocks.filter((b) => /^b/i.test(b.blockName)) };
  const names = MEDIUM_LAYOUT.map(([, , border]) => pools[border][randomRange(0, pools[border].length)].blockName);
  assert.deepEqual(out.dungeon.blocks.map((b) => b.blockName), names);
  const eight = loc(8);
  assert.equal(generateMediumDungeon(eight), eight, 'at the threshold it is already medium');
  assert.equal(isMediumDungeon(generateMediumDungeon(loc(9))), true, 'one over, regenerated');
  assert.throws(() => generateMediumDungeon(loc(20, PRIVATEERS_HOLD)), /generateMediumDungeon\(\) must not be called on a main story dungeon/);
  // the small plus: the same body, DFU's five in DFU's order (centre, N, W, E, S)
  const plus = generateSmallerDungeon(loc(20));
  assert.deepEqual(plus.dungeon.blocks.map((b) => [b.x, b.z, b.isStartingBlock, /^b/i.test(b.blockName)]),
    [[0, 0, true, false], [0, -1, false, true], [-1, 0, false, true], [1, 0, false, true], [0, 1, false, true]]);
  assert.equal(plus.dungeon.smaller, true);
  assert.equal(plus.dungeon.medium, undefined, 'each clone says its own size');
});

test('DSIZE1: the size a dungeon is built at - the guards, the quest\'s frozen size, then Smaller, then Medium; DFU\'s UseSmallerDungeon verbatim beside it (A6)', () => {
  const big = loc(20);
  assert.equal(dungeonSizeFor(big, { setting: false, medium: false }), 'full');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: true }), 'medium');
  assert.equal(dungeonSizeFor(big, { setting: true, medium: true }), 'small', 'Smaller Dungeons wins');
  assert.equal(dungeonSizeFor(big, { setting: true, medium: true, online: true }), onlineDungeonSize(big), 'online, the world\'s size for it (SD-ONLINE - PIN MOVED: it was the whole dungeon)');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: false, online: true }), onlineDungeonSize(big), '...whatever either switch says');
  assert.equal(onlineDungeonSize(big), 'medium', 'map 777\'s draw (test/sdonline.test.js holds the law)');
  assert.equal(dungeonSizeFor(loc(20, PRIVATEERS_HOLD), { setting: true, medium: true }), 'full', 'main story never shrinks');
  assert.equal(dungeonSizeFor({ hasDungeon: false }, { setting: true }), 'full');
  const machine = (state) => ({
    getSiteLinks: (type, mapId) => (type === SITE_TYPES.Dungeon && mapId === 777 ? [{ questUID: 5 }] : []),
    getQuest: () => ({ smallerDungeonsState: state }),
  });
  assert.equal(dungeonSizeFor(big, { setting: true, medium: false, questMachine: machine(MEDIUM_DUNGEONS_STATE) }), 'medium', 'the quest compiled at medium');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: true, questMachine: machine(SMALLER_DUNGEONS_STATE.Enabled) }), 'small');
  assert.equal(dungeonSizeFor(big, { setting: true, medium: true, questMachine: machine(SMALLER_DUNGEONS_STATE.Disabled) }), 'full');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: true, questMachine: machine(SMALLER_DUNGEONS_STATE.NotSet) }), 'medium', 'NotSet falls to the settings');
  // DFU's own member answers as it always did - a state it does not name falls through to the setting (:776-797)
  assert.equal(useSmallerDungeon(big, { setting: true }), true);
  assert.equal(useSmallerDungeon(big, { setting: false }), false);
  assert.equal(useSmallerDungeon(big, { setting: false, questMachine: machine(MEDIUM_DUNGEONS_STATE) }), false);
  assert.equal(useSmallerDungeon(big, { setting: true, questMachine: machine(MEDIUM_DUNGEONS_STATE) }), true, 'A6: DFU\'s fall-through, verbatim');
  assert.equal(useSmallerDungeon(big, { setting: true, questMachine: machine(SMALLER_DUNGEONS_STATE.Disabled) }), false);
  assert.equal(useSmallerDungeon(big, { setting: false, questMachine: machine(SMALLER_DUNGEONS_STATE.Enabled) }), true);
  assert.equal(useSmallerDungeon(big, { setting: true, online: true }), false);
  // the one door
  assert.equal(dungeonLocationFor(big, { setting: false, medium: true }).dungeon.blocks.length, 8);
  assert.equal(dungeonLocationFor(big, { setting: true, medium: true }).dungeon.blocks.length, 5);
  assert.equal(dungeonLocationFor(big, { setting: false, medium: false }), big);
});

test('DSIZE1: the quest\'s stamp, the save\'s stamp and the warp - three layouts, compared whole; online the stamp is the room\'s size (E4)', () => {
  assert.equal(smallerDungeonsStateNow(true, true, false), SMALLER_DUNGEONS_STATE.Enabled);
  assert.equal(smallerDungeonsStateNow(false, true, false), MEDIUM_DUNGEONS_STATE);
  assert.equal(smallerDungeonsStateNow(false, false, false), SMALLER_DUNGEONS_STATE.Disabled);
  assert.equal(smallerDungeonsStateNow(true, false, true), ONLINE_DUNGEONS_STATE, 'E4: online, the room builds every dungeon at its own size whatever the setting says (SD-ONLINE: the world\'s - PIN MOVED)');
  assert.equal(smallerDungeonsStateNow(false, false, true), ONLINE_DUNGEONS_STATE);
  assert.equal(smallerDungeonsStateNow(true, true), SMALLER_DUNGEONS_STATE.Enabled, 'off the online page, the settings');
  const full = loc(20), med = generateMediumDungeon(loc(20)), sml = generateSmallerDungeon(loc(20));
  assert.equal(smallerDungeonsStamp(med), MEDIUM_DUNGEONS_STATE);
  assert.equal(smallerDungeonsStamp(sml), SMALLER_DUNGEONS_STATE.Enabled);
  assert.equal(smallerDungeonsStamp(full), SMALLER_DUNGEONS_STATE.Disabled);
  const S = { NotSet: 0, Disabled: 1, Enabled: 2, Medium: 3 };
  const cases = [[S.NotSet, full, false], [S.NotSet, med, false], [S.Disabled, full, false], [S.Enabled, sml, false], [S.Medium, med, false],
    [S.Disabled, med, true], [S.Disabled, sml, true], [S.Enabled, full, true], [S.Enabled, med, true], [S.Medium, full, true], [S.Medium, sml, true], [9, full, true]];
  for (const [saved, l, want] of cases) assert.equal(needsStartWarp(saved, l), want, `saved ${saved} into ${l.dungeon.medium ? 'medium' : l.dungeon.smaller ? 'small' : 'full'}`);
  assert.equal(needsStartWarp(S.Medium, loc(20, PRIVATEERS_HOLD)), false, 'never in a main-story dungeon');
});

test('DSIZE1 E5: the machine\'s Start takes a linked dungeon\'s size where the medium size is either side - the size the markers were chosen on; DFU\'s two values left DFU\'s', () => {
  const quest = (uid, state, mapId = 777) => ({
    uid, smallerDungeonsState: state,
    resources: new Map([['dun', { isPlace: true, siteDetails: { siteType: SITE_TYPES.Dungeon, mapId } }], ['npc', { isPerson: true }]]),
  });
  const machineOf = (held) => ({
    getSiteLinks: (type, mapId) => (type === SITE_TYPES.Dungeon && mapId === 777 && held != null ? [{ questUID: 1 }] : []),
    getQuest: (uid) => (uid === 1 ? { smallerDungeonsState: held } : null),
  });
  const S = SMALLER_DUNGEONS_STATE, M = MEDIUM_DUNGEONS_STATE, O = ONLINE_DUNGEONS_STATE;
  for (const [held, stamped, want] of [
    [S.Disabled, M, S.Disabled], [M, S.Enabled, M], [S.Enabled, M, S.Enabled], [M, S.Disabled, M],
    [S.Enabled, S.Disabled, S.Disabled], [S.Disabled, S.Enabled, S.Enabled],   // DFU's own pair: DFU's stamp, untouched
    [S.NotSet, M, M], [null, M, M], [M, M, M],
    // SD-ONLINE: the world's sizes are a port's size too - either side, the link's
    [O, S.Disabled, O], [S.Disabled, O, S.Disabled], [O, M, O], [M, O, M], [O, S.Enabled, O], [S.NotSet, O, O], [O, O, O],
  ]) {
    const q = quest(2, stamped);
    adoptLinkedDungeonSize(q, machineOf(held));
    assert.equal(q.smallerDungeonsState, want, `link ${held}, stamped ${stamped}`);
  }
  const own = quest(1, M);
  adoptLinkedDungeonSize(own, machineOf(S.Disabled));
  assert.equal(own.smallerDungeonsState, M, 'its own link is not another quest\'s');
  const elsewhere = quest(2, M, 999);
  adoptLinkedDungeonSize(elsewhere, machineOf(S.Disabled));
  assert.equal(elsewhere.smallerDungeonsState, M, 'a link on another dungeon is not this one\'s');
  // wired at the machine's Start, after the stamp
  const m = src('src/systems/quest/machine.js');
  assert.match(m, /startQuestImmediate\(quest\) \{\n    quest\.start\(\);\n    adoptLinkedDungeonSize\(quest, this\);/);
});

test('DSIZE1 E1 (SD-ONLINE, PIN MOVED): a quest stamped at another size, loaded online, has its dungeon markers enumerated again on the room\'s build (the world\'s size for each dungeon), its placements put back there, and its stamp set to the world\'s sizes', () => {
  const m = new QuestMachine();
  const q = m.parseQuestForLists(BARE_SRC, 0, { rolls: () => 0 });
  m.startQuestImmediate(q);
  q.smallerDungeonsState = SMALLER_DUNGEONS_STATE.Disabled;   // chosen on the whole dungeon, offline
  // the room's build (the quest's world answers it - online, world.js questWorld sizes through dungeonLocationFor):
  // two blocks, a spawn marker in each, at block (0,0) and (1,0)
  const flat = (record, x) => ({ type: RDB_RESOURCE_TYPES.Flat, position: x, xPos: x, yPos: 0, zPos: 0, resources: { flatResource: { textureArchive: 199, textureRecord: record } } });
  const blockData = { W1: { position: 100, rdbBlock: { objectRootList: [{ rdbObjects: [flat(11, 1), flat(18, 2)] }] } }, B1: { position: 200, rdbBlock: { objectRootList: [{ rdbObjects: [flat(11, 3)] }] } } };
  const built = { name: 'Keep', mapTableData: { mapId: 777 }, dungeon: { medium: true, blocks: [{ blockName: 'W1', x: 0, z: 0 }, { blockName: 'B1', x: 1, z: 0 }] } };
  q.hooks = { ...(q.hooks ?? {}), world: {
    maps: { getRegion: (r) => (r === 3 ? { mapNameLookup: new Map([['Keep', 5]]) } : null), getLocation: (r, l) => (r === 3 && l === 5 ? built : null) },
    getBlock: (n) => blockData[n] ?? null,
  } };
  const dun = new Place(q);
  dun.symbol = sym('dun');
  const old = (id, x, z) => ({ markerType: 0, flatPosition: { x: id, y: 0, z: 0 }, dungeonX: x, dungeonZ: z, buildingKey: 0, markerID: id, targetResources: null });
  dun.siteDetails = { siteType: SITE_TYPES.Dungeon, mapId: 777, regionIndex: 3, locationName: 'Keep', buildingKey: 0, magicNumberIndex: 0,
    selectedMarker: { targetResources: [sym('boss')] }, questSpawnMarkers: [old(1, 0, -1)], questItemMarkers: [] };
  dun._range = () => 0;
  q.resources.set('dun', dun);
  q.resources.set('boss', { symbol: sym('boss'), isFoe: true, spawnCount: 1, killCount: 0, parentQuest: q, questResourceBehaviour: null });
  q.tasks.set('_go_', { actions: [{ typeName: 'PlaceFoe', foeSymbol: sym('boss'), placeSymbol: sym('dun'), marker: -1, isComplete: true }] });
  assert.equal(relayOnlineDungeons(m), 1, 'one quest re-laid');
  assert.deepEqual(dun.siteDetails.questSpawnMarkers.map((k) => [k.dungeonX, k.dungeonZ, k.markerID]), [[0, 0, 101], [1, 0, 203]], 'the room\'s build\'s markers');
  assert.deepEqual(dun.siteDetails.questItemMarkers.map((k) => [k.dungeonX, k.markerID]), [[0, 102]]);
  assert.deepEqual(dun.siteDetails.selectedMarker.targetResources.map((t) => t.name), ['boss'], 'the boss stands on the room\'s build\'s marker');
  assert.equal(dun.siteDetails.selectedMarker.dungeonZ, 0, '...a marker the room\'s build has');
  assert.equal(q.smallerDungeonsState, ONLINE_DUNGEONS_STATE, 'the sizes its markers now know');
  // again from the small size, and from the medium: the markers agree, nothing moves, nothing counted - and the stamp is the room's
  const held = dun.siteDetails.selectedMarker;
  for (const from of [SMALLER_DUNGEONS_STATE.Enabled, MEDIUM_DUNGEONS_STATE]) {
    q.smallerDungeonsState = from;
    assert.equal(relayOnlineDungeons(m), 0);
    assert.equal(dun.siteDetails.selectedMarker, held, 'a Place whose markers come out the same keeps its targets');
    assert.equal(q.smallerDungeonsState, ONLINE_DUNGEONS_STATE);
  }
  // a quest at the room's sizes is not read
  dun.siteDetails.questSpawnMarkers = [old(1, 0, -1)];
  assert.equal(relayOnlineDungeons(m), 0);
  assert.equal(dun.siteDetails.questSpawnMarkers[0].dungeonZ, -1, 'ONLINE: the room\'s, left as it is');
  // DFU's NotSet names no layout ("the setting"): read and compared like any other
  q.smallerDungeonsState = SMALLER_DUNGEONS_STATE.NotSet;
  assert.equal(relayOnlineDungeons(m), 1, 'NotSet, its markers off the room\'s build: re-laid');
  assert.equal(dun.siteDetails.questSpawnMarkers[0].dungeonZ, 0);
  assert.equal(q.smallerDungeonsState, ONLINE_DUNGEONS_STATE);
  // a dungeon this pass cannot read keeps the quest's stamp - the size its markers there still know
  q.smallerDungeonsState = SMALLER_DUNGEONS_STATE.Disabled;
  dun.siteDetails = { ...dun.siteDetails, locationName: 'Nowhere' };
  assert.equal(relayOnlineDungeons(m), 0);
  assert.equal(q.smallerDungeonsState, SMALLER_DUNGEONS_STATE.Disabled, 'unread: the stamp stands');
  // wired at the bridge's load, online only, before anything mounts
  const bridge = src('src/scenes/questBridge.js');
  const restore = bridge.slice(bridge.indexOf('restore(data) {'));
  assert.match(restore, /machine\.restoreSaveData\(data\.machine \?\? \{ siteLinks: \[\], quests: \[\] \}\);\n(?:\s*\/\/[^\n]*\n)+\s*if \(isOnlinePage\(\)\) relayOnlineDungeons\(machine, /);
  assert.doesNotMatch(src('src/systems/quest/questRepair.js'), /function relayWholeDungeons/, 'the whole-dungeon re-lay is gone, not beside it');
});

const ARENA2 = process.env.ARENA2_PATH;
const skipReal = !ARENA2 || !existsSync(ARENA2) ? 'ARENA2_PATH not set or missing - real-data validation skipped' : false;

test('DSIZE1 against MAPS.BSA: every dungeon over eight blocks builds at the medium size without a throw, each from its own pools, and the ring closes it', { skip: skipReal }, async () => {
  const { MapsFile } = await import('../src/formats/mapsFile.js');
  const maps = new MapsFile();
  maps.load(new Uint8Array(readFileSync(join(ARENA2, 'MAPS.BSA'))), new Uint8Array(readFileSync(join(ARENA2, 'CLIMATE.PAK'))), new Uint8Array(readFileSync(join(ARENA2, 'POLITIC.PAK'))));
  let over = 0, built = 0, under = 0;
  for (let r = 0; r < maps.regionCount; r++) {
    const region = maps.getRegion(r);
    for (let l = 0; l < (region?.locationCount ?? 0); l++) {
      const location = maps.getLocation(r, l);
      if (!location?.hasDungeon || isMainStoryDungeon(location.mapTableData.mapId)) continue;
      const n = location.dungeon.blocks.length;
      const out = generateMediumDungeon(location);
      if (n <= MEDIUM_DUNGEON_THRESHOLD) { under++; assert.equal(out, location); continue; }
      over++;
      const own = new Set(location.dungeon.blocks.map((b) => b.blockName));
      assert.equal(out.dungeon.blocks.length, MEDIUM_LAYOUT.length);
      for (const [i, b] of out.dungeon.blocks.entries()) {
        assert.ok(own.has(b.blockName), `${location.name}: ${b.blockName} is its own`);
        assert.equal(/^b/i.test(b.blockName), MEDIUM_LAYOUT[i][2], `${location.name}: block ${i} from the right pool`);
      }
      built++;
    }
  }
  assert.ok(over > 2000, `the medium size reaches most dungeons (${over})`);
  assert.equal(built, over, 'every one built');
  assert.ok(under > 1500, `five- and eight-block dungeons pass through (${under})`);
});

test('DSIZE1: the ask is the enhanced skin\'s', () => {
  const skin = uiSkin(), pref = getPref(MEDIUM_DUNGEONS_PREF);
  try {
    setUiSkin('enhanced'); setPref(MEDIUM_DUNGEONS_PREF, true);
    assert.equal(mediumDungeonsWanted(), true);
    setUiSkin('classic');
    assert.equal(mediumDungeonsWanted(), false);
    setUiSkin('enhanced'); setPref(MEDIUM_DUNGEONS_PREF, false);
    assert.equal(mediumDungeonsWanted(), false);
  } finally { setUiSkin(skin); setPref(MEDIUM_DUNGEONS_PREF, pref); }
});

test('DSIZE1: the Features row - Enhanced, its own, off by default and forced off online (SD-ONLINE: the world\'s sizes are the room\'s law there)', () => {
  const f = FEATURES.find((x) => x.id === 'medium-dungeons');
  assert.ok(f);
  assert.deepEqual(f.kinds, ['enhanced']);
  assert.deepEqual({ ...f.control }, { store: 'prefs', key: MEDIUM_DUNGEONS_PREF, initial: false, online: false });
  assert.match(f.note, /Online every dungeon has its own size instead\./, 'the row says what the room does (PIN MOVED)');
  assert.doesNotMatch(f.note, /every dungeon online, keep full size/, 'and no longer the law it replaced');
  assert.equal(FEATURES.findIndex((x) => x.id === 'medium-dungeons'), FEATURES.findIndex((x) => x.id === 'smaller-dungeons') + 1, 'beside DFU\'s own switch');
});

test('DETECT-FINDS: a searched object\'s find is in the one loot walk, at its box\'s middle; unsearched, no Treasure', () => {
  const sb = (items) => ({ aabb: { min: [0, 0, 0], max: [2, 1, 4] }, items });
  assert.deepEqual(searchedNearbyRecord(sb([{ id: 1 }])).pos, [1, 0.5, 2]);
  assert.equal(searchedNearbyRecord(sb([{ id: 1 }, { id: 2 }])).itemCount, 2);
  assert.equal(searchedNearbyRecord({}).pos, null);
  const loot = nearbyLootRecords({ searched: [sb([{ id: 1 }]), sb([])] });
  assert.equal(loot.length, 2, 'both in the walk, as an empty corpse is');
  assert.equal(lootFlags(loot[0]), NEARBY.Treasure, 'a find lying in it is treasure');
  assert.equal(lootFlags(loot[1]), NEARBY.None, 'unsearched: nothing rolled yet, no Treasure bit');
  // and the Detect scan finds it, as it finds a pile
  const scan = updateNearbyObjects([0, 0, 0], { loot });
  assert.equal(getNearbyObjects(scan, NEARBY.Treasure).length, 1);
  assert.match(src('src/scenes/dungeonContext.js'), /loot: \(\) => nearbyLootRecords\(\{ piles: \[\.\.\.lootPiles, \.\.\.droppedLoot\._piles\], foes, searched: searchables \}\),/);
  // AUDIT DELVE (the open item closed): the street's searched headstones need no walk of their own - a grave's find is
  // minted as a dropped pile on the ground (world.js activateGrave), and the street's Detect walk carries every pile
  const w = src('src/scenes/world.js');
  const grave = w.slice(w.indexOf('function activateGrave(g, mode = \'grab\') {'), w.indexOf('const giveReward = (dfItem) => {'));
  assert.match(grave, /const pile = droppedLoot\.dropPile\(items, dropFeet\(\), /, 'the grave\'s find is a pile');
  assert.match(w, /loot: \(\) => nearbyLootRecords\(\{ piles: droppedLoot\._piles, foes: exteriorFoePool\(\) \}\),/, 'and the street walks the piles');
});
