// DSIZE1 (the delve arc, 2026-10-05 - Features-Arc.md's open door on Smaller Dungeons: "a size tier ... would earn the
// Enhanced label"): MEDIUM DUNGEONS.
//
// Over thirteen blocks, a dungeon is regenerated by GenerateSmallerDungeon's own law at the step between DFU's five and
// the whole: a cross of five interior blocks (the start in the middle) ringed by the eight border blocks that close it,
// from its own block list, DFRandom seeded on its MapId. Every guard Smaller Dungeons keeps, Medium keeps; Smaller
// Dungeons wins when both are on; the quest freeze and the save stamp carry it at a value appended past DFU's three
// (world/smallerDungeons.js). And DETECT-FINDS: a searched object's find is in the one loot walk (scenes/shared.js).
// bible/03-World/Delve-Arc.md, DSIZE1 and DETECT-FINDS.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
  SMALLER_DUNGEONS_STATE, MEDIUM_DUNGEON_THRESHOLD, MEDIUM_DUNGEONS_STATE, MEDIUM_DUNGEONS_PREF, MEDIUM_LAYOUT,
  mediumDungeonsWanted, smallerDungeonsStateNow, useSmallerDungeon, dungeonSizeFor, generateMediumDungeon,
  generateSmallerDungeon, isMediumDungeon, isSmallerDungeon, smallerDungeonsStamp, needsStartWarp, dungeonLocationFor,
} from '../src/world/smallerDungeons.js';
import { setSeed, randomRange } from '../src/formats/dfRandom.js';
import { SITE_TYPES } from '../src/systems/quest/place.js';
import { setUiSkin, uiSkin } from '../src/systems/uiSkin.js';
import { getPref, setPref } from '../src/systems/uiPrefs.js';
import { nearbyLootRecords, searchedNearbyRecord } from '../src/scenes/shared.js';
import { getNearbyObjects, updateNearbyObjects, lootFlags, NEARBY } from '../src/systems/nearbyObjects.js';
import { FEATURES, FEATURE_PREF_DEFAULTS } from '../src/systems/features.js';

const src = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const PRIVATEERS_HOLD = 187853213;
const block = (name) => ({ blockName: name, x: 9, z: 9, isStartingBlock: false });
const loc = (n, mapId = 777) => ({
  name: 'T', hasDungeon: true, mapTableData: { mapId },
  dungeon: { blocks: Array.from({ length: n }, (_, i) => block(`${i % 3 === 0 ? 'B' : i % 3 === 1 ? 'N' : 'W'}00000${String(i).padStart(2, '0')}.RDB`)) },
});

test('DSIZE1: the constants - over thirteen, at a value past DFU\'s three, its own pref, off by default', () => {
  assert.equal(MEDIUM_DUNGEON_THRESHOLD, 13);
  assert.equal(MEDIUM_DUNGEONS_STATE, 3);
  assert.deepEqual(Object.values(SMALLER_DUNGEONS_STATE), [0, 1, 2], 'DFU\'s enum, untouched');
  assert.equal(MEDIUM_DUNGEONS_PREF, 'mediumDungeons');
  assert.equal(FEATURE_PREF_DEFAULTS.mediumDungeons, false);
  assert.equal(MEDIUM_LAYOUT.length, MEDIUM_DUNGEON_THRESHOLD, 'the layout is the threshold\'s size');
});

test('DSIZE1: the cross and its ring - every interior block touches the middle, every border block closes an interior', () => {
  const at = new Map(MEDIUM_LAYOUT.map(([x, z, b]) => [`${x},${z}`, b]));
  assert.equal(at.size, 13, 'no two blocks share a place');
  const interior = MEDIUM_LAYOUT.filter(([, , b]) => !b), border = MEDIUM_LAYOUT.filter(([, , b]) => b);
  assert.deepEqual(MEDIUM_LAYOUT[0], [0, 0, false], 'the middle first: the starting block');
  assert.equal(interior.length, 5);
  for (const [x, z] of interior) assert.ok(Math.abs(x) + Math.abs(z) <= 1, `${x},${z} is the middle or an arm`);
  const n4 = ([x, z]) => [[x + 1, z], [x - 1, z], [x, z + 1], [x, z - 1]];
  for (const b of border) assert.ok(n4(b).some(([x, z]) => at.get(`${x},${z}`) === false), `${b} borders an interior block`);
  // and every open side of every interior block is closed by a border block
  for (const i of interior) for (const [x, z] of n4(i)) assert.ok(at.has(`${x},${z}`), `${i}'s side ${x},${z} is closed`);
});

test('DSIZE1: generated - the cross from the interior pool, the ring from the border pool, the source untouched, seeded', () => {
  const source = loc(20);
  const out = generateMediumDungeon(source);
  assert.notEqual(out, source);
  assert.equal(source.dungeon.blocks.length, 20, 'the cached location is never mutated');
  assert.equal(isMediumDungeon(out), true);
  assert.equal(isSmallerDungeon(out), false);
  assert.deepEqual(out.dungeon.blocks.map((b) => [b.x, b.z, b.isStartingBlock]), MEDIUM_LAYOUT.map(([x, z], i) => [x, z, i === 0]));
  out.dungeon.blocks.forEach((b, i) => assert.equal(/^b/i.test(b.blockName), MEDIUM_LAYOUT[i][2], `${i}: ${b.blockName}`));
  assert.deepEqual(generateMediumDungeon(loc(20)).dungeon.blocks, out.dungeon.blocks, 'the same every visit');
  // exactly GetRandomBlock's draws, in layout order, over the two filtered pools
  setSeed(777);
  const pools = { false: source.dungeon.blocks.filter((b) => !/^b/i.test(b.blockName)), true: source.dungeon.blocks.filter((b) => /^b/i.test(b.blockName)) };
  const names = MEDIUM_LAYOUT.map(([, , border]) => pools[border][randomRange(0, pools[border].length)].blockName);
  assert.deepEqual(out.dungeon.blocks.map((b) => b.blockName), names);
  const small = loc(13);
  assert.equal(generateMediumDungeon(small), small, 'at the threshold it is already medium');
  assert.throws(() => generateMediumDungeon(loc(20, PRIVATEERS_HOLD)), /main story/);
});

test('DSIZE1: the size a dungeon is built at - the guards, the quest\'s frozen size, then Smaller, then Medium', () => {
  const big = loc(20);
  assert.equal(dungeonSizeFor(big, { setting: false, medium: false }), 'full');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: true }), 'medium');
  assert.equal(dungeonSizeFor(big, { setting: true, medium: true }), 'small', 'Smaller Dungeons wins');
  assert.equal(dungeonSizeFor(big, { setting: true, medium: true, online: true }), 'full', 'online, the whole dungeon');
  assert.equal(dungeonSizeFor(loc(20, PRIVATEERS_HOLD), { setting: true, medium: true }), 'full', 'main story never shrinks');
  assert.equal(dungeonSizeFor({ hasDungeon: false }, { setting: true }), 'full');
  const machine = (state) => ({
    getSiteLinks: (type, mapId) => (type === SITE_TYPES.Dungeon && mapId === 777 ? [{ questUID: 5 }] : []),
    getQuest: () => ({ smallerDungeonsState: state }),
  });
  assert.equal(dungeonSizeFor(big, { setting: true, medium: false, questMachine: machine(MEDIUM_DUNGEONS_STATE) }), 'medium', 'the quest compiled at medium');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: true, questMachine: machine(SMALLER_DUNGEONS_STATE.Enabled) }), 'small');
  assert.equal(dungeonSizeFor(big, { setting: true, medium: true, questMachine: machine(SMALLER_DUNGEONS_STATE.Disabled) }), 'full');
  assert.equal(dungeonSizeFor(big, { setting: false, medium: true, questMachine: machine(SMALLER_DUNGEONS_STATE.NotSet) }), 'medium', 'NotSet falls to the settings');
  // DFU's own member answers as it always did
  assert.equal(useSmallerDungeon(big, { setting: true }), true);
  assert.equal(useSmallerDungeon(big, { setting: false }), false);
  assert.equal(useSmallerDungeon(big, { setting: false, questMachine: machine(MEDIUM_DUNGEONS_STATE) }), false, 'a medium quest is not small');
  // the one door
  assert.equal(dungeonLocationFor(big, { setting: false, medium: true }).dungeon.blocks.length, 13);
  assert.equal(dungeonLocationFor(big, { setting: true, medium: true }).dungeon.blocks.length, 5);
  assert.equal(dungeonLocationFor(big, { setting: false, medium: false }), big);
});

test('DSIZE1: the quest\'s stamp, the save\'s stamp and the warp - three layouts, compared whole', () => {
  assert.equal(smallerDungeonsStateNow(true, true), SMALLER_DUNGEONS_STATE.Enabled);
  assert.equal(smallerDungeonsStateNow(false, true), MEDIUM_DUNGEONS_STATE);
  assert.equal(smallerDungeonsStateNow(false, false), SMALLER_DUNGEONS_STATE.Disabled);
  const full = loc(20), med = generateMediumDungeon(loc(20)), sml = generateSmallerDungeon(loc(20));
  assert.equal(smallerDungeonsStamp(med), MEDIUM_DUNGEONS_STATE);
  assert.equal(smallerDungeonsStamp(sml), SMALLER_DUNGEONS_STATE.Enabled);
  assert.equal(smallerDungeonsStamp(full), SMALLER_DUNGEONS_STATE.Disabled);
  const S = { NotSet: 0, Disabled: 1, Enabled: 2, Medium: 3 };
  const cases = [[S.NotSet, full, false], [S.NotSet, med, false], [S.Disabled, full, false], [S.Enabled, sml, false], [S.Medium, med, false],
    [S.Disabled, med, true], [S.Disabled, sml, true], [S.Enabled, full, true], [S.Enabled, med, true], [S.Medium, full, true], [S.Medium, sml, true], [9, full, true]];
  for (const [saved, l, want] of cases) assert.equal(needsStartWarp(saved, l), want, `saved ${saved} into ${l.dungeon.medium ? 'medium' : l.dungeon.smaller ? 'small' : 'full'}`);
  assert.equal(needsStartWarp(S.Medium, loc(20, PRIVATEERS_HOLD)), false, 'never in a main-story dungeon');
});

test('DSIZE1: the ask is the enhanced skin\'s', () => {
  const skin = uiSkin(), pref = getPref(MEDIUM_DUNGEONS_PREF);
  try {
    setUiSkin('enhanced'); setPref(MEDIUM_DUNGEONS_PREF, true);
    assert.equal(mediumDungeonsWanted(), true);
    setUiSkin('classic');
    assert.equal(mediumDungeonsWanted(), false);
    setUiSkin('enhanced'); setPref(MEDIUM_DUNGEONS_PREF, false);
    assert.equal(mediumDungeonsWanted(), false);
  } finally { setUiSkin(skin); setPref(MEDIUM_DUNGEONS_PREF, pref); }
});

test('DSIZE1: the Features row - Enhanced, its own, off by default and forced off online', () => {
  const f = FEATURES.find((x) => x.id === 'medium-dungeons');
  assert.ok(f);
  assert.deepEqual(f.kinds, ['enhanced']);
  assert.deepEqual({ ...f.control }, { store: 'prefs', key: MEDIUM_DUNGEONS_PREF, initial: false, online: false });
  assert.equal(FEATURES.findIndex((x) => x.id === 'medium-dungeons'), FEATURES.findIndex((x) => x.id === 'smaller-dungeons') + 1, 'beside DFU\'s own switch');
});

test('DETECT-FINDS: a searched object\'s find is in the one loot walk, at its box\'s middle; unsearched, no Treasure', () => {
  const sb = (items) => ({ aabb: { min: [0, 0, 0], max: [2, 1, 4] }, items });
  assert.deepEqual(searchedNearbyRecord(sb([{ id: 1 }])).pos, [1, 0.5, 2]);
  assert.equal(searchedNearbyRecord(sb([{ id: 1 }, { id: 2 }])).itemCount, 2);
  assert.equal(searchedNearbyRecord({}).pos, null);
  const loot = nearbyLootRecords({ searched: [sb([{ id: 1 }]), sb([])] });
  assert.equal(loot.length, 2, 'both in the walk, as an empty corpse is');
  assert.equal(lootFlags(loot[0]), NEARBY.Treasure, 'a find lying in it is treasure');
  assert.equal(lootFlags(loot[1]), NEARBY.None, 'unsearched: nothing rolled yet, no Treasure bit');
  // and the Detect scan finds it, as it finds a pile
  const scan = updateNearbyObjects([0, 0, 0], { loot });
  assert.equal(getNearbyObjects(scan, NEARBY.Treasure).length, 1);
  assert.match(src('src/scenes/dungeonContext.js'), /loot: \(\) => nearbyLootRecords\(\{ piles: \[\.\.\.lootPiles, \.\.\.droppedLoot\._piles\], foes, searched: searchables \}\),/);
});
