import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseBsaIndex, readNifHeader, walkEsm, bodyParts, armReport,
  isFirstPersonId, FP_SKELETONS, ARM_PARTS, MW_BODY_PARTS,
} from '../src/tools/mwInspect.js';

// MW-D: the diagnostic that should have existed before any renderer.
// Fixtures are BUILT BY HAND here, byte by byte, from the layout recorded
// in bible/02-Formats/Morrowind-Rules.md Part V - which was read off
// OpenMW's own reader. A fixture generated by the code under test would
// prove nothing, and that mistake is exactly what sank the first arc.

const u32 = (n) => [n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255];
const ascii = (s) => [...s].map((c) => c.charCodeAt(0));
const zt = (s) => [...ascii(s), 0];

/** A Morrowind BSA, assembled to the letter of the recorded layout:
 *  12-byte header, ONE contiguous run of 3*filenum uint32, the string
 *  buffer, an 8*filenum hash table that the engine skips, then the data. */
function buildBsa(entries) {
  const n = entries.length;
  const names = [];
  const nameOffsets = [];
  let no = 0;
  for (const e of entries) { nameOffsets.push(no); names.push(...zt(e.name)); no += e.name.length + 1; }
  const dirsize = 12 * n + names.length;
  const table = [];
  let dataOff = 0;
  for (const e of entries) { table.push(...u32(e.data.length), ...u32(dataOff)); dataOff += e.data.length; }
  for (const off of nameOffsets) table.push(...u32(off));
  const hash = new Array(8 * n).fill(0xcd);   // read and IGNORED by the engine
  const data = entries.flatMap((e) => [...e.data]);
  return new Uint8Array([...u32(0x100), ...u32(dirsize), ...u32(n), ...table, ...names, ...hash, ...data]);
}

test('MW-D: the BSA index - the name table is at [2*filenum + i], not a second array', () => {
  // THE CORRECTION THIS PINS. The tier C rule repeated the header
  // COMMENT ("8 bytes*numfiles then 4 bytes*numfiles"); the code reads one
  // contiguous run and indexes it. Both descriptions cover the same bytes,
  // so only a fixture with DIFFERING sizes and offsets can tell them apart
  // - which is why the two entries below are deliberately unequal.
  const bsa = buildBsa([
    { name: 'meshes\\XBase_Anim.1st.nif', data: new Uint8Array([1, 2, 3, 4, 5]) },
    { name: 'meshes\\b\\B_N_Nord_M_Hand.nif', data: new Uint8Array([9, 9]) },
  ]);
  const idx = parseBsaIndex(bsa);
  assert.equal(idx.fileCount, 2);
  // names are normalised the way the VFS does it: backslash -> slash, lowercased
  assert.deepEqual(idx.files.map((f) => f.name),
    ['meshes/xbase_anim.1st.nif', 'meshes/b/b_n_nord_m_hand.nif']);
  assert.deepEqual(idx.files.map((f) => f.size), [5, 2]);
  // offsets are RELATIVE to 12 + dirsize + 8*filenum, and the hash table
  // sits between the strings and the data - forget it and every file reads
  // 16 bytes of hash as its first bytes.
  assert.equal(idx.files[0].offset, idx.dataStart);
  assert.equal(idx.files[1].offset, idx.dataStart + 5);
  assert.deepEqual([...bsa.subarray(idx.files[0].offset, idx.files[0].offset + 5)], [1, 2, 3, 4, 5]);
  assert.deepEqual([...bsa.subarray(idx.files[1].offset, idx.files[1].offset + 2)], [9, 9]);
});

test('MW-D: a wrong magic and a corrupt directory are named, not guessed at', () => {
  const bad = buildBsa([{ name: 'a', data: new Uint8Array([1]) }]);
  bad[0] = 0x02;   // id 0x102
  assert.throws(() => parseBsaIndex(bad), /not a Morrowind BSA.*0x102.*expected 0x100/);
  assert.throws(() => parseBsaIndex(new Uint8Array(4)), /too small/);
  const huge = buildBsa([{ name: 'a', data: new Uint8Array([1]) }]);
  huge[8] = 0xff; huge[9] = 0xff;   // absurd file count
  assert.throws(() => parseBsaIndex(huge), /larger than the archive/);
});

test('MW-D: the NIF header is a PREFIX test, and the bool width is a THRESHOLD', () => {
  const nif = (line, ver) => new Uint8Array([...ascii(line), 0x0a, ...u32(ver)]);
  // Morrowind: 4.0.0.2, and the real files carry a version suffix on the
  // line - so equality would reject every retail mesh.
  const mw = readNifHeader(nif('NetImmerse File Format, Version 4.0.0.2', 0x04000002));
  assert.equal(mw.ok, true);
  assert.equal(mw.magic, 'NetImmerse File Format');
  assert.equal(mw.versionText, '4.0.0.2');
  assert.equal(mw.boolBytes, 4, 'below 4.1.0.0 a NIF bool is int32');
  // the threshold is the rule, not the answer
  assert.equal(readNifHeader(nif('Gamebryo File Format, Version 10.0.1.0', 0x0a000100)).boolBytes, 1);
  assert.equal(readNifHeader(nif('NetImmerse File Format', 0x04010000)).boolBytes, 1, '4.1.0.0 exactly is int8');
  const no = readNifHeader(new Uint8Array([...ascii('PK not a nif'), 0x0a, ...u32(1)]));
  assert.equal(no.ok, false);
  assert.match(no.why, /header line is/);
});

/** A TES3 record: type[4] + uint32 size + 8 bytes of header/flags, then
 *  subrecords of name[4] + uint32 len + data. */
const sub = (name, data) => [...ascii(name), ...u32(data.length), ...data];
const body = (id, race, part, { female = false, model = 'b/x.nif', skin = true, playable = true } = {}) => {
  const d = [
    ...sub('NAME', zt(id)), ...sub('MODL', zt(model)), ...sub('FNAM', zt(race)),
    ...sub('BYDT', [MW_BODY_PARTS.indexOf(part), 0, (female ? 1 : 0) | (playable ? 0 : 2), skin ? 0 : 1]),
  ];
  return [...ascii('BODY'), ...u32(d.length), ...u32(0), ...u32(0), ...d];
};

test('MW-D: first-person is a RECORD ID ending in 1st - never a spliced filename', () => {
  // The single rule the reverted arc got wrong in kind. It rewrote the
  // MODL path to b/hand.1st.nif and asked the archive for that file; the
  // engine looks up a DIFFERENT RECORD and uses whatever MODL it carries.
  assert.equal(isFirstPersonId('b_n_nord_m_hand.1st'), true);
  assert.equal(isFirstPersonId('B_N_Nord_M_Hand.1ST'), true, 'ids are matched case-insensitively');
  assert.equal(isFirstPersonId('b_n_nord_m_hand'), false);
  const esm = new Uint8Array([
    ...body('b_n_nord_m_hand', 'nord', 'hand', { model: 'b/hand_m.nif' }),
    ...body('b_n_nord_m_hand.1st', 'nord', 'hand', { model: 'b/hand_1st_totally_different.nif' }),
  ]);
  const parts = bodyParts(esm);
  assert.equal(parts.length, 2);
  const fp = parts.find((p) => p.firstPerson);
  assert.equal(fp.model, 'b/hand_1st_totally_different.nif',
    'the .1st RECORD carries its own mesh name, unrelated to the third-person one');
});

test('MW-D: the arm report answers about the PLAYERS OWN data, slot by slot', () => {
  const esm = new Uint8Array([
    ...body('h.1st', 'nord', 'hand', { model: 'b/h1.nif' }),
    ...body('hf.1st', 'nord', 'hand', { female: true, model: 'b/h1f.nif' }),
    ...body('w', 'nord', 'wrist', { model: 'b/w.nif' }),                      // third-person only
    ...body('f.1st', 'nord', 'forearm', { model: 'b/f1.nif', skin: false }),  // clothing, not skin
    ...body('u.1st', 'khajiit', 'upperarm', { model: 'b/u1.nif' }),           // wrong race
  ]);
  const parts = bodyParts(esm);
  const rows = armReport(parts, 'Nord', false);
  assert.deepEqual(rows.map((r) => r.slot), [...ARM_PARTS], 'every arm slot is reported, present or not');
  assert.equal(rows[0].verdict, 'first-person record found');
  assert.equal(rows[0].firstPerson.id, 'h.1st');
  assert.match(rows[1].verdict, /^no \.1st record - falls back to the third-person mesh/,
    'wrist: allowed to fall back, because it is one of the four arm parts');
  assert.equal(rows[2].verdict, 'NOTHING for this slot', 'a non-skin record does not count');
  assert.equal(rows[3].verdict, 'NOTHING for this slot', 'another race does not count');
  // sex-matched where the data has it, male where it does not
  assert.equal(armReport(parts, 'nord', true)[0].firstPerson.id, 'hf.1st');
});

test('MW-D: the skeleton list names the file the reverted rig asked for', () => {
  const paths = FP_SKELETONS.map((s) => s.path);
  assert.ok(paths.includes('meshes/xbase_anim.1st.nif'), 'the male first-person skeleton');
  assert.ok(paths.includes('meshes/base_anim_female.1st.nif'));
  assert.ok(paths.includes('meshes/base_animkna.1st.nif'), 'beast races');
  const ghost = FP_SKELETONS.find((s) => s.path === 'meshes/base_anim.1st.nif');
  assert.ok(ghost, 'the hardcoded name is listed SO THE REPORT CAN SAY WHETHER IT WAS EVER THERE');
  assert.match(ghost.who, /REVERTED/);
});

test('MW-D: the ESM walk cannot desynchronise, because every record carries its size', () => {
  const esm = new Uint8Array([
    ...body('a', 'nord', 'hand'),
    ...ascii('JUNK'), ...u32(3), ...u32(0), ...u32(0), 1, 2, 3,   // unknown type, skipped by size
    ...body('b', 'nord', 'wrist'),
  ]);
  assert.deepEqual(walkEsm(esm).map((r) => r.type), ['BODY', 'JUNK', 'BODY']);
  assert.deepEqual(bodyParts(esm).map((p) => p.id), ['a', 'b'], 'the unknown record is stepped over, not fatal');
  // a truncated tail stops the walk instead of throwing - a half-copied
  // archive should report what it has, not refuse to say anything
  assert.deepEqual(walkEsm(esm.subarray(0, esm.length - 4)).map((r) => r.type), ['BODY', 'JUNK']);
});
