import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseBsaIndex, readNifHeader, walkEsm, bodyParts, armReport,
  isFirstPersonId, FP_SKELETONS, ARM_PARTS, MW_BODY_PARTS,
  scanNifRecordTypes, skinVerdict, armMeshPaths, parseMeshForPreview, meshBounds, frontViewMapper,
  skeletonReport, checkRequiredBones, FP_REQUIRED_BONES,
} from '../src/tools/mwInspect.js';

// MW-D: the diagnostic that should have existed before any renderer.
// Fixtures are BUILT BY HAND here, byte by byte, from the layout recorded
// in bible/02-Formats/Morrowind-Rules.md Part V - which was read off
// OpenMW's own reader. A fixture generated by the code under test would
// prove nothing, and that mistake is exactly what sank the first arc.

const u32 = (n) => [n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255];
const ascii = (s) => [...s].map((c) => c.charCodeAt(0));
const zt = (s) => [...ascii(s), 0];

/** A Morrowind BSA, assembled to the letter of the recorded layout:
 *  12-byte header, ONE contiguous run of 3*filenum uint32, the string
 *  buffer, an 8*filenum hash table that the engine skips, then the data. */
function buildBsa(entries) {
  const n = entries.length;
  const names = [];
  const nameOffsets = [];
  let no = 0;
  for (const e of entries) { nameOffsets.push(no); names.push(...zt(e.name)); no += e.name.length + 1; }
  const dirsize = 12 * n + names.length;
  const table = [];
  let dataOff = 0;
  for (const e of entries) { table.push(...u32(e.data.length), ...u32(dataOff)); dataOff += e.data.length; }
  for (const off of nameOffsets) table.push(...u32(off));
  const hash = new Array(8 * n).fill(0xcd);   // read and IGNORED by the engine
  const data = entries.flatMap((e) => [...e.data]);
  return new Uint8Array([...u32(0x100), ...u32(dirsize), ...u32(n), ...table, ...names, ...hash, ...data]);
}

test('MW-D: the BSA index - the name table is at [2*filenum + i], not a second array', () => {
  // THE CORRECTION THIS PINS. The tier C rule repeated the header
  // COMMENT ("8 bytes*numfiles then 4 bytes*numfiles"); the code reads one
  // contiguous run and indexes it. Both descriptions cover the same bytes,
  // so only a fixture with DIFFERING sizes and offsets can tell them apart
  // - which is why the two entries below are deliberately unequal.
  const bsa = buildBsa([
    { name: 'meshes\\XBase_Anim.1st.nif', data: new Uint8Array([1, 2, 3, 4, 5]) },
    { name: 'meshes\\b\\B_N_Nord_M_Hand.nif', data: new Uint8Array([9, 9]) },
  ]);
  const idx = parseBsaIndex(bsa);
  assert.equal(idx.fileCount, 2);
  // names are normalised the way the VFS does it: backslash -> slash, lowercased
  assert.deepEqual(idx.files.map((f) => f.name),
    ['meshes/xbase_anim.1st.nif', 'meshes/b/b_n_nord_m_hand.nif']);
  assert.deepEqual(idx.files.map((f) => f.size), [5, 2]);
  // offsets are RELATIVE to 12 + dirsize + 8*filenum, and the hash table
  // sits between the strings and the data - forget it and every file reads
  // 16 bytes of hash as its first bytes.
  assert.equal(idx.files[0].offset, idx.dataStart);
  assert.equal(idx.files[1].offset, idx.dataStart + 5);
  assert.deepEqual([...bsa.subarray(idx.files[0].offset, idx.files[0].offset + 5)], [1, 2, 3, 4, 5]);
  assert.deepEqual([...bsa.subarray(idx.files[1].offset, idx.files[1].offset + 2)], [9, 9]);
});

test('MW-D: a wrong magic and a corrupt directory are named, not guessed at', () => {
  const bad = buildBsa([{ name: 'a', data: new Uint8Array([1]) }]);
  bad[0] = 0x02;   // id 0x102
  assert.throws(() => parseBsaIndex(bad), /not a Morrowind BSA.*0x102.*expected 0x100/);
  assert.throws(() => parseBsaIndex(new Uint8Array(4)), /too small/);
  const huge = buildBsa([{ name: 'a', data: new Uint8Array([1]) }]);
  huge[8] = 0xff; huge[9] = 0xff;   // absurd file count
  assert.throws(() => parseBsaIndex(huge), /larger than the archive/);
});

test('MW-D: the NIF header is a PREFIX test, and the bool width is a THRESHOLD', () => {
  const nif = (line, ver) => new Uint8Array([...ascii(line), 0x0a, ...u32(ver)]);
  // Morrowind: 4.0.0.2, and the real files carry a version suffix on the
  // line - so equality would reject every retail mesh.
  const mw = readNifHeader(nif('NetImmerse File Format, Version 4.0.0.2', 0x04000002));
  assert.equal(mw.ok, true);
  assert.equal(mw.magic, 'NetImmerse File Format');
  assert.equal(mw.versionText, '4.0.0.2');
  assert.equal(mw.boolBytes, 4, 'below 4.1.0.0 a NIF bool is int32');
  // the threshold is the rule, not the answer
  assert.equal(readNifHeader(nif('Gamebryo File Format, Version 10.0.1.0', 0x0a000100)).boolBytes, 1);
  assert.equal(readNifHeader(nif('NetImmerse File Format', 0x04010000)).boolBytes, 1, '4.1.0.0 exactly is int8');
  const no = readNifHeader(new Uint8Array([...ascii('PK not a nif'), 0x0a, ...u32(1)]));
  assert.equal(no.ok, false);
  assert.match(no.why, /header line is/);
});

/** A TES3 record: type[4] + uint32 size + 8 bytes of header/flags, then
 *  subrecords of name[4] + uint32 len + data. */
const sub = (name, data) => [...ascii(name), ...u32(data.length), ...data];
const body = (id, race, part, { female = false, model = 'b/x.nif', skin = true, playable = true } = {}) => {
  const d = [
    ...sub('NAME', zt(id)), ...sub('MODL', zt(model)), ...sub('FNAM', zt(race)),
    ...sub('BYDT', [MW_BODY_PARTS.indexOf(part), 0, (female ? 1 : 0) | (playable ? 0 : 2), skin ? 0 : 1]),
  ];
  return [...ascii('BODY'), ...u32(d.length), ...u32(0), ...u32(0), ...d];
};

test('MW-D: first-person is a RECORD ID ending in 1st - never a spliced filename', () => {
  // The single rule the reverted arc got wrong in kind. It rewrote the
  // MODL path to b/hand.1st.nif and asked the archive for that file; the
  // engine looks up a DIFFERENT RECORD and uses whatever MODL it carries.
  assert.equal(isFirstPersonId('b_n_nord_m_hand.1st'), true);
  assert.equal(isFirstPersonId('B_N_Nord_M_Hand.1ST'), true, 'ids are matched case-insensitively');
  assert.equal(isFirstPersonId('b_n_nord_m_hand'), false);
  const esm = new Uint8Array([
    ...body('b_n_nord_m_hand', 'nord', 'hand', { model: 'b/hand_m.nif' }),
    ...body('b_n_nord_m_hand.1st', 'nord', 'hand', { model: 'b/hand_1st_totally_different.nif' }),
  ]);
  const parts = bodyParts(esm);
  assert.equal(parts.length, 2);
  const fp = parts.find((p) => p.firstPerson);
  assert.equal(fp.model, 'b/hand_1st_totally_different.nif',
    'the .1st RECORD carries its own mesh name, unrelated to the third-person one');
});

test('MW-D: the arm report answers about the PLAYERS OWN data, slot by slot', () => {
  const esm = new Uint8Array([
    ...body('h.1st', 'nord', 'hand', { model: 'b/h1.nif' }),
    ...body('hf.1st', 'nord', 'hand', { female: true, model: 'b/h1f.nif' }),
    ...body('w', 'nord', 'wrist', { model: 'b/w.nif' }),                      // third-person only
    ...body('f.1st', 'nord', 'forearm', { model: 'b/f1.nif', skin: false }),  // clothing, not skin
    ...body('u.1st', 'khajiit', 'upperarm', { model: 'b/u1.nif' }),           // wrong race
  ]);
  const parts = bodyParts(esm);
  const rows = armReport(parts, 'Nord', false);
  assert.deepEqual(rows.map((r) => r.slot), [...ARM_PARTS], 'every arm slot is reported, present or not');
  assert.equal(rows[0].verdict, 'first-person record found');
  assert.equal(rows[0].firstPerson.id, 'h.1st');
  assert.match(rows[1].verdict, /^no \.1st record - falls back to the third-person mesh/,
    'wrist: allowed to fall back, because it is one of the four arm parts');
  assert.equal(rows[2].verdict, 'NOTHING for this slot', 'a non-skin record does not count');
  assert.equal(rows[3].verdict, 'NOTHING for this slot', 'another race does not count');
  // sex-matched where the data has it, male where it does not
  assert.equal(armReport(parts, 'nord', true)[0].firstPerson.id, 'hf.1st');
});

test('MW-D: the skeleton list names the file the reverted rig asked for', () => {
  const paths = FP_SKELETONS.map((s) => s.path);
  assert.ok(paths.includes('meshes/xbase_anim.1st.nif'), 'the male first-person skeleton');
  assert.ok(paths.includes('meshes/base_anim_female.1st.nif'));
  assert.ok(paths.includes('meshes/base_animkna.1st.nif'), 'beast races');
  const ghost = FP_SKELETONS.find((s) => s.path === 'meshes/base_anim.1st.nif');
  assert.ok(ghost, 'the hardcoded name is listed SO THE REPORT CAN SAY WHETHER IT WAS EVER THERE');
  assert.match(ghost.who, /REVERTED/);
});

test('MW-D: the ESM walk cannot desynchronise, because every record carries its size', () => {
  const esm = new Uint8Array([
    ...body('a', 'nord', 'hand'),
    ...ascii('JUNK'), ...u32(3), ...u32(0), ...u32(0), 1, 2, 3,   // unknown type, skipped by size
    ...body('b', 'nord', 'wrist'),
  ]);
  assert.deepEqual(walkEsm(esm).map((r) => r.type), ['BODY', 'JUNK', 'BODY']);
  assert.deepEqual(bodyParts(esm).map((p) => p.id), ['a', 'b'], 'the unknown record is stepped over, not fatal');
  // a truncated tail stops the walk instead of throwing - a half-copied
  // archive should report what it has, not refuse to say anything
  assert.deepEqual(walkEsm(esm.subarray(0, esm.length - 4)).map((r) => r.type), ['BODY', 'JUNK']);
});

// ── MW-D2: the question MW8's design rested on ─────────────────────
//
// MW8 concluded Morrowind's arm parts are RIGID meshes hung off a bone,
// from reading OpenMW's two attach branches - never from a real file. If
// they are skinned, that fix was wrong the same way MW7's was. These pins
// cover the SCAN that asks, and they pin its honesty as hard as its
// mechanics: it must never report skinned by inference.

/** A Morrowind NIF stores each record's TYPE NAME as a sized string
 *  immediately before the record. Built here the same way. */
const nifWith = (types, { version = 0x04000002, junk = true } = {}) => {
  const out = [...ascii('NetImmerse File Format, Version 4.0.0.2'), 0x0a, ...u32(version)];
  for (const t of types) {
    out.push(...u32(t.length), ...ascii(t));
    if (junk) out.push(...[7, 0, 0, 0, 1, 2, 3]);   // a record body the scan must step over
  }
  return new Uint8Array(out);
};

test('MW-D2: the scan finds record types, and reports a skin only when it SEES one', () => {
  const rigid = skinVerdict(nifWith(['NiNode', 'NiTriShape', 'NiTexturingProperty']));
  assert.equal(rigid.ok, true);
  assert.equal(rigid.skinned, false, 'no NiSkinInstance in the file, so not skinned');
  assert.equal(rigid.shapes, 1);
  const skinned = skinVerdict(nifWith(['NiNode', 'NiTriShape', 'NiSkinInstance', 'NiSkinData']));
  assert.equal(skinned.skinned, true);
  assert.equal(skinned.skinInstances, 1);
  // THE VERDICT IS THE INSTANCE, NOT ITS NEIGHBOURS. These two files
  // separate the records that usually travel together, because a scan
  // that keys off the wrong one passes every fixture where both appear.
  assert.equal(skinVerdict(nifWith(['NiTriShape', 'NiSkinData'])).skinned, false,
    'NiSkinData alone is not a skinned shape');
  assert.equal(skinVerdict(nifWith(['NiTriShape', 'NiSkinInstance'])).skinned, true,
    'and NiSkinInstance alone IS one');
  // the verdict carries its own uncertainty - a port must not read this as a parse
  assert.match(skinned.method, /SCAN, not a parse/);
  assert.equal(skinVerdict(new Uint8Array([1, 2, 3])).ok, false, 'a non-NIF is refused, not guessed at');
});

test('MW-D2: the scan does not invent types out of vertex data', () => {
  // floats and indices are the bulk of a real mesh; none of this is a
  // length-prefixed NIF name and none of it may be counted as one.
  const noise = new Uint8Array(4000);
  for (let i = 0; i < noise.length; i++) noise[i] = (i * 37) & 0xff;
  const census = scanNifRecordTypes(noise);
  for (const [name] of census) assert.match(name, /^(Ni|RootCollisionNode|AvoidNode)/,
    `scan admitted ${name} - the Ni-prefix guard is what keeps vertex data out`);
  // a lowercase or too-short run is not a type name
  assert.equal(scanNifRecordTypes(new Uint8Array([...u32(5), ...ascii('nitri')])).size, 0);
  assert.equal(scanNifRecordTypes(new Uint8Array([...u32(2), ...ascii('Ni')])).size, 0);
  // NOTE, honestly: the length floor and the name pattern both reject that
  // one on their own, so neither is individually pinned by it. The
  // redundancy is deliberate defence in depth, and this comment exists so
  // a later reader does not mistake a surviving mutant there for a gap.
  // A WELL-FORMED NAME THAT IS NOT NIF VOCABULARY. This is what the
  // Ni-prefix guard is actually for, and the noise sweep above cannot
  // exercise it - random bytes almost never produce a valid length-prefixed
  // capitalised word, so without this the guard could be deleted unnoticed.
  const impostor = new Uint8Array([...u32(7), ...ascii('Kittens'), ...u32(6), ...ascii('NiNode')]);
  const guarded = scanNifRecordTypes(impostor);
  assert.equal(guarded.has('Kittens'), false, 'a capitalised word is not a record type');
  assert.equal(guarded.get('NiNode'), 1, 'while the real one beside it is still found');
});

test('MW-D2: an arm mesh path comes from the RECORD, never from a spliced name', () => {
  const esm = new Uint8Array([
    ...body('b_n_nord_m_hands.1st', 'nord', 'hand', { model: 'b/B_N_Nord_M_Hands.1st.NIF' }),
    ...body('b_n_nord_m_wrist', 'nord', 'wrist', { model: 'b/B_N_Nord_M_Wrist.nif' }),
  ]);
  const rows = armReport(bodyParts(esm), 'nord', false);
  const paths = armMeshPaths(rows);
  assert.equal(paths[0].path, 'meshes/b/b_n_nord_m_hands.1st.nif');
  assert.equal(paths[0].firstPerson, true);
  assert.equal(paths[0].record, 'b_n_nord_m_hands.1st');
  // the fallback slot resolves to the THIRD-person mesh, which on retail
  // data is what three of the four arm slots actually use
  assert.equal(paths[1].path, 'meshes/b/b_n_nord_m_wrist.nif');
  assert.equal(paths[1].firstPerson, false);
  // a slot with no record at all resolves to nothing, and says so
  assert.equal(paths[2].path, null);
  assert.equal(paths[2].record, null);
});

// ── MW-D3: parse it for real, and be honest when that fails ────────

test('MW-D3: the real reader runs on a real fixture mesh, and reports what it found', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const r = await parseMeshForPreview(bsa.get('meshes/fixture/plain.nif'));
  assert.equal(r.ok, true, r.error);
  assert.ok(r.vertices > 0 && r.triangles > 0, 'geometry came back');
  assert.equal(r.skinnedShapes, 0, 'plain.nif is the rigid one');
  const skinned = await parseMeshForPreview(bsa.get('meshes/fixture/skinned.nif'));
  assert.equal(skinned.skinnedShapes > 0, true, 'and skinned.nif is the other kind');
});

test('MW-D3: a failure is NAMED with its stage, never swallowed into an empty view', async () => {
  // The reverted rig's defining behaviour was to end up with nothing and
  // say nothing. Every failure path here carries a stage and a message.
  const notNif = await parseMeshForPreview(new Uint8Array([...ascii('nope'), 0x0a, 0, 0, 0, 0]));
  assert.equal(notNif.ok, false);
  assert.equal(notNif.stage, 'parse');
  assert.ok(notNif.error && notNif.error.length, 'and the reader\'s own message is passed through');
  // a well-formed header with no geometry behind it is its own answer
  const empty = await parseMeshForPreview(new Uint8Array(
    [...ascii('NetImmerse File Format, Version 4.0.0.2'), 0x0a, ...u32(0x04000002)]));
  assert.equal(empty.ok, false);
  assert.ok(['parse', 'flatten', 'geometry'].includes(empty.stage), `stage was ${empty.stage}`);
});

test('MW-D3: the front view is Z-UP and UNIFORMLY scaled', () => {
  const shapes = [{ positions: new Float32Array([0, 0, 0, 10, 0, 0, 0, 0, 5]), indices: [0, 1, 2] }];
  const b = meshBounds(shapes);
  assert.deepEqual([b.minX, b.maxX, b.minZ, b.maxZ], [0, 10, 0, 5]);
  const map = frontViewMapper(b, 100, 100, 0);
  const [x0, y0] = map(0, 0, 0);
  const [x1, y1] = map(10, 0, 0);
  const [, y2] = map(0, 0, 5);
  assert.ok(x1 > x0, 'x runs across the canvas');
  assert.ok(y2 < y0, 'and +z runs UP the screen, which canvas y does not');
  // uniform: the wider axis fills the box, the shorter one does not - a
  // per-axis fit would hide proportions that are actually wrong
  assert.equal(Math.round(x1 - x0), 100, 'the 10-unit x span fills the 100px box');
  assert.equal(Math.round(y0 - y2), 50, 'and the 5-unit z span gets half of it, not all');
  assert.equal(meshBounds([{ positions: new Float32Array(0) }]), null, 'no vertices is null, not NaN');
});

// ── MW-D4: the bones the rules name, against a real skeleton ───────

test('MW-D4: the skeleton is read and its bone lookup is CASE-INSENSITIVE', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const r = await skeletonReport(bsa.get('meshes/base_anim.nif'));
  assert.equal(r.ok, true, r.error);
  assert.ok(r.boneCount > 0, 'the fixture skeleton has bones');
  assert.ok(r.names.length > 0, 'and they are named');
  // Rule 16: lowercased on BOTH sides. The report must use the same
  // comparison the binder will, or it answers a question nobody asked.
  const any = r.names.find((n) => /[a-z]/i.test(n));
  assert.equal(r.has(any), true, 'found as written');
  assert.equal(r.has(any.toUpperCase()), true, 'and in any case');
  assert.equal(r.has('a bone no skeleton has'), false);
});

test('MW-D4: a missing bone is REPORTED missing, never quietly worked around', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const rows = checkRequiredBones(await skeletonReport(bsa.get('meshes/base_anim.nif')));
  assert.equal(rows.length, FP_REQUIRED_BONES.length, 'every required bone gets a row, present or not');
  // the fixture skeleton is a test rig, not Morrowind's - so these are
  // expected to be ABSENT, and the pin is that it SAYS so rather than
  // returning a shorter list or a cheerful default
  assert.ok(rows.some((b) => !b.present), 'the fixture lacks the retail bones and the report admits it');
  for (const row of rows) assert.equal(typeof row.present, 'boolean', `${row.name} has a verdict`);
  // the bow's bone is listed separately from every other weapon's (rule 8)
  const bow = rows.find((b) => b.name === 'Weapon Bone Left');
  assert.match(bow.why, /BOW/, 'and the bow bone says it is the bow, which is rule 8');
  assert.ok(rows.find((b) => b.name === 'Weapon Bone'), 'beside the bone every other type uses');
  // a failed read yields no rows rather than a list of false negatives
  assert.deepEqual(checkRequiredBones({ ok: false }), []);
});

test('MW-D4: a skeleton that will not parse names its stage', async () => {
  const bad = await skeletonReport(new Uint8Array([...ascii('not a nif'), 0x0a, 0, 0, 0, 0]));
  assert.equal(bad.ok, false);
  assert.equal(bad.stage, 'parse');
  assert.ok(bad.error && bad.error.length);
});
