import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseBsaIndex, readNifHeader, walkEsm, bodyParts, armReport,
  isFirstPersonId, FP_SKELETONS, ARM_PARTS, MW_BODY_PARTS,
  scanNifRecordTypes, skinVerdict, armMeshPaths, parseMeshForPreview, meshBounds, frontViewMapper,
  skeletonReport, checkRequiredBones, FP_REQUIRED_BONES,
  assembleFirstPersonArm, shapeMatchesBone, placeAtBone, armPieceRows,
  poseAssembly, clipReport, clipUnionBounds,
} from '../src/tools/mwInspect.js';

// MW-D: the diagnostic that should have existed before any renderer.
// Fixtures are BUILT BY HAND here, byte by byte, from the layout recorded
// in bible/02-Formats/Morrowind-Rules.md Part V - which was read off
// OpenMW's own reader. A fixture generated by the code under test would
// prove nothing, and that mistake is exactly what sank the first arc.

const u32 = (n) => [n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255];
const ascii = (s) => [...s].map((c) => c.charCodeAt(0));
const zt = (s) => [...ascii(s), 0];

/** A Morrowind BSA, assembled to the letter of the recorded layout:
 *  12-byte header, ONE contiguous run of 3*filenum uint32, the string
 *  buffer, an 8*filenum hash table that the engine skips, then the data. */
function buildBsa(entries) {
  const n = entries.length;
  const names = [];
  const nameOffsets = [];
  let no = 0;
  for (const e of entries) { nameOffsets.push(no); names.push(...zt(e.name)); no += e.name.length + 1; }
  const dirsize = 12 * n + names.length;
  const table = [];
  let dataOff = 0;
  for (const e of entries) { table.push(...u32(e.data.length), ...u32(dataOff)); dataOff += e.data.length; }
  for (const off of nameOffsets) table.push(...u32(off));
  const hash = new Array(8 * n).fill(0xcd);   // read and IGNORED by the engine
  const data = entries.flatMap((e) => [...e.data]);
  return new Uint8Array([...u32(0x100), ...u32(dirsize), ...u32(n), ...table, ...names, ...hash, ...data]);
}

test('MW-D: the BSA index - the name table is at [2*filenum + i], not a second array', () => {
  // THE CORRECTION THIS PINS. The tier C rule repeated the header
  // COMMENT ("8 bytes*numfiles then 4 bytes*numfiles"); the code reads one
  // contiguous run and indexes it. Both descriptions cover the same bytes,
  // so only a fixture with DIFFERING sizes and offsets can tell them apart
  // - which is why the two entries below are deliberately unequal.
  const bsa = buildBsa([
    { name: 'meshes\\XBase_Anim.1st.nif', data: new Uint8Array([1, 2, 3, 4, 5]) },
    { name: 'meshes\\b\\B_N_Nord_M_Hand.nif', data: new Uint8Array([9, 9]) },
  ]);
  const idx = parseBsaIndex(bsa);
  assert.equal(idx.fileCount, 2);
  // names are normalised the way the VFS does it: backslash -> slash, lowercased
  assert.deepEqual(idx.files.map((f) => f.name),
    ['meshes/xbase_anim.1st.nif', 'meshes/b/b_n_nord_m_hand.nif']);
  assert.deepEqual(idx.files.map((f) => f.size), [5, 2]);
  // offsets are RELATIVE to 12 + dirsize + 8*filenum, and the hash table
  // sits between the strings and the data - forget it and every file reads
  // 16 bytes of hash as its first bytes.
  assert.equal(idx.files[0].offset, idx.dataStart);
  assert.equal(idx.files[1].offset, idx.dataStart + 5);
  assert.deepEqual([...bsa.subarray(idx.files[0].offset, idx.files[0].offset + 5)], [1, 2, 3, 4, 5]);
  assert.deepEqual([...bsa.subarray(idx.files[1].offset, idx.files[1].offset + 2)], [9, 9]);
});

test('MW-D: a wrong magic and a corrupt directory are named, not guessed at', () => {
  const bad = buildBsa([{ name: 'a', data: new Uint8Array([1]) }]);
  bad[0] = 0x02;   // id 0x102
  assert.throws(() => parseBsaIndex(bad), /not a Morrowind BSA.*0x102.*expected 0x100/);
  assert.throws(() => parseBsaIndex(new Uint8Array(4)), /too small/);
  const huge = buildBsa([{ name: 'a', data: new Uint8Array([1]) }]);
  huge[8] = 0xff; huge[9] = 0xff;   // absurd file count
  assert.throws(() => parseBsaIndex(huge), /larger than the archive/);
});

test('MW-D: the NIF header is a PREFIX test, and the bool width is a THRESHOLD', () => {
  const nif = (line, ver) => new Uint8Array([...ascii(line), 0x0a, ...u32(ver)]);
  // Morrowind: 4.0.0.2, and the real files carry a version suffix on the
  // line - so equality would reject every retail mesh.
  const mw = readNifHeader(nif('NetImmerse File Format, Version 4.0.0.2', 0x04000002));
  assert.equal(mw.ok, true);
  assert.equal(mw.magic, 'NetImmerse File Format');
  assert.equal(mw.versionText, '4.0.0.2');
  assert.equal(mw.boolBytes, 4, 'below 4.1.0.0 a NIF bool is int32');
  // the threshold is the rule, not the answer
  assert.equal(readNifHeader(nif('Gamebryo File Format, Version 10.0.1.0', 0x0a000100)).boolBytes, 1);
  assert.equal(readNifHeader(nif('NetImmerse File Format', 0x04010000)).boolBytes, 1, '4.1.0.0 exactly is int8');
  const no = readNifHeader(new Uint8Array([...ascii('PK not a nif'), 0x0a, ...u32(1)]));
  assert.equal(no.ok, false);
  assert.match(no.why, /header line is/);
});

/** A TES3 record: type[4] + uint32 size + 8 bytes of header/flags, then
 *  subrecords of name[4] + uint32 len + data. */
const sub = (name, data) => [...ascii(name), ...u32(data.length), ...data];
const body = (id, race, part, { female = false, model = 'b/x.nif', skin = true, playable = true } = {}) => {
  const d = [
    ...sub('NAME', zt(id)), ...sub('MODL', zt(model)), ...sub('FNAM', zt(race)),
    ...sub('BYDT', [MW_BODY_PARTS.indexOf(part), 0, (female ? 1 : 0) | (playable ? 0 : 2), skin ? 0 : 1]),
  ];
  return [...ascii('BODY'), ...u32(d.length), ...u32(0), ...u32(0), ...d];
};

test('MW-D: first-person is a RECORD ID ending in 1st - never a spliced filename', () => {
  // The single rule the reverted arc got wrong in kind. It rewrote the
  // MODL path to b/hand.1st.nif and asked the archive for that file; the
  // engine looks up a DIFFERENT RECORD and uses whatever MODL it carries.
  assert.equal(isFirstPersonId('b_n_nord_m_hand.1st'), true);
  assert.equal(isFirstPersonId('B_N_Nord_M_Hand.1ST'), true, 'ids are matched case-insensitively');
  assert.equal(isFirstPersonId('b_n_nord_m_hand'), false);
  const esm = new Uint8Array([
    ...body('b_n_nord_m_hand', 'nord', 'hand', { model: 'b/hand_m.nif' }),
    ...body('b_n_nord_m_hand.1st', 'nord', 'hand', { model: 'b/hand_1st_totally_different.nif' }),
  ]);
  const parts = bodyParts(esm);
  assert.equal(parts.length, 2);
  const fp = parts.find((p) => p.firstPerson);
  assert.equal(fp.model, 'b/hand_1st_totally_different.nif',
    'the .1st RECORD carries its own mesh name, unrelated to the third-person one');
});

test('MW-D: the arm report answers about the PLAYERS OWN data, slot by slot', () => {
  const esm = new Uint8Array([
    ...body('h.1st', 'nord', 'hand', { model: 'b/h1.nif' }),
    ...body('hf.1st', 'nord', 'hand', { female: true, model: 'b/h1f.nif' }),
    ...body('w', 'nord', 'wrist', { model: 'b/w.nif' }),                      // third-person only
    ...body('f.1st', 'nord', 'forearm', { model: 'b/f1.nif', skin: false }),  // clothing, not skin
    ...body('u.1st', 'khajiit', 'upperarm', { model: 'b/u1.nif' }),           // wrong race
  ]);
  const parts = bodyParts(esm);
  const rows = armReport(parts, 'Nord', false);
  assert.deepEqual(rows.map((r) => r.slot), [...ARM_PARTS], 'every arm slot is reported, present or not');
  assert.equal(rows[0].verdict, 'first-person record found');
  assert.equal(rows[0].firstPerson.id, 'h.1st');
  assert.match(rows[1].verdict, /^no \.1st record - falls back to the third-person mesh/,
    'wrist: allowed to fall back, because it is one of the four arm parts');
  assert.equal(rows[2].verdict, 'NOTHING for this slot', 'a non-skin record does not count');
  assert.equal(rows[3].verdict, 'NOTHING for this slot', 'another race does not count');
  // sex-matched where the data has it, male where it does not
  assert.equal(armReport(parts, 'nord', true)[0].firstPerson.id, 'hf.1st');
});

test('MW-D: the skeleton list names the file the reverted rig asked for', () => {
  const paths = FP_SKELETONS.map((s) => s.path);
  assert.ok(paths.includes('meshes/xbase_anim.1st.nif'), 'the male first-person skeleton');
  assert.ok(paths.includes('meshes/base_anim_female.1st.nif'));
  assert.ok(paths.includes('meshes/base_animkna.1st.nif'), 'beast races');
  const ghost = FP_SKELETONS.find((s) => s.path === 'meshes/base_anim.1st.nif');
  assert.ok(ghost, 'the hardcoded name is listed SO THE REPORT CAN SAY WHETHER IT WAS EVER THERE');
  assert.match(ghost.who, /REVERTED/);
});

test('MW-D: the ESM walk cannot desynchronise, because every record carries its size', () => {
  const esm = new Uint8Array([
    ...body('a', 'nord', 'hand'),
    ...ascii('JUNK'), ...u32(3), ...u32(0), ...u32(0), 1, 2, 3,   // unknown type, skipped by size
    ...body('b', 'nord', 'wrist'),
  ]);
  assert.deepEqual(walkEsm(esm).map((r) => r.type), ['BODY', 'JUNK', 'BODY']);
  assert.deepEqual(bodyParts(esm).map((p) => p.id), ['a', 'b'], 'the unknown record is stepped over, not fatal');
  // a truncated tail stops the walk instead of throwing - a half-copied
  // archive should report what it has, not refuse to say anything
  assert.deepEqual(walkEsm(esm.subarray(0, esm.length - 4)).map((r) => r.type), ['BODY', 'JUNK']);
});

// ── MW-D2: the question MW8's design rested on ─────────────────────
//
// MW8 concluded Morrowind's arm parts are RIGID meshes hung off a bone,
// from reading OpenMW's two attach branches - never from a real file. If
// they are skinned, that fix was wrong the same way MW7's was. These pins
// cover the SCAN that asks, and they pin its honesty as hard as its
// mechanics: it must never report skinned by inference.

/** A Morrowind NIF stores each record's TYPE NAME as a sized string
 *  immediately before the record. Built here the same way. */
const nifWith = (types, { version = 0x04000002, junk = true } = {}) => {
  const out = [...ascii('NetImmerse File Format, Version 4.0.0.2'), 0x0a, ...u32(version)];
  for (const t of types) {
    out.push(...u32(t.length), ...ascii(t));
    if (junk) out.push(...[7, 0, 0, 0, 1, 2, 3]);   // a record body the scan must step over
  }
  return new Uint8Array(out);
};

test('MW-D2: the scan finds record types, and reports a skin only when it SEES one', () => {
  const rigid = skinVerdict(nifWith(['NiNode', 'NiTriShape', 'NiTexturingProperty']));
  assert.equal(rigid.ok, true);
  assert.equal(rigid.skinned, false, 'no NiSkinInstance in the file, so not skinned');
  assert.equal(rigid.shapes, 1);
  const skinned = skinVerdict(nifWith(['NiNode', 'NiTriShape', 'NiSkinInstance', 'NiSkinData']));
  assert.equal(skinned.skinned, true);
  assert.equal(skinned.skinInstances, 1);
  // THE VERDICT IS THE INSTANCE, NOT ITS NEIGHBOURS. These two files
  // separate the records that usually travel together, because a scan
  // that keys off the wrong one passes every fixture where both appear.
  assert.equal(skinVerdict(nifWith(['NiTriShape', 'NiSkinData'])).skinned, false,
    'NiSkinData alone is not a skinned shape');
  assert.equal(skinVerdict(nifWith(['NiTriShape', 'NiSkinInstance'])).skinned, true,
    'and NiSkinInstance alone IS one');
  // the verdict carries its own uncertainty - a port must not read this as a parse
  assert.match(skinned.method, /SCAN, not a parse/);
  assert.equal(skinVerdict(new Uint8Array([1, 2, 3])).ok, false, 'a non-NIF is refused, not guessed at');
});

test('MW-D2: the scan does not invent types out of vertex data', () => {
  // floats and indices are the bulk of a real mesh; none of this is a
  // length-prefixed NIF name and none of it may be counted as one.
  const noise = new Uint8Array(4000);
  for (let i = 0; i < noise.length; i++) noise[i] = (i * 37) & 0xff;
  const census = scanNifRecordTypes(noise);
  for (const [name] of census) assert.match(name, /^(Ni|RootCollisionNode|AvoidNode)/,
    `scan admitted ${name} - the Ni-prefix guard is what keeps vertex data out`);
  // a lowercase or too-short run is not a type name
  assert.equal(scanNifRecordTypes(new Uint8Array([...u32(5), ...ascii('nitri')])).size, 0);
  assert.equal(scanNifRecordTypes(new Uint8Array([...u32(2), ...ascii('Ni')])).size, 0);
  // NOTE, honestly: the length floor and the name pattern both reject that
  // one on their own, so neither is individually pinned by it. The
  // redundancy is deliberate defence in depth, and this comment exists so
  // a later reader does not mistake a surviving mutant there for a gap.
  // A WELL-FORMED NAME THAT IS NOT NIF VOCABULARY. This is what the
  // Ni-prefix guard is actually for, and the noise sweep above cannot
  // exercise it - random bytes almost never produce a valid length-prefixed
  // capitalised word, so without this the guard could be deleted unnoticed.
  const impostor = new Uint8Array([...u32(7), ...ascii('Kittens'), ...u32(6), ...ascii('NiNode')]);
  const guarded = scanNifRecordTypes(impostor);
  assert.equal(guarded.has('Kittens'), false, 'a capitalised word is not a record type');
  assert.equal(guarded.get('NiNode'), 1, 'while the real one beside it is still found');
});

test('MW-D2: an arm mesh path comes from the RECORD, never from a spliced name', () => {
  const esm = new Uint8Array([
    ...body('b_n_nord_m_hands.1st', 'nord', 'hand', { model: 'b/B_N_Nord_M_Hands.1st.NIF' }),
    ...body('b_n_nord_m_wrist', 'nord', 'wrist', { model: 'b/B_N_Nord_M_Wrist.nif' }),
  ]);
  const rows = armReport(bodyParts(esm), 'nord', false);
  const paths = armMeshPaths(rows);
  assert.equal(paths[0].path, 'meshes/b/b_n_nord_m_hands.1st.nif');
  assert.equal(paths[0].firstPerson, true);
  assert.equal(paths[0].record, 'b_n_nord_m_hands.1st');
  // the fallback slot resolves to the THIRD-person mesh, which on retail
  // data is what three of the four arm slots actually use
  assert.equal(paths[1].path, 'meshes/b/b_n_nord_m_wrist.nif');
  assert.equal(paths[1].firstPerson, false);
  // a slot with no record at all resolves to nothing, and says so
  assert.equal(paths[2].path, null);
  assert.equal(paths[2].record, null);
});

// ── MW-D3: parse it for real, and be honest when that fails ────────

test('MW-D3: the real reader runs on a real fixture mesh, and reports what it found', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const r = await parseMeshForPreview(bsa.get('meshes/fixture/plain.nif'));
  assert.equal(r.ok, true, r.error);
  assert.ok(r.vertices > 0 && r.triangles > 0, 'geometry came back');
  assert.equal(r.skinnedShapes, 0, 'plain.nif is the rigid one');
  const skinned = await parseMeshForPreview(bsa.get('meshes/fixture/skinned.nif'));
  assert.equal(skinned.skinnedShapes > 0, true, 'and skinned.nif is the other kind');
});

test('MW-D3: a failure is NAMED with its stage, never swallowed into an empty view', async () => {
  // The reverted rig's defining behaviour was to end up with nothing and
  // say nothing. Every failure path here carries a stage and a message.
  const notNif = await parseMeshForPreview(new Uint8Array([...ascii('nope'), 0x0a, 0, 0, 0, 0]));
  assert.equal(notNif.ok, false);
  assert.equal(notNif.stage, 'parse');
  assert.ok(notNif.error && notNif.error.length, 'and the reader\'s own message is passed through');
  // a well-formed header with no geometry behind it is its own answer
  const empty = await parseMeshForPreview(new Uint8Array(
    [...ascii('NetImmerse File Format, Version 4.0.0.2'), 0x0a, ...u32(0x04000002)]));
  assert.equal(empty.ok, false);
  assert.ok(['parse', 'flatten', 'geometry'].includes(empty.stage), `stage was ${empty.stage}`);
});

test('MW-D3: the front view is Z-UP and UNIFORMLY scaled', () => {
  const shapes = [{ positions: new Float32Array([0, 0, 0, 10, 0, 0, 0, 0, 5]), indices: [0, 1, 2] }];
  const b = meshBounds(shapes);
  assert.deepEqual([b.minX, b.maxX, b.minZ, b.maxZ], [0, 10, 0, 5]);
  const map = frontViewMapper(b, 100, 100, 0);
  const [x0, y0] = map(0, 0, 0);
  const [x1, y1] = map(10, 0, 0);
  const [, y2] = map(0, 0, 5);
  assert.ok(x1 > x0, 'x runs across the canvas');
  assert.ok(y2 < y0, 'and +z runs UP the screen, which canvas y does not');
  // uniform: the wider axis fills the box, the shorter one does not - a
  // per-axis fit would hide proportions that are actually wrong
  assert.equal(Math.round(x1 - x0), 100, 'the 10-unit x span fills the 100px box');
  assert.equal(Math.round(y0 - y2), 50, 'and the 5-unit z span gets half of it, not all');
  assert.equal(meshBounds([{ positions: new Float32Array(0) }]), null, 'no vertices is null, not NaN');
});

// ── MW-D4: the bones the rules name, against a real skeleton ───────

test('MW-D4: the skeleton is read and its bone lookup is CASE-INSENSITIVE', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const r = await skeletonReport(bsa.get('meshes/base_anim.nif'));
  assert.equal(r.ok, true, r.error);
  assert.ok(r.boneCount > 0, 'the fixture skeleton has bones');
  assert.ok(r.names.length > 0, 'and they are named');
  // Rule 16: lowercased on BOTH sides. The report must use the same
  // comparison the binder will, or it answers a question nobody asked.
  const any = r.names.find((n) => /[a-z]/i.test(n));
  assert.equal(r.has(any), true, 'found as written');
  assert.equal(r.has(any.toUpperCase()), true, 'and in any case');
  assert.equal(r.has('a bone no skeleton has'), false);
});

test('MW-D4: a missing bone is REPORTED missing, never quietly worked around', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const rows = checkRequiredBones(await skeletonReport(bsa.get('meshes/base_anim.nif')));
  assert.equal(rows.length, FP_REQUIRED_BONES.length, 'every required bone gets a row, present or not');
  // the fixture skeleton is a test rig, not Morrowind's - so these are
  // expected to be ABSENT, and the pin is that it SAYS so rather than
  // returning a shorter list or a cheerful default
  assert.ok(rows.some((b) => !b.present), 'the fixture lacks the retail bones and the report admits it');
  for (const row of rows) assert.equal(typeof row.present, 'boolean', `${row.name} has a verdict`);
  // the bow's bone is listed separately from every other weapon's (rule 8)
  const bow = rows.find((b) => b.name === 'Weapon Bone Left');
  assert.match(bow.why, /BOW/, 'and the bow bone says it is the bow, which is rule 8');
  assert.ok(rows.find((b) => b.name === 'Weapon Bone'), 'beside the bone every other type uses');
  // a failed read yields no rows rather than a list of false negatives
  assert.deepEqual(checkRequiredBones({ ok: false }), []);
});

test('MW-D4: a skeleton that will not parse names its stage', async () => {
  const bad = await skeletonReport(new Uint8Array([...ascii('not a nif'), 0x0a, 0, 0, 0, 0]));
  assert.equal(bad.ok, false);
  assert.equal(bad.stage, 'parse');
  assert.ok(bad.error && bad.error.length);
});

// ── MW-D5: assembly, and the two rules MW8 got backwards ──────────

test('MW-D5: rule 15 - the bone name is a PREFIX filter, with "Tri " stripped', () => {
  // How a SKINNED part picks its side. A rigid one uses the mirror
  // instead (rule 13); confusing the two is what MW8 did.
  assert.equal(shapeMatchesBone('Tri Left Hand', 'Left Hand'), true, 'the Tri convention is stripped');
  assert.equal(shapeMatchesBone('Left Hand 01', 'Left Hand'), true, 'a prefix match, not equality');
  assert.equal(shapeMatchesBone('TRI LEFT HAND', 'left hand'), true, 'case-insensitive both ways');
  assert.equal(shapeMatchesBone('Tri Right Hand', 'Left Hand'), false, 'the OTHER side is excluded');
  assert.equal(shapeMatchesBone('Right Hand', 'Left Hand'), false);
  // a nameless shape in a one-shape part file IS the part
  assert.equal(shapeMatchesBone('', 'Left Hand'), true);
  assert.equal(shapeMatchesBone(null, 'Left Hand'), true);
});

test('MW-D5: rule 13 - the mirror negates X and ONLY X, and it always runs', () => {
  // THE PIN THAT WOULD HAVE CAUGHT MW8, and it is here as a direct call
  // because it could not be reached through assembly: no fixture skeleton
  // has a bone whose name contains "left", so the assembly path never
  // took this branch and the mirror mutant SURVIVED a full sweep. A rule
  // that cannot be exercised is not pinned, whatever the output says.
  const identity = { a: [1, 0, 0, 0, 1, 0, 0, 0, 1], t: [0, 0, 0] };
  const src = new Float32Array([2, 3, 5, -7, 11, 13]);
  assert.deepEqual([...placeAtBone(src, identity, false)], [2, 3, 5, -7, 11, 13], 'the right side is untouched');
  assert.deepEqual([...placeAtBone(src, identity, true)], [-2, 3, 5, 7, 11, 13],
    'the left side negates X and leaves Y and Z alone');
  // and the bone transform still applies on top of the mirror
  const shifted = { a: [1, 0, 0, 0, 1, 0, 0, 0, 1], t: [100, 0, 0] };
  assert.deepEqual([...placeAtBone(new Float32Array([2, 0, 0]), shifted, true)], [98, 0, 0],
    'mirror first, then the bone - not the other way round');
});

test('MW-D5: assembly places a rigid part ONCE PER SIDE, through the real readers', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  // The fixture skeleton's vocabulary is Bone0/Bone1, not Morrowind's, so
  // the bones are named explicitly. Without that this test never reaches
  // the assembly path at all - which is exactly how three mutants survived
  // a full sweep the first time this was written.
  const r = await assembleFirstPersonArm({
    skeletonBytes: bsa.get('meshes/base_anim.nif'),
    parts: [{ slot: 'hand', bones: ['Bone0', 'Bone1'], bytes: bsa.get('meshes/fixture/plain.nif') }],
  });
  assert.equal(r.ok, true, `${r.error} :: ${r.notes.join(' | ')}`);
  const rigid = r.pieces.filter((p) => p.kind === 'rigid');
  assert.equal(rigid.length, 2, 'one placement per side - two bones, two pieces');
  assert.deepEqual(rigid.map((p) => p.bone), ['Bone0', 'Bone1']);
  // neither fixture bone is named "left", so neither is mirrored - the
  // mirror itself is pinned directly above, because no fixture skeleton
  // can reach it through this path
  assert.deepEqual(rigid.map((p) => p.mirrored), [false, false]);
  assert.ok(rigid[0].positions.length > 0 && rigid[0].indices.length > 0, 'with real geometry');
});

test('MW-D5: rule 15 excludes a skinned shape whose name does not match its bone', async () => {
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  // skinned.nif's one shape is named "Skinned", which is not a prefix
  // match for Bone0 - so the filter drops it and assembly yields nothing.
  // THIS IS THE RULE WORKING, and it is pinned so that deleting the filter
  // is visible: without it this returns a piece.
  const r = await assembleFirstPersonArm({
    skeletonBytes: bsa.get('meshes/base_anim.nif'),
    parts: [{ slot: 'hand', bones: ['Bone0'], bytes: bsa.get('meshes/fixture/skinned.nif') }],
  });
  assert.equal(r.pieces.filter((p) => p.kind === 'skinned').length, 0,
    'a shape the bone filter rejects contributes nothing');
  // THE GAP RECORDED HERE IS CLOSED by "MW-D6: rule 15's ACCEPT path,
  // end to end" below - armskel.nif carries Morrowind's own bone names
  // and armhand.nif names its shapes the retail way, so the ACCEPT
  // branch now runs through the real readers. This test keeps the
  // REJECT half; the two are a matched pair.
});

test('MW-D5: assembly reports WHY it produced nothing, and never silently empties', async () => {
  const bad = await assembleFirstPersonArm({
    skeletonBytes: new Uint8Array([...ascii('not a nif'), 0x0a, 0, 0, 0, 0]),
    parts: [],
  });
  assert.equal(bad.ok, false);
  assert.equal(bad.stage, 'skeleton');
  assert.ok(bad.error);
  const { readFileSync } = await import('node:fs');
  const { MwBsaFile } = await import('../src/formats/mwBsaFile.js');
  const bsa = new MwBsaFile(new Uint8Array(
    readFileSync(new URL('./fixtures/mw/fixture.bsa', import.meta.url))));
  const noParts = await assembleFirstPersonArm({
    skeletonBytes: bsa.get('meshes/base_anim.nif'), parts: [],
  });
  assert.equal(noParts.ok, false, 'no parts is not a success');
  assert.match(noParts.error, /nothing bound/);
  assert.deepEqual(noParts.pieces, []);
});

// ── MW-D6: the arm ASSEMBLES with Morrowind's own vocabulary ───────
//
// Every fixture MW-D5 had spoke SkinRoot/Bone0/Bone1 and named its shapes
// "Skinned"/"PartSkin". Two attachment rules cannot be exercised in that
// vocabulary at all, which is why MW-D5 pinned them by direct call and
// recorded the gap. armskel.nif carries rule 5's own bone names and
// armhand.nif names its shapes the retail way, so both rules now run END
// TO END through the real readers, with NO test-only `bones` override.

const armFixture = async (name) => {
  const { readFileSync } = await import('node:fs');
  return new Uint8Array(readFileSync(new URL(`./fixtures/mw/${name}`, import.meta.url)));
};

test('MW-D6: rule 15\'s ACCEPT path, end to end - each side binds its OWN shape', async () => {
  // THE GAP MW-D5 RECORDED, CLOSED. One part file carries "Tri Right Hand"
  // and "Tri Left Hand"; PART_BONES.hand is ['left hand','right hand'], so
  // the engine's two filtered passes (rule 4: one mesh part, two slots)
  // must yield one piece per side, each the shape named for it.
  const r = await assembleFirstPersonArm({
    skeletonBytes: await armFixture('armskel.nif'),
    parts: [{ slot: 'hand', bytes: await armFixture('armhand.nif') }],
  });
  assert.equal(r.ok, true, `${r.error} :: ${r.notes.join(' | ')}`);
  const skinned = r.pieces.filter((p) => p.kind === 'skinned');
  assert.equal(skinned.length, 2, 'ONE PIECE PER SIDE - a latch that stops after the first bone gives 1');
  assert.deepEqual(skinned.map((p) => p.bone), ['left hand', 'right hand']);
  assert.equal(r.pieces.filter((p) => p.kind === 'rigid').length, 0, 'both shapes are skinned');
  // and the filter put each side's geometry on its own side of x=0
  const xs = (p) => [...p.positions].filter((_, i) => i % 3 === 0);
  assert.ok(xs(skinned[0]).every((x) => x < 0), 'the left piece is the left shape');
  assert.ok(xs(skinned[1]).every((x) => x > 0), 'and the right piece the right one');
});

test('MW-D6: rule 13\'s mirror, reached END TO END through assembly', async () => {
  // MW-D5 could only pin the mirror by calling placeAtBone directly,
  // because no fixture skeleton had a bone named "left" and the branch
  // was unreachable. armskel has both sides, so the DERIVATION
  // (`/left/i` on the bone name) is now exercised too - which the direct
  // call could never test, since it takes `mirror` as an argument.
  const r = await assembleFirstPersonArm({
    skeletonBytes: await armFixture('armskel.nif'),
    parts: [{ slot: 'upperarm', bytes: await armFixture('armcuff.nif') }],
  });
  assert.equal(r.ok, true, `${r.error} :: ${r.notes.join(' | ')}`);
  const rigid = r.pieces.filter((p) => p.kind === 'rigid');
  assert.equal(rigid.length, 2, 'one placement per side');
  assert.deepEqual(rigid.map((p) => p.bone), ['left upper arm', 'right upper arm']);
  assert.deepEqual(rigid.map((p) => p.mirrored), [true, false], 'the LEFT one is mirrored, and only it');
  const bounds = (p) => {
    const xs = [...p.positions].filter((_, i) => i % 3 === 0);
    return [Math.min(...xs), Math.max(...xs)];
  };
  const [lMin, lMax] = bounds(rigid[0]);
  const [rMin, rMax] = bounds(rigid[1]);
  assert.ok(Math.abs(lMin + rMax) < 1e-5 && Math.abs(lMax + rMin) < 1e-5,
    `the left piece is the right piece with X negated, exactly (L ${lMin},${lMax} R ${rMin},${rMax})`);
  // and z is untouched by the mirror - it negates X and ONLY X
  const zs = (p) => [...p.positions].filter((_, i) => i % 3 === 2).sort();
  assert.deepEqual(zs(rigid[0]), zs(rigid[1]), 'Z is identical on both sides');
});

test('MW-D6: a NAMELESS skinned shape binds ONCE, not once per side', async () => {
  // The port EXTENDS rule 15: OpenMW's ciStartsWith("", "right hand") is
  // false and the engine drops a nameless shape, while this reader treats
  // it as "the part". The extension has a consequence the engine does not
  // have - a nameless shape passes the filter at EVERY bone - so without
  // a latch one file binds twice and the duplicate lands in the same
  // place. armnameless.nif exists solely so that branch is enterable.
  const r = await assembleFirstPersonArm({
    skeletonBytes: await armFixture('armskel.nif'),
    parts: [{ slot: 'hand', bytes: await armFixture('armnameless.nif') }],
  });
  assert.equal(r.ok, true, `${r.error} :: ${r.notes.join(' | ')}`);
  assert.equal(r.pieces.filter((p) => p.kind === 'skinned').length, 1,
    'once for the part, not once per bone');
});

test('MW-D6: a part the reader refuses is a NOTE, and the rest of the arm still assembles', async () => {
  const r = await assembleFirstPersonArm({
    skeletonBytes: await armFixture('armskel.nif'),
    parts: [
      { slot: 'hand', bytes: await armFixture('armhand.nif') },
      { slot: 'wrist', bytes: new Uint8Array([...ascii('not a nif'), 0x0a, 0, 0, 0, 0]) },
    ],
  });
  assert.equal(r.ok, true, 'one bad part does not abandon the arm');
  assert.equal(r.pieces.filter((p) => p.kind === 'skinned').length, 2, 'the good part still binds both sides');
  assert.equal(r.notes.length, 1, 'and the bad one is recorded, once');
  assert.match(r.notes[0], /^wrist:/, 'named by the slot that failed');
});

test('MW-D6: armPieceRows keys by slot AND bone, and bounds are PER PIECE', async () => {
  // A key of slot alone collides on every arm slot, because every arm
  // slot is two-boned; and the assembly-wide bounds would make both sides
  // read identically in the table, hiding the very mix-up this stage is
  // built to show.
  const r = await assembleFirstPersonArm({
    skeletonBytes: await armFixture('armskel.nif'),
    parts: [{ slot: 'hand', bytes: await armFixture('armhand.nif') }],
  });
  const rows = armPieceRows(r.pieces);
  assert.equal(rows.length, 2);
  assert.equal(new Set(rows.map((x) => x.key)).size, 2, 'the two sides get distinct keys');
  assert.deepEqual(rows.map((x) => x.key), ['hand @ left hand', 'hand @ right hand']);
  assert.deepEqual(rows.map((x) => x.triangles), [1, 1]);
  assert.deepEqual(rows.map((x) => x.vertices), [3, 3]);
  assert.ok(rows[0].bounds.maxX < 0 && rows[1].bounds.minX > 0,
    'per-piece bounds put each side on its own side of x=0');
  assert.deepEqual(armPieceRows(null), [], 'and nothing in, nothing out');
});

// --- MW-D7: THE ASSEMBLY, POSED -------------------------------------------

/** The arm MW-D6 assembles, plus the clip that drives it. Both halves come
 *  from files on disk written by pyffi, not by the code under test. */
async function posedArm() {
  const { readFileSync } = await import('node:fs');
  const { parseNif } = await import('../src/formats/mwNifFile.js');
  const { extractTracks, sampleTrack } = await import('../src/formats/mwAnim.js');
  const { accumRootRef } = await import('../src/formats/mwSkin.js');
  const f = (n) => new Uint8Array(readFileSync(new URL(`./fixtures/mw/${n}`, import.meta.url)));
  const arm = await assembleFirstPersonArm({
    skeletonBytes: f('armskel.nif'),
    parts: [{ slot: 'hand', bytes: f('armhand.nif') }, { slot: 'upperarm', bytes: f('armcuff.nif') }],
  });
  const tracks = extractTracks(parseNif(f('armidle.kf')));
  return {
    arm,
    tracks,
    sampleTrack,
    accumRoot: accumRootRef(arm.skeleton, tracks),
    at(time, opts = {}) {
      poseAssembly(arm, { tracks, sampleTrack, time, accumRoot: this.accumRoot, ...opts });
      return armPieceRows(arm.pieces);
    },
  };
}

test('MW-D7: the assembly carries what a re-pose needs, and nothing aliases', async () => {
  const { arm } = await posedArm();
  assert.equal(arm.ok, true);
  assert.ok(arm.skeleton && arm.fns, 'the skeleton and the resolved readers ride along');
  assert.ok(Number.isInteger(arm.rootRef), 'and the skeleton root, so the per-frame call is synchronous');
  for (const p of arm.pieces) {
    if (p.kind === 'skinned') {
      assert.ok(p.batch && p.batch.skin, 'a skinned piece keeps its batch - skinBatch needs it every frame');
      // THE ALIASING HAZARD, and it is not theoretical: mwViewer.js:430-436
      // copies the bind positions for exactly this reason. Alias these and
      // each frame skins the PREVIOUS frame's output and the pose runs away.
      assert.notEqual(p.positions, p.batch.positions, 'and its output buffer is its own allocation');
    } else {
      assert.ok(p.source && Number.isInteger(p.attachRef),
        'a rigid piece keeps its authored positions and its attach bone');
      assert.notEqual(p.positions, p.source, 'and writes somewhere else');
    }
  }
});

test('MW-D7: posing moves BOTH kinds of piece - a rig that only re-skins is half a rig', async () => {
  const h = await posedArm();
  const a = h.at(1.0).map((r) => r.bounds.maxX);
  const b = h.at(2.0).map((r) => r.bounds.maxX);
  const rows = h.at(2.0);
  assert.equal(rows.length, 4);
  for (let i = 0; i < rows.length; i++) {
    assert.ok(Math.abs(a[i] - b[i]) > 1e-3,
      `${rows[i].key} (${rows[i].kind}) moved between t=1.0 and t=2.0`);
  }
  // The rigid half moves because the ATTACHMENT AFFINE is recomputed from
  // the animated pose. Reuse the bind-time matrices and the cuffs freeze
  // inside hands that animate.
  const rigid = rows.filter((r) => r.kind === 'rigid');
  assert.equal(rigid.length, 2);
  assert.ok(rigid.every((r, i) => Math.abs(a[rows.indexOf(r)] - b[rows.indexOf(r)]) > 1e-3 || i < 0));
});

test('MW-D7: posing twice at one time gives the same numbers twice', async () => {
  const h = await posedArm();
  const once = h.at(2.0).map((r) => `${r.bounds.minX},${r.bounds.maxX}`).join('|');
  const twice = h.at(2.0).map((r) => `${r.bounds.minX},${r.bounds.maxX}`).join('|');
  assert.equal(once, twice, 'the pose is a function of time, not of how many frames have run');
});

test('MW-D7: the mirror is a fact about the BONE NAME, and survives the clip', async () => {
  const h = await posedArm();
  for (const t of [1.0, 1.5, 2.0, 2.5, 3.0]) {
    const rows = h.at(t);
    const by = (b) => rows.find((r) => r.bone === b);
    assert.deepEqual(rows.filter((r) => r.kind === 'rigid').map((r) => r.mirrored), [true, false],
      `t=${t}: the LEFT rigid piece is the mirrored one, and it does not change with the pose`);
    // The fixture's left arm track is the right's rotation negated about
    // Y, which the x-mirror conjugates exactly - so this holds at every
    // instant, not just at rest.
    assert.ok(Math.abs(by('left upper arm').bounds.minX + by('right upper arm').bounds.maxX) < 1e-5,
      `t=${t}: the rigid sides stay exact mirrors`);
    assert.ok(Math.abs(by('left hand').bounds.minX + by('right hand').bounds.maxX) < 1e-5,
      `t=${t}: and so do the skinned ones`);
  }
});

test('MW-D7: the accum root is extracted at the POSE, which is the only place it is real', async () => {
  const h = await posedArm();
  const bip = [...h.arm.skeleton.nodes.entries()].find(([, n]) => n.name === 'Bip01')[0];
  h.at(3.0);
  assert.deepEqual([...h.arm.pose.get(bip).translation], [0, 0, 0],
    'the root track\'s x drift is extracted - only its z reaches the pose');
  h.at(3.0, { accumRoot: null });
  assert.equal(h.arm.pose.get(bip).translation[0], 1, 'and without it the root walks to x=+1');

  // MW-D20 REACHED THE PIXELS. F1 recorded "a track on the skeleton
  // root reaches no geometry, BY CONSTRUCTION" - and the construction
  // was the port's own defect: matrices made identity AT the declared
  // root. In the reference, bone matrices include the root's ANIMATED
  // matrix (Bone::update's parentless case is the node's own matrix),
  // so keying Bip01 moves EVERYTHING - which is precisely why rule 56's
  // accum extraction exists: without it, a walk cycle's root channel
  // walks the mesh off the actor. Extraction is now measurable where it
  // is real: at the geometry.
  const withRoot = h.at(3.0).map((r) => r.bounds.maxX);
  const without = h.at(3.0, { accumRoot: null }).map((r) => r.bounds.maxX);
  for (let i = 0; i < withRoot.length; i++) {
    assert.ok(Math.abs((without[i] - withRoot[i]) - 1) < 1e-5,
      `piece ${i}: the unextracted root track carries the geometry exactly its x=+1 drift`);
  }
});

test('MW-D7: a channel a track lacks is rewritten from REST every frame, not held', async () => {
  const h = await posedArm();
  // The forearm tracks are translation-only. Their rotation must come
  // back from node.rest on EVERY pose - a port that caches the last
  // frame's rotation compounds whatever the previous frame left, which is
  // the bug OpenMW's own comment exists to prevent.
  const fore = [...h.arm.skeleton.nodes.entries()].find(([, n]) => n.name === 'Right Forearm');
  const rest = [...fore[1].rest.rotation];
  for (const t of [1.0, 2.0, 3.0, 1.0]) {
    h.at(t);
    assert.deepEqual([...h.arm.pose.get(fore[0]).rotation], rest, `t=${t}: rotation is the rest rotation`);
  }
  // while its translation genuinely animates
  h.at(1.0);
  const a = h.arm.pose.get(fore[0]).translation[2];
  h.at(2.0);
  assert.ok(Math.abs(a - h.arm.pose.get(fore[0]).translation[2]) > 1e-3, 'and the keyed channel moves');
});

test('MW-D7: clipReport is one account of the file, refusal included', async () => {
  const { readFileSync } = await import('node:fs');
  const { parseNif } = await import('../src/formats/mwNifFile.js');
  const { buildSkeleton } = await import('../src/formats/mwSkin.js');
  const f = (n) => new Uint8Array(readFileSync(new URL(`./fixtures/mw/${n}`, import.meta.url)));
  const skel = buildSkeleton(parseNif(f('armskel.nif')));
  const r = await clipReport({ kfBytes: f('armidle.kf'), skeleton: skel, group: 'Idle' });
  assert.equal(r.ok, true);
  assert.equal(r.clip.startTime, 1);
  assert.equal(r.clip.stopTime, 3);
  // Infinity does not survive a page evaluation - it JSON-serialises to
  // null - so the boolean is what a probe can actually read.
  assert.equal(r.loopStopFinite, false);
  assert.equal(JSON.parse(JSON.stringify({ x: r.clip.loopStopTime })).x, null,
    'which is exactly why the boolean exists');
  assert.equal(r.binding.matched.length, 5);
  assert.equal(r.tracks.length, 5);
  // The divergence the page shows rather than argues.
  assert.equal(r.legacy.start, 1);
  assert.equal(r.legacy.stop, 0.5, 'the group LISTING reads a range that runs backwards on this data');

  // A .kf keyed to foreign bones: the report must say BOTH things.
  const blind = await clipReport({ kfBytes: f('xfixture.kf'), skeleton: skel, group: 'Idle' });
  assert.equal(blind.ok, true, 'the file parses fine - that is the whole danger');
  assert.equal(blind.clip.ok, false);
  assert.equal(blind.binding.matched.length, 0);
  assert.deepEqual(blind.binding.unmatchedTracks, ['bone1']);
  const none = await clipReport({ kfBytes: null });
  assert.equal(none.ok, false, 'and a missing animation source is named, not treated as an empty clip');
});

test('MW-D7: the draw mapper is fixed over the WHOLE clip, not per frame', async () => {
  const h = await posedArm();
  // The sample order matters to this pin. t=3.0 is the widest frame, so a
  // "union" that simply kept the LAST frame would pass a monotone list by
  // accident. Put the extremum in the middle.
  const times = [1.0, 1.5, 3.0, 2.5, 2.0];
  const union = clipUnionBounds(h.arm, (t) => h.at(t), times);
  const each = times.map((t) => { h.at(t); return h.arm.bounds; });
  assert.ok(union.maxX >= Math.max(...each.map((b) => b.maxX)) - 1e-9);
  assert.ok(union.minX <= Math.min(...each.map((b) => b.minX)) + 1e-9);
  assert.ok(each.some((b) => b.maxX < union.maxX - 1e-3),
    'and it is genuinely WIDER than some frames - a per-frame mapper would rescale those and hide the motion');
});

test('MW-D9d: NiCamera parses, and the records after it stay in sync', async () => {
  const { readFileSync } = await import('node:fs');
  const { parseNif } = await import('../src/formats/mwNifFile.js');
  const { buildSkeleton } = await import('../src/formats/mwSkin.js');
  const bytes = new Uint8Array(readFileSync(new URL('./fixtures/mw/armskelcam.nif', import.meta.url)));

  // REPORTED LIVE (Mac, MW-D9): `skeleton: NIF: unimplemented record type
  // "NiCamera" (record 17)`. Retail first-person skeletons carry one -
  // rule 54's camera tracks a node named "Camera" - and an unimplemented
  // type is FATAL to a 4.0.0.2 NIF, because there are no per-record
  // sizes and so nothing can be skipped. One missing reader cost the
  // whole file.
  const nif = parseNif(bytes);
  const cam = nif.records.find((r) => r.type === 'NiCamera');
  assert.ok(cam, 'the camera record is read rather than throwing');
  assert.equal(cam.name, 'Camera');
  // The values, so a WRONG-BUT-SAME-LENGTH layout is caught too.
  assert.equal(cam.frustum.left, -0.5);
  assert.equal(cam.frustum.right, 0.5);
  assert.equal(cam.frustum.far, 1000);
  assert.equal(cam.viewport.right, 1);
  assert.equal(cam.lodAdjust, 1);

  // AND THE REAL TEST: the fixture puts a bone AFTER the camera, so a
  // wrong field count desyncs the stream and this bone comes out wrong
  // or the parse dies. A camera written last would hide that entirely.
  const skel = buildSkeleton(nif);
  assert.ok(skel.byName.has('bip01 spine1'),
    'the record after the camera is still readable - the field count is right');
  assert.ok(skel.byName.has('weapon bone') && skel.byName.has('weapon bone left'),
    'and everything before it survived too');
});
