// PERF-V8 (2026-10-10, the owner: "performance must be highest priority now, it even runs shoppy on my nasa pc"):
// THE WORLD HOST'S FRAME IS A FUNCTION V8 WILL OPTIMIZE (bible/07-Rendering/Performance-Priority.md; PERF-NEXT item 22).
//
// V8 never optimizes a function whose bytecode is over --max-optimized-bytecode-size (61,440 bytes): it runs in the
// interpreter and the baseline compiler for the page's whole life - its arithmetic boxed, its for-of loops allocating an
// iterator result a step. The world host's `frame` was 105,768 bytes, the one per-frame function over the line, and every
// loop it held inline (the pixel walk over every streamed pixel's models and flats, the townspeople, the peers' batches)
// ran there every frame, whatever the machine. Its largest self-contained statements now run as closures of their own,
// made in place (`const frameMotor = () => {   // PERF-V8` ... `};` and the call), every line of theirs as it was.
//
// ONE: every function named `frame` in the world host's module graph - and every closure moved out of one, each named
// `frame...` so V8's filter prints it - is under the ceiling, and under three quarters of it: the room a host frame grows
// into before the next statement is moved out (a frame grew ~6 KB in the three days before this pin; one statement put
// back can add 7 KB - past r123 a register's operands go wide). TWO: what was moved out runs where it ran, as it ran -
// each closure is called once, right after it is made, in the frame, in the order its statement stood, and holds one
// statement that declares nothing, returns nothing out of the frame and hoists no `var` out of it (the frame exits early
// by `return`; a `return` moved into a closure would leave the closure alone and run the rest of the frame).
//
// AUDIT PERF-V8 (2026-10-10, the owner: "Lets do an audit on this"): the first cut measured `frame` alone (the motor's
// closure, 16 KB, unmeasured), counted "20 or more" closures (one folded back passed) and read the rules once over the
// parse, by hand; they are read over the parse here, every run.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { parse } from 'acorn';

const WORLD = new URL('../src/scenes/world.js', import.meta.url);

/** The statements moved out of the world host's frame, in the order they stand. */
const CLOSURES = ['frameMotor', 'frameDwTerrainPass', 'frameOriginShift', 'framePixelChanged', 'frameDistantStorm', 'frameDreadStorm', 'frameGateStorm',
  'frameLanterns', 'framePixelWalk', 'frameRing', 'frameWater', 'frameLocationRect', 'framePopulation', 'framePools', 'frameGrass', 'frameBanners',
  'frameHaze', 'frameCurtains', 'frameSpells', 'frameHud', 'framePace'];

test('PERF-V8: every `frame` in the world host\'s graph, and every closure moved out of one, is bytecode V8 optimizes - under --max-optimized-bytecode-size, and under three quarters of it (mutant: a moved statement folded back into the frame)', (t) => {
  const opts = spawnSync(process.execPath, ['--v8-options'], { encoding: 'utf8' }).stdout;
  const ceiling = Number(/default: --max-optimized-bytecode-size=(\d+)/.exec(opts)?.[1]);
  assert.ok(ceiling > 0, 'this node says its ceiling');
  // compiled eagerly (--no-lazy) at the graph's link, before any module runs - a module that cannot run in node (an
  // import.meta.glob) has printed its functions by then; `frame*` takes the closures (`frameMotor`) with the frames
  const out = spawnSync(process.execPath, ['--no-lazy', '--print-bytecode', '--print-bytecode-filter=frame*', '--input-type=module', '-e',
    `await import(${JSON.stringify(WORLD.href)}).catch(() => {})`], { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
  const fns = [...out.stdout.matchAll(/\[generated bytecode for function: (frame\w*) [^\n]*\]\n(?:[^\n]*\n){0,4}?Bytecode length: (\d+)/g)].map((m) => ({ name: m[1], size: Number(m[2]) }));
  const frames = fns.filter((f) => f.name === 'frame'), moved = fns.filter((f) => CLOSURES.includes(f.name));
  assert.ok(frames.length >= 3, `the hosts' frames printed (${frames.length}; ${out.stderr.slice(0, 200)})`);
  assert.deepEqual([...new Set(moved.map((f) => f.name))].sort(), [...CLOSURES].sort(), 'every closure moved out printed');
  const most = frames.reduce((a, f) => Math.max(a, f.size), 0), mostMoved = moved.reduce((a, f) => (f.size > a.size ? f : a), moved[0]);
  t.diagnostic(`the largest frame: ${most} bytes of bytecode against the ceiling's ${ceiling} (${frames.length} frames in the graph); the largest closure: ${mostMoved.name}, ${mostMoved.size}`);
  for (const f of [...frames, ...moved]) {
    assert.ok(f.size < ceiling, `${f.name}: ${f.size} bytes is over the ceiling (${ceiling}) - never optimized`);
    assert.ok(f.size < ceiling * 3 / 4, `${f.name}: ${f.size} bytes is within a quarter of the ceiling (${ceiling}) - move its next self-contained statement into a closure of its own, as PERF-V8's are`);
  }
});

/** Walk `node`'s children, not into a nested function (its `return` and `var` are its own). */
function walk(node, visit, top = true) {
  if (!node || typeof node.type !== 'string') return;
  if (!top && /Function/.test(node.type)) return;
  visit(node);
  for (const k of Object.keys(node)) {
    const v = node[k];
    if (Array.isArray(v)) for (const c of v) walk(c, visit, false);
    else if (v && typeof v.type === 'string') walk(v, visit, false);
  }
}

test('PERF-V8: each closure moved out of the world host\'s frame is made in the frame and called once, on the line after its own close, in the order the statements stood; each holds one statement that declares nothing, returns nothing and hoists no `var` (mutants: a closure made and never called; called twice by `?.()`; one folded back; a `return` moved into one)', () => {
  const src = readFileSync(WORLD, 'utf8');
  const at = src.indexOf('\n  function frame(now) {\n');
  const end = src.indexOf('\n  }\n', at);
  assert.ok(at > 0 && end > at, 'the frame found');
  const text = src.slice(at + 1, end + 4);
  const ast = parse(text, { ecmaVersion: 'latest', sourceType: 'script', allowReturnOutsideFunction: true });
  const frame = ast.body[0];
  assert.equal(frame.type, 'FunctionDeclaration'); assert.equal(frame.id.name, 'frame');
  const body = frame.body.body;
  const made = [];
  body.forEach((st, i) => {
    if (st.type !== 'VariableDeclaration' || st.declarations.length !== 1) return;
    const d = st.declarations[0];
    if (d.init?.type !== 'ArrowFunctionExpression') return;
    const line = text.slice(st.start, text.indexOf('\n', st.start));
    if (!line.includes('// PERF-V8')) return;
    made.push({ name: d.id.name, i, fn: d.init });
  });
  assert.deepEqual(made.map((m) => m.name), CLOSURES, 'the moved statements, by name, in the order they stood');
  const uses = new Map(CLOSURES.map((n) => [n, 0]));
  walk(frame.body, (n) => { if (n.type === 'Identifier' && uses.has(n.name)) uses.set(n.name, uses.get(n.name) + 1); });
  for (const { name, i, fn } of made) {
    const call = body[i + 1];
    assert.ok(call?.type === 'ExpressionStatement' && call.expression.type === 'CallExpression' && !call.expression.optional
      && call.expression.callee.type === 'Identifier' && call.expression.callee.name === name && call.expression.arguments.length === 0, `${name}: called on the statement after it`);
    assert.equal(text.slice(fn.body.end, call.start), ';\n    ', `${name}: on the line after its close`);
    assert.equal(uses.get(name), 2, `${name}: made, and called once - nowhere else`);
    assert.equal(fn.body.type, 'BlockStatement', `${name}: a block`);
    assert.equal(fn.body.body.length, 1, `${name}: one statement`);
    assert.ok(!/Declaration$/.test(fn.body.body[0].type), `${name}: which declares nothing the frame could read after it`);
    walk(fn.body, (n) => {
      assert.notEqual(n.type, 'ReturnStatement', `${name}: no return - the frame's would leave the closure alone`);
      if (n.type === 'VariableDeclaration') assert.notEqual(n.kind, 'var', `${name}: no var - the frame's would hoist into the closure`);
    });
  }
});
