// PERF-V8 (2026-10-10, the owner: "performance must be highest priority now, it even runs shoppy on my nasa pc"):
// THE WORLD HOST'S FRAME IS A FUNCTION V8 WILL OPTIMIZE (bible/07-Rendering/Performance-V8.md; PERF-NEXT item 22).
//
// V8 never optimizes a function whose bytecode is over --max-optimized-bytecode-size (61,440 bytes): it runs in the
// interpreter and the baseline compiler for the page's whole life - its arithmetic boxed, its for-of loops allocating an
// iterator result a step. The world host's `frame` was 105,768 bytes, the one per-frame function over the line, and every
// loop it held inline (the pixel walk over every streamed pixel's models and flats, the townspeople, the peers' batches)
// ran there every frame, whatever the machine. Its largest self-contained statements now run as closures of their own,
// made in place (`const motorStep = () => {   // PERF-V8` ... `};` and the call), every line of theirs as it was.
//
// ONE: every function named `frame` in the world host's module graph is under the ceiling, and under three quarters of
// it - the room a host frame grows into before the next statement is moved out (a frame grew ~6 KB in the three days
// before this pin). TWO: what was moved out runs where it ran - each closure is called once, right after it is made, in
// the frame, in the order its statement stood (the source pins read the order; this reads that nothing was left uncalled).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const WORLD = new URL('../src/scenes/world.js', import.meta.url);

test('PERF-V8: every `frame` in the world host\'s graph is bytecode V8 optimizes - under --max-optimized-bytecode-size, and under three quarters of it (mutant: a moved statement folded back into the frame)', (t) => {
  const opts = spawnSync(process.execPath, ['--v8-options'], { encoding: 'utf8' }).stdout;
  const ceiling = Number(/default: --max-optimized-bytecode-size=(\d+)/.exec(opts)?.[1]);
  assert.ok(ceiling > 0, 'this node says its ceiling');
  // compiled eagerly (--no-lazy) at the graph's link, before any module runs - a module that cannot run in node (an
  // import.meta.glob) has printed its functions by then
  const out = spawnSync(process.execPath, ['--no-lazy', '--print-bytecode', '--print-bytecode-filter=frame', '--input-type=module', '-e',
    `await import(${JSON.stringify(WORLD.href)}).catch(() => {})`], { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
  const frames = [...out.stdout.matchAll(/\[generated bytecode for function: frame [^\n]*\]\n(?:[^\n]*\n){0,4}?Bytecode length: (\d+)/g)].map((m) => Number(m[1]));
  assert.ok(frames.length >= 3, `the hosts' frames printed (${frames.length}; ${out.stderr.slice(0, 200)})`);
  const most = Math.max(...frames);
  t.diagnostic(`the largest frame: ${most} bytes of bytecode against the ceiling's ${ceiling} (${frames.length} frames in the graph)`);
  assert.ok(most < ceiling, `a frame of ${most} bytes is over the ceiling (${ceiling}) - never optimized`);
  assert.ok(most < ceiling * 3 / 4, `a frame of ${most} bytes is within a quarter of the ceiling (${ceiling}) - move its next self-contained statement into a closure of its own, as PERF-V8's are`);
});

test('PERF-V8: each closure moved out of the world host\'s frame is made in the frame and called once, on the line after its own close, in the order the statements stood (mutant: a closure made and never called)', () => {
  const src = readFileSync(WORLD, 'utf8');
  const at = src.indexOf('\n  function frame(now) {\n');
  const end = src.indexOf('\n  }\n', at);
  assert.ok(at > 0 && end > at, 'the frame found');
  const body = src.slice(at, end);
  const made = [...body.matchAll(/\n {4}const (\w+) = \(\) => \{ {3}\/\/ PERF-V8\n/g)];
  assert.ok(made.length >= 20, `the moved statements (${made.length})`);
  let prev = -1;
  for (const m of made) {
    const name = m[1];
    const close = body.indexOf('\n    };\n', m.index + 1);
    assert.ok(close > m.index, `${name}: closed`);
    assert.equal(body.slice(close, close + `\n    };\n    ${name}();\n`.length), `\n    };\n    ${name}();\n`, `${name}: called on the line after its close`);
    assert.equal(body.split(`${name}()`).length - 1, 1, `${name}: called once`);
    assert.ok(m.index > prev, `${name}: in the order the statements stood`);
    prev = close;
  }
});
