// SLAM8 (2026-09-16, AUDIT SLAM): RELAY_VERSION CANNOT BE FORGOTTEN AGAIN.
//
// The line above `RELAY_VERSION` has said "Bump it with every relay-changing slice" since WORLD1, and SLAM5 changed
// the relay's hello path - the 130-player wall - and left it at `world67`. So `world67` named BOTH the relay that
// stops an event at 130 players and the one that does not, and `/health` is the only pre-flight check this port has
// on event day: the relay is deployed by hand and nothing in CI deploys it.
//
// A hand-maintained constant beside a comment asking politely will be forgotten again; that is what a comment is.
// So the version is bound to the LAW ITSELF here. `server/src/index.js` is the relay and `src/net/wire.js` is the
// law it runs (re-exported by server/src/relay.js), and a change to either is a change to what a deployed worker
// does. Change one of those files and this pin fails until a NEW version with its own hash is added below - and it
// has to be new, because the old version's recorded hash is the old bytes and stays that way.
//
// This deliberately fires for a comment-only edit too. `/health` answers "is the worker running the bundle I built?",
// and a bundle whose comments differ is a different bundle; a version that is only sometimes trustworthy is the
// thing that just cost us.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { graph } from './importGraph.mjs';   // ACC4: the walk moved to a helper so the ACCOUNT Worker's deploy filter is held to its own graph by the same law
import { RELAY_VERSION } from '../src/net/wire.js';   // LOCALDEV1: the worker entry exports handlers alone

/** SLAM13 (AUDIT SLAM, final lens): THE LAW IS THE WHOLE BUNDLE, not two files. wrangler bundles every relative import
 *  the worker reaches - server/src/relay.js, src/net/wire.js and, since ONCRASH1, src/world/mat4.js (wrapAngle, which
 *  poseChanged and validPose run on every pose) - and an edit to any of them is a different deployed worker under the
 *  same name. So from world73 on the hash walks the import graph from server/src/index.js: every relative `from '...'`,
 *  depth first, each file once, in the order the imports are written. A file joining the graph changes the hash too,
 *  which is the point - a new import is a new bundle. Rows before world73 were sha256(index.js + wire.js) and stay
 *  as recorded: they are facts about bytes already deployed, under the hash law of their day. */
export const RELAY_GRAPH = graph('server/src/index.js');

/** A version bump is `sed world<N>/world<N+1>` over nine test files - RUN IT WITH THIS FILE EXCLUDED, or it
 *  rewrites a row's KEY and relabels bytes already deployed (AUDIT SLAM / SLAM9 did exactly that, and this pin caught it).
 *  Every relay this repo has shipped a law for, and the sha256 of its law that IS it (see `graph` for what the law is).
 *  Append; never edit an existing row - an old row is a historical fact about bytes that have already been deployed. */
const LAW = {
  world69: '27da57b0787d8e18e93dea8358614d9af2e9c65133774755f39960e0ec8f89de',   // SLAM8: a keepalive is never tiered; turn counts what was relayed
  world70: '06cb8eb45de961f9756a71a3cfba19fd84e3a3e7a5217d5e3798e3b11cf4ebed',   // SLAM9: the who budget derived from the socket gates, spent before the scan
  world71: '37bfb4d0bc508775233bcbabbe4bbd7b1b4dc4fccd148e9a17c72fba0dd0e877',   // SLAM10: the far tier bucketed by the listener's id, stable under movement
  world72: 'de19e038912ea8e2e0568923bcf398b86ea2c80c173051129c0ece93bf6efa51',   // SLAM11: the memory push and the act fan borrow against their budgets and land whole
  world73: 'c12e8b6497602a53eead0f4b7abb41a0f6b65be217e174e9ed11c0244a9362ba',   // SLAM13: the keepalive floor, the sender's act share, the memory a listener at a time, the yaw seam, the version in the welcome (first row over the import graph)
  world74: 'f09ab5bdcc836a30fe540d4558a7d0a6c1c933130d9db4d61d5e86c896b55595',   // MERGE (SLAM13 + SRV-N/CHAT-G onto main): one `v` on every welcome, last; the chat's third gate reaches nameFilter.js
  world75: '4587d8fa5adbfc5df062feb6831c1d191ac0563b7312d4bff7d311aa00093cac',   // SLAM15: a stop is heard whole, under the keepalive's floor
  world76: '6f7d8d11d5c055d02fadc70935d9951b3c99732f8b59c9f9f4b72363b873781f',   // LOCALDEV1: the worker entry no longer exports the version string (workerd refused the bundle locally)
  world77: 'b8daad37e99a5f42c73910a000a44c3cca5d82c955cfed8bb064c10239e6aa60',   // ROSTER-G: the channel's welcome names its members with the true count; its joins and leaves are said
  world78: '059dda8d32a6e836c44d67cb2a81e969f7d9f15468e60262f57798b37c083ec6',   // SOC1: the world channel is the social hub - accounts (id + secret beside the peer's), friends, requests, presence and last-seen, four-seat parties, the party pose fan
  world79: '1ce0aa5a1a3080a2ce121be6e9bb832cd4f5a0312dd47bb18963aebfacd03a6a',
  world80: 'fc02a655c311d19778d026248c77d6a2f85bf25888865942e0520164db7bac8d',   // RESPAWN1: validSharedFoe takes `team`/`mobileTeam` as the MobileTeams NAME - the numeric law refused every foe record a dungeon published, so every memory restored empty and every kill came back alive   // AUDIT SOC: the hub's cooldowns, the paged sweep of idle accounts and lapsed parties, pending rows without presence, by-account acts for relations alone, the record cache, the newest tab speaking, the replaced socket's leave, the clock on the channel welcome, `peers` on the picture, the act projected at the door
  world81: '38878bdb5febe591e819830f195ef68f75a620930f4f35d08e18984887559328',   // AUDIT WATCH1 A1: wire.js gained CELL_WATCH_PUPPETS_MAX (the reader's allowance for a criminal's watch beside its foes) - no relay behaviour moved, the bytes did
  world82: '2c97add60a97d56f949ce6af4f8bba4947a862ad75183c578803c1c62864325a',
  world83: '30d4fd6bb7a536b22ff0c01c08db137026181e39d0222b3607db30a43014f21e',
  world84: '3cb3d6118b2798c89790a182d0d3eb69bd8f5bfb1cb87fcb997b0d50c2e433e2',
  world85: '87888cc6cd63b20a02967f9d839ca20781d453585baf41e482ad58f2cd0f5878',   // ACC1d: THE TOKEN SEAM. server/src/index.js imports src/net/identityToken.js, so the module joins the bundle and the hash changes for that alone; wire.js carries `tok` on the hello (shape only - parseClient is sync and pure and the crypto is the relay's); the room verifies, takes the name OUT of the token, spends each signature once per room (F8, Mac: a token is spent once), and marks the frames it vouches for with `v`. The key and the TTL ceiling are config beside each other in server/wrangler.toml.   // RELAY-H1: HEARTBEAT_MS 5000 -> 20000 and PING_MS beside it in wire.js (the standing player's liveness rides the runtime-answered ping, so the object sleeps between poses); KEEPALIVE_FAN_MS follows; the relay's own SLAM8 comment notes the pair moved   // ONLINE-CLASS1: validLook carries the character's class name (letters-only, optional), so a peer without a Morrowind body stands as its class-enemy sprite; an older peer's look without it still validates   // AUDIT ALL (the merge): the main merge moved a comment line in wire.js under world81 and the row was rewritten in place - SLAM5 verbatim; world81 restored to the audit's bytes, world82 names today's
  world86: '35e2f0bb2c14248083dd5514c52951015b85646d9d97ee207e4162684f4f1a2b',   // ACC1g: THE WALL MOVES TO THE DOOR (Mac: "You shouldnt be able to just type a name and enter anymore.... this is what the account system is for"). server/src/index.js `_named` REFUSES a hello with no token and one it has no usable key to check - the two arms ACC1d admitted, and admitting them was the hole ACC1a opened this arc to close: the name on a hello was the client's own and the relay only sanitised it. A GUEST IS NOT SHUT OUT - a guest session mints a token like anybody else, so the cost to a new player is one press and no email. AND `v` LEAVES THE WIRE IN THE SAME DEPLOY: every admitted socket is verified now, so the per-name verdict on the join, the roster (wire.js `rosterFor`) and the chat line said the same thing about everybody - a field carrying no information. It goes here rather than in a later slice because a wire change costs a drop and this deploy is already paying for one; ACC1d-MARK, its only reader, is retired with it.
  world87: 'b35a4d0ec7579023e6ba83ea894ceeba3bd65c26f22ea9a568e9de94eb7b4150',   // ACC3: TITLES AND GLYPHS RIDE THE SIGNATURE (Mac: "Player titles appear above a player name... name glyphs... appear on the right side"). src/net/identityToken.js gains TITLES, GLYPHS and the `t`/`g` claims, validated against those two closed lists before a token verifies; server/src/index.js `_named` reads both OUT of the verified claims, and wire.js `badged` puts them on the welcome's roster rows, the join, the channel roster and the `who` answer - absent, never null, when there is no badge. A CLIENT NEVER ASSERTS EITHER, which is ACC1g's law applied to a stronger claim than a name: a title over somebody's head reads as this project's own word about them. The deployed relay is still world84, so world86 and world87 ride ONE drop between them.
  world88: 'b96b8ca4a994bf052081da4499f6b34d864bf8ceb03fd8c27aa981c03510747d',   // ACC3b: `readBadge`, the INVERSE of world87's `badged`, in wire.js beside it - the client's half of one field, so a badge cannot be written one way and understood another. It is the relay's bundle only because the pair lives together; the relay never calls it (it reads a badge out of a verified token, never off the wire). wire.js imports the vocabulary from identityToken.js, which was already in the graph, so the bundle gained bytes and no file.
  world89: 'c6bbe33551e8d6be470e63cb75cfa75dd9012ebe56dad189b7681f4a8d573067',   // RED1: THE SERVER SPEAKING (Mac: "a red text system (kind of like warframe) where I can message chat as the server before we merge"). A `say` frame in, a `red` frame out to every socket in the room, and THE AUTHORITY IS THE DEV GLYPH THE TOKEN ALREADY CARRIED - `a.glyphs` was written by `_named` off the verified claims and can be written by nothing else on that socket, so the right to speak as the server is the same fact as the mark beside the name, granted and revoked the same way, with no second password, no admin route and no second key to leak. Its own bucket at RED_HZ_MAX, deliberately well under chat's, because a player's line reaches a room and this reaches every player in the game. The line carries no id and no name, because nobody is speaking it - and it is its OWN frame type rather than a flag on a chat line, so the client marks it from the type, which no player can send.
  world90: '7f109a2bc863ab36fe9517fad4c43300e4409839ad8036459024fd0db4e443aa',   // MOD1: THE MODERATOR'S MUTE (Mac: "a moderator glyph and moderator chat commands" - /mute, /unmute, the blue shield). identityToken.js gains the `mod` glyph, the `mu` claim (a mute rides the signature, so a reconnect cannot shed one) and a second token SHAPE - the mute ORDER, `{o:'mute', s, mu}`, which one key signs beside identities and which the claim shapes keep apart both ways. server/src/index.js keeps the verified account (`sub`) and the mute (`mu`) on the attachment, refuses a muted line and tells only its sender, and gains a `mute` arm that believes the ORDER'S SIGNATURE and never its carrier, the newest order per account winning (`_orders`) so a replay cannot undo an unmute and a token older than the order is held to it. wire.js carries `{t:'mute', order}` in, `{t:'muted', until}` out, `sub` on chat lines and a channel's roster and joins, MUTE_HZ_MAX. The key load moved into `_loadKey` so the hello and the order share one.
  world91: '0a4606f6b2d934132adaf12ec9bb3eb28190c5b080c2946445c395a2c315bd10',
  world92: '4dbadc7abb0751cc241a86991bbc8c45df9379416fd5cd9b91ab3ef0524a9c79',   // AUDIT DROPS (2026-09-22): the trade bytes budgeted per sender (B3), the hub's quest cooldown at half the client's floor (C1), the quest budget spent only with a party to reach (C3)   // QUEST1 + TRADE1 + PEER-FS1 (2026-09-22, three drops from Mac's contributors in one deploy): the {t:'quest'} hub frame (a party member's quest shared, validQuestFrame, its own cooldown and QUEST_FRAME_MAX), the {t:'trade'} directed frame (a courier between two peers - validTradeData, tradeGate, the room's trade byte budget), and the pose's footstep byte for the peers' footsteps. An older relay closes on the unknown frames, so the clients offer Trade only to world91 or later (TRADE_RELAY_MIN).
  world93: 'ff1fac557b7368668303860530b55780673c8fb33c8627b1b3a9fc1c39b98562',   // PARTY-REST DROP (2026-09-22): the party pose grew rest.kind, voteAt, restEnemyAt, restCancelFor/At, restStartedAt; bk a full 32-bit key
  world94: '6f482bb81f3a49306cfe3b936e44f8b7bec72d0b09286d687b2b9e58cb9e16da',   // PARTY8 (2026-09-22, Mac: "increase the party limit to 8"): PARTY_MAX 4 -> 8 in wire.js - a party frame's member bound, so the hub and the client move together
  world95: '4c705e967ac2f039cb79517a3ad64e89404d2a15c0500f917e0b336f66e5a0a7',   // AUDIT PARTY8 + AUDIT PARTY-REST (2026-09-23): the party pose carries `readyAt` (a vote's shared-clock stamp every reader judges for freshness), the hub's quest fan pays in bytes (QUEST_ROOM_BYTES_PER_S), a lapse burst says the lead once, the lead passes to an online seat
  world96: 'cdbfcb6e2533c9e26a51157d1304564ff34ed5767f45586387faec285fea0bb4',   // ALLY-CAST (2026-09-23): the `cast` frame - a beneficial spell at a party mate, directed like a trade frame (validCastData, the relay's cast arm, its own meter and funnel); the receiver decides what lands
  world97: '1dca6ab13b44079c0ece4b6030f01b8712ee200b094f7d5b43c8459733dd581e',   // AUDIT ALLY-CAST (2026-09-23): the cast frame's honest bounds (level 30, byte components, a touch or a ranged single target alone, the icon), the funnel onto a destination PER SENDER (CAST_DEST_SENDERS_MAX slots), the dead length check gone
  world98: '4c21e4ee8da1c7d5ab746460fb1af03b2effad202715510695213429b2da06e0',   // SPELLFX1 (2026-09-23, the friendly-spells drop): the pose's `ce` and `ar` - a cast's element and the arrows loosed, so peers DRAW each other's missiles and shafts; visual only. The drop's own `aid` frame is NOT here: its friendly spells ride ALLY-CAST's `cast` frame (world97), whose sender's meter is a whole blast deep here (CAST_BURST_MAX, one frame per mate)
  world99: '96eddfd9b86bc9d0ea0f8de4e20b1388016d1b7ce20a1b22df30618a0e0979ca',   // HCC-PARK + RIDE (2026-09-23): the {t:'park'} frame (a parked wagon or waiting horse the cell room keeps per owner, validParkData, parkGate, the owner registry's internal paths, TTL and cap) and the pose's rd/rv riding fields. An older relay closes on the unknown frame, so the clients send park only to world99 or later (PARK_RELAY_MIN) AUDIT BRANCH (before any deploy - world99 never shipped, so its row is still this branch's to write): the owner is the verified ACCOUNT and the frame's CHARACTER (parkKeyOf), never the peer id; an account is never handed its own records; the welcome always lists; the registry ordered by when the owner said it; PARK_ACCOUNT_MAX; expiry said; the same word no news; a unit horse facing
  world100: '3d4faf9c32561ad7ee0f885f1241882e6339bef496237ef9e1981bfb6f5e2f8a',   // DISC7 (2026-09-23): the pose's half-speed bit `hs` (rideOf: mounted and moving slower than half speed, omitted at 0; poseChanged sends its edge at once) - the peers' riding loop swaps HorseClop / HorseClop2 on the rider's own flag
  world101: '87bd108fea8894900fed4f93cdf0625bdb6b7a6ad5d4d6ab1ee52c56f37ceaac',   // DISC12 (2026-09-23): the pose's hand-in-use bit `lh` and beast form `wb` (omitted at 0; poseChanged sends each edge at once; lerpPose carries both) - peers draw the used hand's weapon and the beast sprite
  world102: '86cb555c9161567c59d4de139ac5751faffa0cfaa980e3f5aeb9cd71ccd6e410',   // THE SIXTH MERGE (2026-09-23): the community arc's deploy, recorded over main's DISC12 (world101, above; the arc's never-deployed world101 row was its bytes before DISC12 took the name). JOURNAL1 (the same deploy): the `page` frame - a page of a player's journal held out to one player near them, directed like a card through the cast arm's per-sender funnel (`_senderFunnel`, now the three arms' one helper), on its own meter, never from a muted player; its words cleaned by the letter's line law, which moves into wire.js (`wordsLine`, `foldBlankLines`) so the letter and the page read one. MAIL1 (the same deploy): no frame - the letters are the account service's - but sanitizeChat's character loop is `visibleText` now, which the letter's law reads too (one law, not a copy); a chat line comes out of it unchanged. INSPECT1 (the same deploy): the `card` frame - a player's card asked for and answered, directed like a cast frame through the cast arm's own per-sender funnel (`_senderFunnel`, the two arms' one helper). AUDIT ATTACH (the same deploy): every per-socket meter leaves the socket's 2 KiB attachment for the Room instance (`_meterOf`/`_spend`). EMOTE1 (the same deploy): an action line (`me: true`) and the joiner kept between two pictographs in the one sanitizer. DICE1 (the same deploy): the `roll` frame - a roll asked of the relay and rolled from its own CSPRNG (net/dice.js joins the bundle through wire.js), said through the chat's one fan (`_sayLine`). CHAT-CHAN (2026-09-23, the community arc - kurkku's and Addison Knox's channels): the 62 region channels (`chat:region.<i>`) join the whitelist, a chat line may name the `party` channel - fanned by the hub to the party's members alone and refused whole naming anything else (CHAT_LINE_CHANNELS) - a party's lines are budgeted apart from the room's (PARTY_CHAT_ROOM_HZ_MAX - the room's is priced for a fan of everyone), and a cast's strikes are its own (`castDrops`; they were the chat gate's `cdrops`, which a place room's Local chat now shares the socket with). THE MERGE (2026-09-23): main's HCC-PARK + RIDE and DISC7 took world99 and world100 while this arc was in review, so its frames' RELAY_MIN gates move to world101 with it, and main's park frame and half-speed bit join this bundle; the park meter's strikes are its own (`parkDrops` - they were the party pose meter's `pdrops`, so a pass of either forgave the other's strikes and a miss of either counted toward the other's bound). Undeployed: a later slice of this arc restates this row until the branch merges
  world103: 'c61c70b2522b7e1ca7f8d6aa9ba6580a04f7f3d27d740183a3ef536fea581d4e',   // PCORPSE1 + RESURRECT1 + PCORPSE3 (2026-09-23, the contributor's drop, merged over DISC12): the pose's death flag `dd` (1 on a dying player's last pose, omitted alive; poseChanged sends it at once), the party pose's Resurrect call `rz` {to, at} and fallen body `dd` {k, x, y, z, at}, each omitted when absent; and validLook's `class` widened to a custom class's own name (the sprite fix). The drop numbered its three steps world100-102 off world99; none ran on the relay, so the merged graph is this one version past the deployed world101 - numbered world103 at the merge: main's community arc deployed world102 first
  world104: 'd0057aeb2b7a86e4ddcebf9155a97c113050aae958380c9900e7b0ca57f53cf7',   // TITLE-N (2026-09-24, Mac): the Dungeon Master's `narrate` frame (from the `dm` glyph alone, its own bucket) fanned as `{t:'dm'}`, and the badge vocabulary's four new titles and four new glyphs
  world105: 'ccf2e3515e8ad49701a9209ca4c9fc0170608ebca7ed4128e90153da15d4ad9f',   // AUDIT 68 (2026-09-24, the whole-tree sweep; world103 on its branch, renumbered past main's world103 and world104 at the merge): no frame changes shape; the relay's law moved - the hello's token asked before any write (a refused hello leaves no secret or look and closes no live holder), the hit bytes the destination's own meter (the pre-merge review: a sender's reopened C3), say and mute metered through _spend, the hub sweep reading a member's party record rather than trusting its pointer, an owner registry's word expiring with PARK_TTL_MS
  world106: 'c4250605e9bb5807dd2ce2639706d6a7084b75413bd5d02927ed4026e0aba449',   // DISC23-B (2026-09-24, Gryphoth on Discord: "a way to change our sprite in general instead of it defaulting depending on the class"): validLook carries `eo`, the Eye Of The Beholder on-foot set the player chose (0-15, EOTB_FOOT_SETS), omitted while their mod is off - a look without it keeps its bytes; the relay projects it through like `class`
  world107: '863a3200eac3d43c18cb0c3f63d6fc5953ca4bfae8c0cc1a605e34c94d668158',   // DUEL1 (2026-09-24; world105 on its branch, renumbered past main's world105, AUDIT 68, and world106, DISC23-B, at the merge; Mac: "When inspecting a player, they should be able to send an invite to duel"): the `duel` frame - one directed frame between two players (ask/yes/no, the start and the ring's centre, a strike's sheet and weapon, a spell, the defender's result, the end), routed like a card through a per-sender funnel of its own (`duin`, DUEL_HZ_MAX) on its own meter (`duelBucket`/`duelDrops`), the sender's verified account (`sub`) stamped beside its id; the card frame stamped the same way; the cast frame's spell law shared (castSpellOf) with the duel's
  world108: 'ac91d7ba5bdae045b1e7eaab4973e93c1c42034d3d4d79e677472da77de613e3',   // HT-WAIST-NET (2026-09-24; world106 on its branch, renumbered past main's DISC23-B (world106) and DUEL1 (world107)): the pose's waist-lantern bit `hl` (1 while the sender's lit light is a lantern hung at the waist, omitted otherwise; poseChanged sends its edge at once; lerpPose carries it) - a peer's Morrowind body hangs the lantern at its hip; ungated, as every pose field
  world109: 'f5fc90b081cb6a9c42d179cffa784f392d88609db53ffc00b3dc38d5a0e10822',   // PROFILE2 (2026-09-25, Mac: "make the profile icon visible somehow on the pause menu and allow changes"), in the same unshipped deploy: the `look` frame (the relay's look arm, LOOK_HZ_MAX, the room's hello budget). SKIN2 (2026-09-25, Mac: "Implement these as new skin options"): the look's `eo` bound widens from the mod's sixteen on-foot sets to every skin the build carries (FOOT_SKINS, 36 - Daggerfall's twenty classes after them), so a peer in a class skin is drawn in it, not clamped to the mod's last set. No frame changes shape; the relay's bytes moved, and the bytes are the law.
  world110: '2457e95dcb6a6828d555491cf2e1dcd003ed326385d0b4abacaba6cf352a3e43',   // EVENT1 (2026-09-25, Mac: "I wanna do a fun live event for the server"): the `stage` frame - a live event staged by a dev in the hub, kept in its storage, fanned as `event` and said on the hub welcome's `ev`
  world111: '81e4b53aa27af94cbb68fa0ad59d00b97dc5cca829eeebdb8351dded8e460f04',   // RENOWN1 (2026-09-24; world108 on its branch, renumbered past main's HT-WAIST-NET (world108), PROFILE2 and SKIN2 (world109) and EVENT1 (world110); Mac: "What if the leveling system was something seperate unique to online but compatible" ... "Plus having their level appear on the left side of character name"; named: "Lets officially call this Renown"): the identity token's `lv` claim (the Renown level of the character the client named at the mint, bounded by RENOWN_MAX in identityToken.js) stamped by `badged` beside the title and glyphs on every welcome row, join and roster; the `renown` frame in (a RENOWN ORDER the account service signed - ORDER_KINDS gains 'renown', each kind carrying its own field alone), taken only from a socket whose verified account it names, on its own meter (`rnbucket`/`rndrops`, RENOWN_HZ_MAX), fanned as `{t:'renown', id, lv}`; and `verifyOrder` asks for its KIND by name, so the mute arm can never be handed a renown order; and (AUDIT RENOWN1, the same unshipped deploy, the row rewritten in place) the arm takes only a RISE - an order that does not raise the socket's level is answered to its carrier alone - never in a channel or the hub, and on the room's own renown budget (`_roomRenown`, RENOWN_ROOM_HZ_MAX); and (AUDIT PSCALE1, the same unshipped deploy, the row rewritten in place again) the bundled wire.js - a foe record's `n` (how many fight it) and the reader's allowance, CELL_PUPPETS_MAX, eight and CELL_LOOSE_PUPPETS more - which the relay reads none of
  world112: '1b7a03480daa42b31075e73543bf584feb0dd3f6077f7f18d047643e422aa35e',   // PARTY-TRAVEL (2026-09-25; world110 on its branch, renumbered past EVENT1 and RENOWN1; Mac: "Implementing a prompt for online to travel to party leader and the option for party members to ready up and travel together"): validPartyPose carries the party's journey - the leader's proposal `tv` {x, y, o, at, go}, a member's answer `tr`/`td` (the round's `at`), the leader's feet in the open air `wx`/`wy`/`wz` - each omitted when absent or out of its law, never refusing the pose; PARTY_TRAVEL_RELAY_MIN beside the other gates. The relay projects every party pose through validPartyPose (parseClient), so the deployed relay strips the fields until this ships
};

const rd = (p) => readFileSync(new URL('../' + p, import.meta.url));

test('SLAM8: RELAY_VERSION names exactly one relay law - change the worker or the wire without bumping it and this fails (mutants: the relay edited under a version already shipped, which is SLAM5 verbatim; a row rewritten in place, which relabels bytes that are already deployed)', () => {
  // MERGE onto main (SRV-N / CHAT-G): wire.js reaches net/nameFilter.js now - the chat's third gate - and this pin caught the graph growing, as it is for
  // ACC1d: identityToken.js JOINED THE BUNDLE, which is the expensive line in the accounts arc - the relay verifies the name it is told, so the token module is the worker now, and this deploy drops every connected player. The order is the walk's own (index.js reaches the token module before relay.js re-exports the wire).
  // DICE1: net/dice.js JOINED THE BUNDLE - the relay rolls, and the dice's law is one home for both ends (wire.js imports it, so it walks after nameFilter.js); it imports nothing, so the graph stays flat.
  assert.deepEqual(RELAY_GRAPH, ['server/src/index.js', 'src/net/identityToken.js', 'src/net/wire.js', 'src/world/mat4.js', 'src/net/nameFilter.js', 'src/net/dice.js', 'server/src/relay.js'], 'the bundle the worker is: a new file here is a new law, and this row says so until it is written down');
  const h = createHash('sha256');
  for (const f of RELAY_GRAPH) h.update(rd(f));
  const hash = h.digest('hex');
  assert.ok(LAW[RELAY_VERSION], `RELAY_VERSION is '${RELAY_VERSION}' and this file has no law recorded for it - add the row`);
  assert.equal(hash, LAW[RELAY_VERSION],
    `THE RELAY'S LAW CHANGED UNDER '${RELAY_VERSION}'.\n`
    + `  Bump RELAY_VERSION in src/net/wire.js and add a row here in the SAME commit:\n`
    + `      ${'<new version>'}: '${hash}',\n`
    + `  /health is the only pre-flight check the event has, and it has to mean something.`);
  assert.equal(new Set(Object.values(LAW)).size, Object.keys(LAW).length, 'two versions cannot name the same bytes');
  assert.ok(/^world\d+$/.test(RELAY_VERSION), 'the shape law (nine test files hard-code this spelling)');
});
