// SLAM8 (2026-09-16, AUDIT SLAM): RELAY_VERSION CANNOT BE FORGOTTEN AGAIN.
//
// The line above `RELAY_VERSION` has said "Bump it with every relay-changing slice" since WORLD1, and SLAM5 changed
// the relay's hello path - the 130-player wall - and left it at `world67`. So `world67` named BOTH the relay that
// stops an event at 130 players and the one that does not, and `/health` is the only pre-flight check this port has
// on event day: the relay is deployed by hand and nothing in CI deploys it.
//
// A hand-maintained constant beside a comment asking politely will be forgotten again; that is what a comment is.
// So the version is bound to the LAW ITSELF here. `server/src/index.js` is the relay and `src/net/wire.js` is the
// law it runs (re-exported by server/src/relay.js), and a change to either is a change to what a deployed worker
// does. Change one of those files and this pin fails until a NEW version with its own hash is added below - and it
// has to be new, because the old version's recorded hash is the old bytes and stays that way.
//
// This deliberately fires for a comment-only edit too. `/health` answers "is the worker running the bundle I built?",
// and a bundle whose comments differ is a different bundle; a version that is only sometimes trustworthy is the
// thing that just cost us.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { graph } from './importGraph.mjs';   // ACC4: the walk moved to a helper so the ACCOUNT Worker's deploy filter is held to its own graph by the same law
import { RELAY_VERSION } from '../src/net/wire.js';   // LOCALDEV1: the worker entry exports handlers alone

/** SLAM13 (AUDIT SLAM, final lens): THE LAW IS THE WHOLE BUNDLE, not two files. wrangler bundles every relative import
 *  the worker reaches - server/src/relay.js, src/net/wire.js and, since ONCRASH1, src/world/mat4.js (wrapAngle, which
 *  poseChanged and validPose run on every pose) - and an edit to any of them is a different deployed worker under the
 *  same name. So from world73 on the hash walks the import graph from server/src/index.js: every relative `from '...'`,
 *  depth first, each file once, in the order the imports are written. A file joining the graph changes the hash too,
 *  which is the point - a new import is a new bundle. Rows before world73 were sha256(index.js + wire.js) and stay
 *  as recorded: they are facts about bytes already deployed, under the hash law of their day. */
export const RELAY_GRAPH = graph('server/src/index.js');

/** A version bump is `sed world<N>/world<N+1>` over nine test files - RUN IT WITH THIS FILE EXCLUDED, or it
 *  rewrites a row's KEY and relabels bytes already deployed (AUDIT SLAM / SLAM9 did exactly that, and this pin caught it).
 *  Every relay this repo has shipped a law for, and the sha256 of its law that IS it (see `graph` for what the law is).
 *  Append; never edit an existing row - an old row is a historical fact about bytes that have already been deployed. */
const LAW = {
  world69: '27da57b0787d8e18e93dea8358614d9af2e9c65133774755f39960e0ec8f89de',   // SLAM8: a keepalive is never tiered; turn counts what was relayed
  world70: '06cb8eb45de961f9756a71a3cfba19fd84e3a3e7a5217d5e3798e3b11cf4ebed',   // SLAM9: the who budget derived from the socket gates, spent before the scan
  world71: '37bfb4d0bc508775233bcbabbe4bbd7b1b4dc4fccd148e9a17c72fba0dd0e877',   // SLAM10: the far tier bucketed by the listener's id, stable under movement
  world72: 'de19e038912ea8e2e0568923bcf398b86ea2c80c173051129c0ece93bf6efa51',   // SLAM11: the memory push and the act fan borrow against their budgets and land whole
  world73: 'c12e8b6497602a53eead0f4b7abb41a0f6b65be217e174e9ed11c0244a9362ba',   // SLAM13: the keepalive floor, the sender's act share, the memory a listener at a time, the yaw seam, the version in the welcome (first row over the import graph)
  world74: 'f09ab5bdcc836a30fe540d4558a7d0a6c1c933130d9db4d61d5e86c896b55595',   // MERGE (SLAM13 + SRV-N/CHAT-G onto main): one `v` on every welcome, last; the chat's third gate reaches nameFilter.js
  world75: '4587d8fa5adbfc5df062feb6831c1d191ac0563b7312d4bff7d311aa00093cac',   // SLAM15: a stop is heard whole, under the keepalive's floor
  world76: '6f7d8d11d5c055d02fadc70935d9951b3c99732f8b59c9f9f4b72363b873781f',   // LOCALDEV1: the worker entry no longer exports the version string (workerd refused the bundle locally)
  world77: 'b8daad37e99a5f42c73910a000a44c3cca5d82c955cfed8bb064c10239e6aa60',   // ROSTER-G: the channel's welcome names its members with the true count; its joins and leaves are said
  world78: '059dda8d32a6e836c44d67cb2a81e969f7d9f15468e60262f57798b37c083ec6',   // SOC1: the world channel is the social hub - accounts (id + secret beside the peer's), friends, requests, presence and last-seen, four-seat parties, the party pose fan
  world79: '1ce0aa5a1a3080a2ce121be6e9bb832cd4f5a0312dd47bb18963aebfacd03a6a',
  world80: 'fc02a655c311d19778d026248c77d6a2f85bf25888865942e0520164db7bac8d',   // RESPAWN1: validSharedFoe takes `team`/`mobileTeam` as the MobileTeams NAME - the numeric law refused every foe record a dungeon published, so every memory restored empty and every kill came back alive   // AUDIT SOC: the hub's cooldowns, the paged sweep of idle accounts and lapsed parties, pending rows without presence, by-account acts for relations alone, the record cache, the newest tab speaking, the replaced socket's leave, the clock on the channel welcome, `peers` on the picture, the act projected at the door
  world81: '38878bdb5febe591e819830f195ef68f75a620930f4f35d08e18984887559328',   // AUDIT WATCH1 A1: wire.js gained CELL_WATCH_PUPPETS_MAX (the reader's allowance for a criminal's watch beside its foes) - no relay behaviour moved, the bytes did
  world82: '2c97add60a97d56f949ce6af4f8bba4947a862ad75183c578803c1c62864325a',
  world83: '30d4fd6bb7a536b22ff0c01c08db137026181e39d0222b3607db30a43014f21e',
  world84: '3cb3d6118b2798c89790a182d0d3eb69bd8f5bfb1cb87fcb997b0d50c2e433e2',
  world85: '87888cc6cd63b20a02967f9d839ca20781d453585baf41e482ad58f2cd0f5878',   // ACC1d: THE TOKEN SEAM. server/src/index.js imports src/net/identityToken.js, so the module joins the bundle and the hash changes for that alone; wire.js carries `tok` on the hello (shape only - parseClient is sync and pure and the crypto is the relay's); the room verifies, takes the name OUT of the token, spends each signature once per room (F8, Mac: a token is spent once), and marks the frames it vouches for with `v`. The key and the TTL ceiling are config beside each other in server/wrangler.toml.   // RELAY-H1: HEARTBEAT_MS 5000 -> 20000 and PING_MS beside it in wire.js (the standing player's liveness rides the runtime-answered ping, so the object sleeps between poses); KEEPALIVE_FAN_MS follows; the relay's own SLAM8 comment notes the pair moved   // ONLINE-CLASS1: validLook carries the character's class name (letters-only, optional), so a peer without a Morrowind body stands as its class-enemy sprite; an older peer's look without it still validates   // AUDIT ALL (the merge): the main merge moved a comment line in wire.js under world81 and the row was rewritten in place - SLAM5 verbatim; world81 restored to the audit's bytes, world82 names today's
  world86: '35e2f0bb2c14248083dd5514c52951015b85646d9d97ee207e4162684f4f1a2b',   // ACC1g: THE WALL MOVES TO THE DOOR (Mac: "You shouldnt be able to just type a name and enter anymore.... this is what the account system is for"). server/src/index.js `_named` REFUSES a hello with no token and one it has no usable key to check - the two arms ACC1d admitted, and admitting them was the hole ACC1a opened this arc to close: the name on a hello was the client's own and the relay only sanitised it. A GUEST IS NOT SHUT OUT - a guest session mints a token like anybody else, so the cost to a new player is one press and no email. AND `v` LEAVES THE WIRE IN THE SAME DEPLOY: every admitted socket is verified now, so the per-name verdict on the join, the roster (wire.js `rosterFor`) and the chat line said the same thing about everybody - a field carrying no information. It goes here rather than in a later slice because a wire change costs a drop and this deploy is already paying for one; ACC1d-MARK, its only reader, is retired with it.
  world87: 'b35a4d0ec7579023e6ba83ea894ceeba3bd65c26f22ea9a568e9de94eb7b4150',   // ACC3: TITLES AND GLYPHS RIDE THE SIGNATURE (Mac: "Player titles appear above a player name... name glyphs... appear on the right side"). src/net/identityToken.js gains TITLES, GLYPHS and the `t`/`g` claims, validated against those two closed lists before a token verifies; server/src/index.js `_named` reads both OUT of the verified claims, and wire.js `badged` puts them on the welcome's roster rows, the join, the channel roster and the `who` answer - absent, never null, when there is no badge. A CLIENT NEVER ASSERTS EITHER, which is ACC1g's law applied to a stronger claim than a name: a title over somebody's head reads as this project's own word about them. The deployed relay is still world84, so world86 and world87 ride ONE drop between them.
  world88: 'b96b8ca4a994bf052081da4499f6b34d864bf8ceb03fd8c27aa981c03510747d',   // ACC3b: `readBadge`, the INVERSE of world87's `badged`, in wire.js beside it - the client's half of one field, so a badge cannot be written one way and understood another. It is the relay's bundle only because the pair lives together; the relay never calls it (it reads a badge out of a verified token, never off the wire). wire.js imports the vocabulary from identityToken.js, which was already in the graph, so the bundle gained bytes and no file.
  world89: 'c6bbe33551e8d6be470e63cb75cfa75dd9012ebe56dad189b7681f4a8d573067',   // RED1: THE SERVER SPEAKING (Mac: "a red text system (kind of like warframe) where I can message chat as the server before we merge"). A `say` frame in, a `red` frame out to every socket in the room, and THE AUTHORITY IS THE DEV GLYPH THE TOKEN ALREADY CARRIED - `a.glyphs` was written by `_named` off the verified claims and can be written by nothing else on that socket, so the right to speak as the server is the same fact as the mark beside the name, granted and revoked the same way, with no second password, no admin route and no second key to leak. Its own bucket at RED_HZ_MAX, deliberately well under chat's, because a player's line reaches a room and this reaches every player in the game. The line carries no id and no name, because nobody is speaking it - and it is its OWN frame type rather than a flag on a chat line, so the client marks it from the type, which no player can send.
  world90: '7f109a2bc863ab36fe9517fad4c43300e4409839ad8036459024fd0db4e443aa',   // MOD1: THE MODERATOR'S MUTE (Mac: "a moderator glyph and moderator chat commands" - /mute, /unmute, the blue shield). identityToken.js gains the `mod` glyph, the `mu` claim (a mute rides the signature, so a reconnect cannot shed one) and a second token SHAPE - the mute ORDER, `{o:'mute', s, mu}`, which one key signs beside identities and which the claim shapes keep apart both ways. server/src/index.js keeps the verified account (`sub`) and the mute (`mu`) on the attachment, refuses a muted line and tells only its sender, and gains a `mute` arm that believes the ORDER'S SIGNATURE and never its carrier, the newest order per account winning (`_orders`) so a replay cannot undo an unmute and a token older than the order is held to it. wire.js carries `{t:'mute', order}` in, `{t:'muted', until}` out, `sub` on chat lines and a channel's roster and joins, MUTE_HZ_MAX. The key load moved into `_loadKey` so the hello and the order share one.
  world91: '0a4606f6b2d934132adaf12ec9bb3eb28190c5b080c2946445c395a2c315bd10',
  world92: '4dbadc7abb0751cc241a86991bbc8c45df9379416fd5cd9b91ab3ef0524a9c79',   // AUDIT DROPS (2026-09-22): the trade bytes budgeted per sender (B3), the hub's quest cooldown at half the client's floor (C1), the quest budget spent only with a party to reach (C3)   // QUEST1 + TRADE1 + PEER-FS1 (2026-09-22, three drops from Mac's contributors in one deploy): the {t:'quest'} hub frame (a party member's quest shared, validQuestFrame, its own cooldown and QUEST_FRAME_MAX), the {t:'trade'} directed frame (a courier between two peers - validTradeData, tradeGate, the room's trade byte budget), and the pose's footstep byte for the peers' footsteps. An older relay closes on the unknown frames, so the clients offer Trade only to world91 or later (TRADE_RELAY_MIN).
  world93: 'ff1fac557b7368668303860530b55780673c8fb33c8627b1b3a9fc1c39b98562',   // PARTY-REST DROP (2026-09-22): the party pose grew rest.kind, voteAt, restEnemyAt, restCancelFor/At, restStartedAt; bk a full 32-bit key
  world94: '6f482bb81f3a49306cfe3b936e44f8b7bec72d0b09286d687b2b9e58cb9e16da',   // PARTY8 (2026-09-22, Mac: "increase the party limit to 8"): PARTY_MAX 4 -> 8 in wire.js - a party frame's member bound, so the hub and the client move together
  world95: '4c705e967ac2f039cb79517a3ad64e89404d2a15c0500f917e0b336f66e5a0a7',   // AUDIT PARTY8 + AUDIT PARTY-REST (2026-09-23): the party pose carries `readyAt` (a vote's shared-clock stamp every reader judges for freshness), the hub's quest fan pays in bytes (QUEST_ROOM_BYTES_PER_S), a lapse burst says the lead once, the lead passes to an online seat
  world96: 'cdbfcb6e2533c9e26a51157d1304564ff34ed5767f45586387faec285fea0bb4',   // ALLY-CAST (2026-09-23): the `cast` frame - a beneficial spell at a party mate, directed like a trade frame (validCastData, the relay's cast arm, its own meter and funnel); the receiver decides what lands
  world97: '1dca6ab13b44079c0ece4b6030f01b8712ee200b094f7d5b43c8459733dd581e',   // AUDIT ALLY-CAST (2026-09-23): the cast frame's honest bounds (level 30, byte components, a touch or a ranged single target alone, the icon), the funnel onto a destination PER SENDER (CAST_DEST_SENDERS_MAX slots), the dead length check gone
  world98: '4c21e4ee8da1c7d5ab746460fb1af03b2effad202715510695213429b2da06e0',   // SPELLFX1 (2026-09-23, the friendly-spells drop): the pose's `ce` and `ar` - a cast's element and the arrows loosed, so peers DRAW each other's missiles and shafts; visual only. The drop's own `aid` frame is NOT here: its friendly spells ride ALLY-CAST's `cast` frame (world97), whose sender's meter is a whole blast deep here (CAST_BURST_MAX, one frame per mate)
  world99: '96eddfd9b86bc9d0ea0f8de4e20b1388016d1b7ce20a1b22df30618a0e0979ca',   // HCC-PARK + RIDE (2026-09-23): the {t:'park'} frame (a parked wagon or waiting horse the cell room keeps per owner, validParkData, parkGate, the owner registry's internal paths, TTL and cap) and the pose's rd/rv riding fields. An older relay closes on the unknown frame, so the clients send park only to world99 or later (PARK_RELAY_MIN) AUDIT BRANCH (before any deploy - world99 never shipped, so its row is still this branch's to write): the owner is the verified ACCOUNT and the frame's CHARACTER (parkKeyOf), never the peer id; an account is never handed its own records; the welcome always lists; the registry ordered by when the owner said it; PARK_ACCOUNT_MAX; expiry said; the same word no news; a unit horse facing
  world100: '3d4faf9c32561ad7ee0f885f1241882e6339bef496237ef9e1981bfb6f5e2f8a',   // DISC7 (2026-09-23): the pose's half-speed bit `hs` (rideOf: mounted and moving slower than half speed, omitted at 0; poseChanged sends its edge at once) - the peers' riding loop swaps HorseClop / HorseClop2 on the rider's own flag
  world101: '87bd108fea8894900fed4f93cdf0625bdb6b7a6ad5d4d6ab1ee52c56f37ceaac',   // DISC12 (2026-09-23): the pose's hand-in-use bit `lh` and beast form `wb` (omitted at 0; poseChanged sends each edge at once; lerpPose carries both) - peers draw the used hand's weapon and the beast sprite
  world102: '86cb555c9161567c59d4de139ac5751faffa0cfaa980e3f5aeb9cd71ccd6e410',   // THE SIXTH MERGE (2026-09-23): the community arc's deploy, recorded over main's DISC12 (world101, above; the arc's never-deployed world101 row was its bytes before DISC12 took the name). JOURNAL1 (the same deploy): the `page` frame - a page of a player's journal held out to one player near them, directed like a card through the cast arm's per-sender funnel (`_senderFunnel`, now the three arms' one helper), on its own meter, never from a muted player; its words cleaned by the letter's line law, which moves into wire.js (`wordsLine`, `foldBlankLines`) so the letter and the page read one. MAIL1 (the same deploy): no frame - the letters are the account service's - but sanitizeChat's character loop is `visibleText` now, which the letter's law reads too (one law, not a copy); a chat line comes out of it unchanged. INSPECT1 (the same deploy): the `card` frame - a player's card asked for and answered, directed like a cast frame through the cast arm's own per-sender funnel (`_senderFunnel`, the two arms' one helper). AUDIT ATTACH (the same deploy): every per-socket meter leaves the socket's 2 KiB attachment for the Room instance (`_meterOf`/`_spend`). EMOTE1 (the same deploy): an action line (`me: true`) and the joiner kept between two pictographs in the one sanitizer. DICE1 (the same deploy): the `roll` frame - a roll asked of the relay and rolled from its own CSPRNG (net/dice.js joins the bundle through wire.js), said through the chat's one fan (`_sayLine`). CHAT-CHAN (2026-09-23, the community arc - kurkku's and Addison Knox's channels): the 62 region channels (`chat:region.<i>`) join the whitelist, a chat line may name the `party` channel - fanned by the hub to the party's members alone and refused whole naming anything else (CHAT_LINE_CHANNELS) - a party's lines are budgeted apart from the room's (PARTY_CHAT_ROOM_HZ_MAX - the room's is priced for a fan of everyone), and a cast's strikes are its own (`castDrops`; they were the chat gate's `cdrops`, which a place room's Local chat now shares the socket with). THE MERGE (2026-09-23): main's HCC-PARK + RIDE and DISC7 took world99 and world100 while this arc was in review, so its frames' RELAY_MIN gates move to world101 with it, and main's park frame and half-speed bit join this bundle; the park meter's strikes are its own (`parkDrops` - they were the party pose meter's `pdrops`, so a pass of either forgave the other's strikes and a miss of either counted toward the other's bound). Undeployed: a later slice of this arc restates this row until the branch merges
  world103: 'c61c70b2522b7e1ca7f8d6aa9ba6580a04f7f3d27d740183a3ef536fea581d4e',   // PCORPSE1 + RESURRECT1 + PCORPSE3 (2026-09-23, the contributor's drop, merged over DISC12): the pose's death flag `dd` (1 on a dying player's last pose, omitted alive; poseChanged sends it at once), the party pose's Resurrect call `rz` {to, at} and fallen body `dd` {k, x, y, z, at}, each omitted when absent; and validLook's `class` widened to a custom class's own name (the sprite fix). The drop numbered its three steps world100-102 off world99; none ran on the relay, so the merged graph is this one version past the deployed world101 - numbered world103 at the merge: main's community arc deployed world102 first
  world104: 'd0057aeb2b7a86e4ddcebf9155a97c113050aae958380c9900e7b0ca57f53cf7',   // TITLE-N (2026-09-24, Mac): the Dungeon Master's `narrate` frame (from the `dm` glyph alone, its own bucket) fanned as `{t:'dm'}`, and the badge vocabulary's four new titles and four new glyphs
  world105: 'ccf2e3515e8ad49701a9209ca4c9fc0170608ebca7ed4128e90153da15d4ad9f',   // AUDIT 68 (2026-09-24, the whole-tree sweep; world103 on its branch, renumbered past main's world103 and world104 at the merge): no frame changes shape; the relay's law moved - the hello's token asked before any write (a refused hello leaves no secret or look and closes no live holder), the hit bytes the destination's own meter (the pre-merge review: a sender's reopened C3), say and mute metered through _spend, the hub sweep reading a member's party record rather than trusting its pointer, an owner registry's word expiring with PARK_TTL_MS
  world106: 'c4250605e9bb5807dd2ce2639706d6a7084b75413bd5d02927ed4026e0aba449',   // DISC23-B (2026-09-24, Gryphoth on Discord: "a way to change our sprite in general instead of it defaulting depending on the class"): validLook carries `eo`, the Eye Of The Beholder on-foot set the player chose (0-15, EOTB_FOOT_SETS), omitted while their mod is off - a look without it keeps its bytes; the relay projects it through like `class`
  world107: '863a3200eac3d43c18cb0c3f63d6fc5953ca4bfae8c0cc1a605e34c94d668158',   // DUEL1 (2026-09-24; world105 on its branch, renumbered past main's world105, AUDIT 68, and world106, DISC23-B, at the merge; Mac: "When inspecting a player, they should be able to send an invite to duel"): the `duel` frame - one directed frame between two players (ask/yes/no, the start and the ring's centre, a strike's sheet and weapon, a spell, the defender's result, the end), routed like a card through a per-sender funnel of its own (`duin`, DUEL_HZ_MAX) on its own meter (`duelBucket`/`duelDrops`), the sender's verified account (`sub`) stamped beside its id; the card frame stamped the same way; the cast frame's spell law shared (castSpellOf) with the duel's
  world108: 'ac91d7ba5bdae045b1e7eaab4973e93c1c42034d3d4d79e677472da77de613e3',   // HT-WAIST-NET (2026-09-24; world106 on its branch, renumbered past main's DISC23-B (world106) and DUEL1 (world107)): the pose's waist-lantern bit `hl` (1 while the sender's lit light is a lantern hung at the waist, omitted otherwise; poseChanged sends its edge at once; lerpPose carries it) - a peer's Morrowind body hangs the lantern at its hip; ungated, as every pose field
  world109: 'f5fc90b081cb6a9c42d179cffa784f392d88609db53ffc00b3dc38d5a0e10822',   // PROFILE2 (2026-09-25, Mac: "make the profile icon visible somehow on the pause menu and allow changes"), in the same unshipped deploy: the `look` frame (the relay's look arm, LOOK_HZ_MAX, the room's hello budget). SKIN2 (2026-09-25, Mac: "Implement these as new skin options"): the look's `eo` bound widens from the mod's sixteen on-foot sets to every skin the build carries (FOOT_SKINS, 36 - Daggerfall's twenty classes after them), so a peer in a class skin is drawn in it, not clamped to the mod's last set. No frame changes shape; the relay's bytes moved, and the bytes are the law.
  world110: '2457e95dcb6a6828d555491cf2e1dcd003ed326385d0b4abacaba6cf352a3e43',   // EVENT1 (2026-09-25, Mac: "I wanna do a fun live event for the server"): the `stage` frame - a live event staged by a dev in the hub, kept in its storage, fanned as `event` and said on the hub welcome's `ev`
  world111: '81e4b53aa27af94cbb68fa0ad59d00b97dc5cca829eeebdb8351dded8e460f04',   // RENOWN1 (2026-09-24; world108 on its branch, renumbered past main's HT-WAIST-NET (world108), PROFILE2 and SKIN2 (world109) and EVENT1 (world110); Mac: "What if the leveling system was something seperate unique to online but compatible" ... "Plus having their level appear on the left side of character name"; named: "Lets officially call this Renown"): the identity token's `lv` claim (the Renown level of the character the client named at the mint, bounded by RENOWN_MAX in identityToken.js) stamped by `badged` beside the title and glyphs on every welcome row, join and roster; the `renown` frame in (a RENOWN ORDER the account service signed - ORDER_KINDS gains 'renown', each kind carrying its own field alone), taken only from a socket whose verified account it names, on its own meter (`rnbucket`/`rndrops`, RENOWN_HZ_MAX), fanned as `{t:'renown', id, lv}`; and `verifyOrder` asks for its KIND by name, so the mute arm can never be handed a renown order; and (AUDIT RENOWN1, the same unshipped deploy, the row rewritten in place) the arm takes only a RISE - an order that does not raise the socket's level is answered to its carrier alone - never in a channel or the hub, and on the room's own renown budget (`_roomRenown`, RENOWN_ROOM_HZ_MAX); and (AUDIT PSCALE1, the same unshipped deploy, the row rewritten in place again) the bundled wire.js - a foe record's `n` (how many fight it) and the reader's allowance, CELL_PUPPETS_MAX, eight and CELL_LOOSE_PUPPETS more - which the relay reads none of
  world112: '1b7a03480daa42b31075e73543bf584feb0dd3f6077f7f18d047643e422aa35e',   // PARTY-TRAVEL (2026-09-25; world110 on its branch, renumbered past EVENT1 and RENOWN1; Mac: "Implementing a prompt for online to travel to party leader and the option for party members to ready up and travel together"): validPartyPose carries the party's journey - the leader's proposal `tv` {x, y, o, at, go}, a member's answer `tr`/`td` (the round's `at`), the leader's feet in the open air `wx`/`wy`/`wz` - each omitted when absent or out of its law, never refusing the pose; PARTY_TRAVEL_RELAY_MIN beside the other gates. The relay projects every party pose through validPartyPose (parseClient), so the deployed relay strips the fields until this ships
  world113: 'eecfa6f6c84dc3043d6a45ac865eaedecd430da622ffd929e3249ae9ded3ff5d',   // WB3 + AUDIT WB (2026-09-25; world110 and world111 on their branch, neither deployed, renumbered past main's EVENT1 (world110), RENOWN1 (world111) and PARTY-TRAVEL (world112)) - WB3 (Mac: "a gate of oblivion which takes place in a large boss arena with an oversized enemy with telegraphed attacks", and Option B - the relay's object is the authority over the boss): the `gate` frame (`in` a level claim, `hit` a blow; validGateIn/validGateOut), the `gate:<day>` room the Worker opens and the hello admits only inside its day's window, the fight the object runs on its alarm and checkpoints (net/gateBrain.js), the kill said once with a receipt per earning account (net/gateReceipt.js, GATE_SIGNING_KEY) and the hub's world line (GATE_INTERNAL_FELL); gateLaw, gateBrain and gateReceipt join the bundle; and AUDIT WB (Mac: "A proper audit on everything"), the relay's half: a socket silent past HELLO_WAIT_MS gives its seat back to a full room, one seat an account in a gate's court, a full fight frees a seat left idle (gateBrain freeSeat), a newcomer to a bled fight comes with an empty bucket, an `in` said again writes nothing, the kill kept before it is said and the hub told until it answers (GATE_TELL_RETRY_MS), each account's receipt kept by the hub for its life and handed to its next hello (gateReceiptKey), a day's gate times made once (gateLaw).
  world114: 'c0f385ffb38eeb803600e2954a8271a60b07d39b52461abd10e3055fb005cca3',   // PEERLIGHT1 + PEERLIGHT2 (never deployed before this row: the torch's `lt` and the Light spell's `lc` ship together) (2026-09-26, the player: "when another player lights a torch you should be able to see them lighting your way as well"): the pose's `lt` (a lit light's radius x2, +1 guttering, omitted while nothing burns), so the others' torches light my world; and `lc` 1 while the Light spell burns ("can the candle spell of mages also make light for others?"), so the others hang its candle - net/wire.js validPose, poseChanged. And PEERFX1 in the same deploy (AUDIT MERGE-PLUS E5: this row named the lights alone): `hk` with `hp`/`hb`/`hq` - a weapon blow of the sender's that landed, its point, its blood and its share - and `hu` with `uq`, the times the sender was struck, each bounded by validPose and dropped by an older relay's.
  world115: '2521c978439525b742936f08f47b31e5c7470b3b041b34c9c3f341162c8d0fa8',   // GUILD1c (2026-09-25, Mac: "Do guild1c" - the guild tag beside names, and guild chat; world113 on its branch, never deployed - its branch row named bytes 7ed3e9a0... - renumbered past main's WB3 + AUDIT WB (world113) and the Enhanced Plus patch (world114) at the merge, whose bundle it carries whole): the identity token's guild (`gi`, `gt`, `gm` - the guild's id, its tag and the character's member row, all three or none, read against the law's own shapes: net/guildLaw.js joins the bundle), `gt` stamped by `badged` beside the level; the `guild` frame in (a GUILD order - the guild the carrier's character is in now, or none - taken only from the account it names, the newest winning, the tag fanned in a place alone on the room's own budget) and the `guildout` frame (a member removed or a guild disbanded, believed on its signature, held against older tokens and orders in `_guildOuts`), `{t:'guild', id, gt?}` out; a chat line may name the `guild` channel, fanned by the hub to the sockets wearing the sender's guild alone (GUILD_CHAT_ROOM_HZ_MAX); and (AUDIT MERGE-PLUS, the same unshipped deploy, the row rewritten in place) the held removals outlive the room's sleep - `_guildOuts` is kept in the room's storage (`guildouts`, each dropped once no token or order it could refuse is still alive) and read back before a guild claim is believed, so a member removed before an idle room was evicted is not let back in by the token they still hold
  world116: '6ce9024745567dd5c5a348a5d79fc77594ecc2edae604f80dedcf607498ca14c',   // world114 on its branch, never deployed - renumbered past main's Enhanced Plus patch (world114) and GUILD1c (world115) at the merge. WBX5 (2026-09-26, Mac: "The boss phases need to be more defined and more detailed mechanics", and Swololo's "boss damage is way too low ... should be hp % based maybe + base damage"): net/gateBrain.js - each phase named (PHASE_NAMES) and turned by a sequence (PHASE_TURN: the Crushing Leap into the court's heart, then the phase's signature - the Flame Nova, the Spokes of Dagon twice), three new attacks (leap, meteor, spokes; the meteor and Hellfire leave burning ground, POOLS), every share raised with a `base` beside it (WBX4); no new wire shape (validGateOut already takes an attack id to 15); and AUDIT WBX in the same, never-deployed world114 (2026-09-26, Mac: "Do a comprehensive audit on everything so far"): an absent fighter's share retired and restored (retireShare/restoreShare), a seat kept by a blow worth its claim or SEAT_KEEP_MS stood, standing measured on the fight's own clock (liveMs), the fall settled where he stands (settleAt), the cleave's 7, the wind-up's health, a blow arming the beat and none after the Wrath's hour; the wire's `in` carries the brain's law (`bv`, GATE_BRAIN_MIN) and a `spent` word joins the gate kinds (relaySupportsGateSpent), the receipt carries its fight's level (`l`), the hub hands a receipt to one socket an account and not to a fighter in the court, forgets a spent one and sweeps expired ones; and AUDIT WBX2 in the same (2026-09-26, Mac: "Audit this before we merge"): the hub keeps a spent word in its copy's place and holds a court fighter's copy from their hellos (GATE_HERE_HOLD_MS), the brain keeps his fraction when every share is out (standsAt) and flies a leap by the screens' own law (leapAt)
  world117: 'd99fb7124b444aae70727a23faa7e5039ca1055d6c01ed1b910ed8a7953bd2d3',   // SHADOW-FANG (2026-09-26; world114 on its branch, never deployed - renumbered past the Enhanced Plus patch's PEERLIGHT1/2 + PEERFX1 (world114) and GUILD1c (world115) at its first merge, where its row was world116 and named bytes 569b7bab...; that row dropped, never deployed, when main's Oblivion Gate WBX took world116 first; Mac: "SirMcMobdon gets a brand new title/glyph"): identityToken.js's TITLES and GLYPHS gain `shadowfang` - no frame changes shape; a token carrying it is refused by an older relay, so this deploy carries it before the account service (acct14 - acct12 on its branch) mints one - and that deploy now waits for it (AUDIT B1)
  world118: 'fc4e95b11a22fac5d621c8c14afab241430fab59c38af7ee75b8944fb50686bc',   // OWN1 (2026-09-26; world114 on its branch, never deployed - its branch row named bytes 998d2a80... - renumbered past main's PEERLIGHT1/2 + PEERFX1 (world114), GUILD1c (world115), WBX (world116) and SHADOW-FANG (world117) at the merge, whose bundle it carries whole; Mac: "Dungeons and buildings" - a shared quest's foes in a dungeon and a building, and a building's foes at all): the `own` frame - in a world room any hello'd socket streams its OWN foes beside the host's stream (OWN_PREFIX, the foes frame's cap and bucket, the room's own ingress and fan budgets, at most CELL_FRAME_RECORDS_MAX records; a cell's own frame is junk), and a `hit` marked `own` in a world room goes to the socket its `to` names (an unroutable one junk, as a cell's); OWN_RELAY_MIN beside the other gates; INVIS-NET (the same unshipped deploy): the pose's concealment bits (`cv`); the pre-merge audit (the same unshipped deploy, O3/O4): a fanned frame that re-serialises longer than its charged length, or deeper than stringify takes, is junk (`fanOut`)
  world119: '2f6da5b5c2b47bf72469c7d2a25a2664390333c68b0c92185b80a3c4bbeb94b4',   // AUDIT SET (2026-09-27, the Sigil Sets audit; world117 on its branch, never deployed - its branch row named bytes 23327acc... - renumbered past main's SHADOW-FANG (world117) and OWN1 + INVIS-NET (world118) at the merge, whose bundle it carries whole): the dungeon's foe record carries `v` - the joiner whose blow killed the foe, on a death's record alone (wire.js validFoeRecord) - so a joiner's sets hear their own kill underground. The relay forwards a foes frame unread (parseClient: `read by no relay`), so an older relay passes `v` too and no deploy is owed for it; the bundle's bytes moved, so the version does
  world120: '57bde0d4703172bb01e5c0763c99bc69046c8bb997d5272af1e27860a1f79600',   // PARTY-BUFFS + REST-OPT + the batch's AUDIT, one deploy (2026-09-27; world119, world120 and world121 on their branch, never deployed - their branch rows named bytes 835a65f6..., 173e19f1... and d723c801... - renumbered past main's AUDIT SET (world119), which landed first): validPartyPose carries `fx` (a member's live spell effects, at most PARTY_FX_MAX) and `rs` (1 while they rest) - PARTY-BUFFS - and `nr` (1 while a member rests alone) - REST-OPT; the wire exports TRADE_REV_MAX and names REST_OPT_RELAY_MIN / relaySupportsRestOpt (a client honours the rest-alone switch only through a hub at this version or later) - the batch's AUDIT. A relay before it strips the three pose fields: nothing closes
  world121: 'c79d15c3268b7e86d24af71f4927226a83560b32d038ccc03ad70f40f84be81c',   // ONE-SEAT (2026-09-27, Mac: "the player can only have one character only at a time. Like they shouldnt be able to open multiple tabs and join as different characters"; world119, then world120, on its branch, never deployed - its branch rows named bytes 2d4bb8d3... and c64de558... - renumbered past main's AUDIT SET (world119) and PARTY-BUFFS + REST-OPT + the batch's AUDIT (world120) at the merges, whose bundles it carries whole): a hub hello may CLAIM the account's one seat (`cl`) - the account's other tabs in the hub are closed CLOSE_REPLACED, SEAT_ELSEWHERE said first - and a hub hello that does not claim is refused while another tab of the account holds the hub; AUDIT ONESEAT (the same unshipped deploy): a seat that moves is not a drain (R1 - no party swept), and a socket the object closed holds no seat (R4)
  world122: '5058554d9eb26b5d3f72e6e63727ed1dd9183219eebd0074277af4be32aeb1fc',   // OVERWORLD NAMES (2026-09-28, NOT YET DEPLOYED): the client's door reads a trav frame's Renown and guild tag too (validTravellerFrame: readRenown, readGuildTag) - the relay already stamped them (badged). AUDIT DEEP2 (2026-09-28, NOT YET DEPLOYED, so rewritten in place again): a clear with no mark behind it is METERED as a mark is (it was parsed and dropped free - a flood at no cost); a clear over the room's budget is OWED and said on the budget's next pass (the room's next traveller frame), a new mark or a leave making it moot; a welcome never lists a socket already closing. AUDIT DEEP (2026-09-28): a clear only where a mark is, on its own budget and past the cooldown; the welcome's marks say their age. TV3 (2026-09-28, Mac: "being able to see other players traveling also"; his call: "Region-wide from the start"; bible/06-Systems/Travel-View.md TV3): the `trav` frame - a TRAVELLER MARK {px, py, fx, fy, h, m, tv} (validTravellerMark: seven keys and no eighth) told in a REGION's channel alone (isRegionRoom), on its own cooldown (travHubGate, TRAV_HUB_MIN_MS), kept on the attachment (`tm`, stamped) or taken out by a null, fanned to the room at TRAV_ROOM_HZ_MAX (a clear over its own budget owed, never lost - AUDIT TV C2, AUDIT DEEP2 C2) with the token's name and account, and the fresh ones (TRAV_STALE_MS) handed a joiner in its welcome (`tr`, TRAV_WELCOME_MAX); the wire names TRAVELLER_RELAY_MIN / relaySupportsTravellers (an older relay CLOSES the socket on the frame, so a client sends none through one)
  world123: 'f86ce4d41b5377e2e817a93cea03bde7c11638fc9e7ecb64c6b85324b90f7060',   // THE GATE IN THE ROCK + THE RAIDS, one deploy (2026-09-28; world122 to world126 on their branch, never deployed - their branch rows named bytes 46f809f7..., 3fbc7c26..., 6ffc0a20..., a84d418b..., 75372051... - renumbered past main's TV3 + AUDIT DEEP + OVERWORLD NAMES (world122) at the merge): RAID3 (Mac on World Events - Raiding Parties online: "1. Server" - the `raid` frame, a player's word on a town's raid to its cell, whose ledger the relay keeps and whose receipts it signs); AUDIT RAID + AUDIT SETS (a raid is its whole tuple; an earner's receipt kept by the hub); RAID-ROLL + AUDIT ONLINE 2 (every raid word read against its day's own roll; the towns table the hub keeps by its pinned hash); GATE-COLLAPSE (the field: "Never left"; Mac: "Count down to collapse" - the gate law's sealed-hours countdown and seal line, words the relay bundles); DISCORD-GATES (Mac: "Discord live gates?" - net/gateHerald.js joins the bundle: the hub posts each gate's omen, the opt-in role pinged, and its kill to a Discord webhook, a Worker secret, and hears where each gate stands, `gate` `site`, GATE_SITE_RELAY_MIN).
  world124: '688d28caa14639887f2fc4841673b64d08437fe8c36658ad46fc64b5f233f6e0',   // TV8 (2026-09-28, Mac: "Leader drives"; NOT YET DEPLOYED; world123 on its branch, renumbered past THE MERGE's world123 at the merge - one deploy with it): the party pose carries the leader's Overworld walk `tw` and a member's stop `ts` (net/wire.js validPartyPose; systems/partyWalk.js) - an older relay strips both, and the client offers the walk only through one that carries it (PARTY_WALK_RELAY_MIN)
  world125: 'cbc33f03103e8fefb41e614a46f05e84ef2e2c2d1f9bbc5ba2683891caaa6780',   // VOICE1 (2026-09-28, Mac: "develop prox chat"; world124 on its branch, renumbered past main's TV8 at the merge): the `rtc` frame - a voice link's offer, answer, ICE and goodbye, directed to one player in a place room, never from a muted player; the voice itself is browser to browser   // REVERTED (2026-09-28, Mac: "Do not merge voice chat. Please revert voice chat but keep other changes"): the relay is world124's bytes again, and RELAY_VERSION names world124
  world127: '5a0fc9bf0dd1b922ad58a116c83b53bf6786bd107db9b2dcf01ab3faa1b4b993',   // OW6L (2026-09-29, the product owner: "Everything needs that persistence between players in the overworld."; NOT YET DEPLOYED): the `ow` frame - a player's word on its CELL's overworld ledger, the bands and raiders it spent (`sp`) and the spawned dungeons it first saw or cleared (`dg`, shared classic minutes) - which the cell keeps in its storage (net/overworldLaw.js joins the bundle: min-merged, bounded, pruned on load and on write), fans to everyone in it and hands whole on the cell's welcome (`ow`); world127, never world125 (VOICE1's, merged on main and reverted - a relay may have carried it) nor world126 (DISCORD-GATES' on its branch), so no client takes a relay that closes its socket on `ow` for one that keeps the ledger (OW_RELAY_MIN)
  world128: '72771b06e7aa68f66e9e6ded44afc0d0e6abf5d916f4660cb5d08ba4ff389a39',   // WB8 (2026-09-28, Mac: "Make the oblivion gate boss not be able to be pacified ... give him unique and different modifers on every 2 hour spawn"; NOT YET DEPLOYED; world126 on its branch, never deployed - its branch row named bytes de0674a2... - and one relay past main's OW6L (world127) at the merge, with it): the Warden's marks - net/gateMods.js joins the bundle; the `st` frame's `md`, the `fed` kind, GATE_BRAIN_V and GATE_BRAIN_MIN 3; the day's draw (gateLaw.js gateModsOf) and the fight's profile (gateBrain.js fightProfile); the hub's omen post names them. Undeployed: a later slice of this arc restates this row until the branch merges
  world129: '2bd00ec1b4de557ab4e929f29d7dc1ffcc775768540abe1ac7c7c793227b6df7',   // PENITENT (2026-09-29, Mac: "This new custom title/glyph is for the user Diggleborf"; NOT YET DEPLOYED): identityToken.js's TITLES and GLYPHS gain `penitent` - no frame changes shape; a token carrying it is refused by an older relay, so this deploy carries it before the account service (acct21) mints one - and that deploy waits for it (SHADOW-FANG's AUDIT B1)
  world130: '331e2ee12ef353efc93f3f9e3852c971e55ebcea2bdacb6257416ec39de2b031',   // REALM-DOOR (2026-09-29, the field: Gryphoth, 'it said my client was outdated ... my character was no longer online'; NOT YET DEPLOYED; world129 on its branch, renumbered past main's PENITENT at the merge): the door asks the realm - a hello whose token the account service signed as naming no realm character of its account (identityToken.js `rc` 0, acct22) is refused in every room before anything is written, with REALM_DOOR_WORD (net/wire.js), which a build from before the realm prints as it stands and never retries; a token with no `rc` (a service before acct22 - the two Workers deploy on their own) is admitted as it was
  world131: '6632343e503000a370d9ad41ed7200dbaa7008a4a79be516ac2960a7fc368b21',   // MERGE 2 (2026-09-29, Mac: "Merge and markdown notes", the professions branch onto main; NOT YET DEPLOYED): the branch's BOUNTY1 + AUDIT 28 (world125 on its branch, never deployed - its branch row named bytes 5198d471...; world125 is VOICE1's on main) one relay past REALM-DOOR - the party pose's `bq` and `lv`, a bounty row's `k`, `a` and `t`; a relay before it strips the bounty fields and nothing closes
  world132: '0fff43b15bbdd2029a59bde1d167dbd9fc98e70ee9a6cce1d00565fe682053e7',   // STRIKE-SHARED (2026-09-29, Mac: "Do #1"; NOT YET DEPLOYED): the hit's strike spell (`sp`, `lv`) and a dead foe record's trapper (`j`, `q`) - read by the clients alone; the relay fans both unread
  world133: '451295ab26369e5f957d4cfbf607b5bbc129708708f86e6bff7685f2b29a3a17',   // SOFTCAP1 (2026-09-29, NOT YET DEPLOYED): the party pose's `cl` - a member's character level, for mentor mode (systems/mentorMode.js); validPartyPose projects it, never gated - an older relay strips it and nobody mentors
  world134: '65ddd6185143ec1d7b68c7bfc28ac8a916995afc5a982008a106f439b8987dba',   // PARTY-MAP (2026-09-30, NOT YET DEPLOYED): SHARED CARTOGRAPHY - the `amap` frame (a member's revealed dungeon automap rows under the buff), parsed by parseClient, metered by amapShareGate and AMAP_ROOM_HZ_MAX, fanned to the party alone
  world135: 'e97c6f1f8ccc64ed40f74c09523eec13dc3c79525a889b8244c9764d820a69f7',   // WB9 (2026-09-30, Mac: "I want to add 2 more arena's of the same size that the boss leaps to between each phase" and "a detailed wipe mechanic on the final phase"; NOT YET DEPLOYED; world134 on its branch - main's PARTY-MAP took world134 first): the gate's brain law 4 - the three courts, the bound across the fire and the walkways it lays (`ct`, `xa` on the state), Dagon's Reckoning and its crystals (`cx`, `su`, `rk` on the state; `cx`, `cxh`, `cxb`, `stun` from the room; `xhit` in - net/gateBrain.js applyCrystalHit, judged and fanned at once); every share and base raised (WB9e) and the ground's bite (WB9d); the aura a token signs for (WB9g: identityToken.js AURAS, `au`, stamped by badged); AUDIT WB9 (before the merge): no blow from outside his court (applyHit, applyCrystalHit), no crystal struck in the Reckoning's last RECKON_CLOSE_MS nor after it, a kill mid-Reckoning spends its crystals
  world136: '02e28acd44e1b2d8f17ce6f1be67c0ab27abd39e1ef7907f032595dc22907886',   // GATE-UX (2026-10-01, Mac: "Develop a detailed damage chart after the boss kill, showing and ranking everyone's damage"): the kill's damage chart - the brain counts each fighter's blows landed, the heaviest, the crystals' share and the falls, and makes the chart at the kill (net/gateBrain.js damageChart); the court's `fell` word and the state's fall carry it as `dm` (wire.js GATE_CHART_MAX, validGateOut's projection), the hub's word of the kill never does
  world137: '468c17ecf4c528704b811b455a2f084b5c7253c11399066143e523ec8808fff3',   // KEPT-KILL (2026-10-01, NOT YET DEPLOYED; world136 on its branch - main's GATE-UX took world136 first): the party pose's `qk` - the kills of quest foes a member held on a partner's word, so every copy of the quest counts a kill no copy saw (validPartyPose, KEPT_KILL_POSE_MAX)
  world138: '3c853a8baedf165665cbdcfe12d49255e563a4b117dfc905c1a8fb7416976fa1',   // HERALD (2026-10-01, Mac: "Herald doesnt exist ingame yet" - "you'll need to develop the herald title/glyph"; NOT YET DEPLOYED): `herald` joins TITLES and GLYPHS (identityToken.js) - the Patreon tier between Disciple and Hierophant, its title and its trumpet - so a relay from before it refuses a token carrying it (claimsValid); nothing else moved
  world139: '78bc46cf9552f5c2682f696c28b2c17089f4bd497f74037ddc66f91bf93e3130',   // LOOT7 (2026-10-01, Mac: "Do you wanna turn this into an arc and do all of the above?"; NOT YET DEPLOYED - world138 on its branch, main's HERALD took world138 first): a street foe record's `cp` - a champion's trait index, projected by validFoeRecord so every puppet of an owner's champion stands the same one; a relay before it strips the field and the puppet stands as an ordinary foe. The merge's bundle: HERALD's token titles and glyphs with it
  world140: '30e0446e5c8688beb96856d5eabd3f74470ec55321f3839ba4b3c1fa3791876c',   // WB11 (2026-10-01, Mac: "1. All three 2. Your choice 3. Your choice 4. Trial rotation"; NOT YET DEPLOYED - world138 on its branch, main's HERALD and LOOT7 took world138 and world139 first): the Legion-Lord's host - the `ahit` blow on one of it (validGateIn), the words `ad`, `amv`, `aatk`, `ah` and `adie` (GATE_OUT_KINDS), `lg` in the state, `a` in a chart row; the brain steps the host (gateBrain.js stepHost, applyHostHit) and its law is 5 (GATE_BRAIN_V/MIN), so a client of law 4 is refused at `in` and told to reload; the relay judges `ahit` on the body and fans its fall; the marks cycle is rebuilt for nine trials (gateLaw.js marksCycle, a bye seat, 144 gates)   // AUDIT WB11 (2026-10-01, never deployed - re-hashed in place): a blow on his host or a crystal keeps the beat (R1); one token a blow, the blow's `q` read by all three arms (W3) and GATE_HZ_MAX 16; the rise spots swept, never unchecked (B1); the Ward-Bearers sized by the fallen too (B4); the Wrath's word before the crumbling (B2); the rising says its own health (B3)   // GATE-HEAL (2026-10-01, Mac: "Can we add a line on the damage round up showing the amount healed?", never deployed - re-hashed in place): the client's `heal` (each receiver's word of what its mates' spells healed in it, by caster - allies only), the relay's bucket per receiver (applyHeal), the chart row's `hl`
  world141: 'd5c8fb1bc23a00fff44b9896dfff9664dd3d368cc96c26d36871d0e68f46c22c',   // CLIMB5 (2026-10-01, NOT YET DEPLOYED - world138 on its branch, main's HERALD, LOOT7 and WB11 took world138-140 first): the pose fields `cl` (1 hanging, 2 on a face, 3 a move in flight) and `cw` (the way the body faces on it), omitted off the wall - the others turn a climber to the wall, pose them off the ground and hear the climb; CLIMB6: with cl 3 the move's `ck` kind, `cy` lip and `cd` time, so the others' bodies climb it
  world142: '316e8828866d21a430f57ca5b6210d71dfe0e1f788a0bc589f129a903fd19c3e',   // FRIENDS-SYNC (2026-10-01, FIELD BUGS part five - "My friend list is different between devices"; Mac: "Build it"; NOT YET DEPLOYED): the hub's account is the token's verified subject - the signed-in player on every device - never the browser profile's id; a profile's record, proved by its secret, merged into the player's once (a union) and retired (_helloAccount, _mergeLegacy); AUDIT part five, before any deploy (the row rewritten, never shipped): a profile record planted at a player's id retired (_retireForged), the union's cut forgotten both ways, the hello's `ps` and the word to a build without it. The hello gains `ps`.
  world143: '961868021baaa075594f20095d27c215811f2e954cec4070bc3a8a240bf891b4',   // ELITE FOES (2026-10-01, Mac: "randomly spawn elite enemies in dungeons and in the overworld"; NOT YET DEPLOYED): validFoeRecord's `z` (0 or 1), an elite foe - its owner's puppet stands as the same elite. A relay before it strips the bit.
  world144: 'fc5c47113fb6e558590cc9628add81ea51217c10dce679a2de60c5327431ab0a',   // SEAT1b (2026-09-30, Mac: "Finish the seats"; NOT YET DEPLOYED; world136 on this branch until the merge of main's GATE-UX and KEPT-KILL, which took world136 and world137 first - its hash the branch's then - world138 on this branch until the merge of main's HERALD, LOOT7, WB11 and CLIMB5, which took world138-world141 first): THE WATCH - src/net/watchReceipt.js joins the bundle (the `k1` receipt and the tick's rhythm, watchDue); a verified account standing in a cell room, having moved in the last five minutes, is sent a `watch` frame every two minutes, its receipt naming the account, the map pixel its pose stands in and a nonce, signed with the gate's key
  world145: 'fe0fced3e54245647a13f5c90130519f665bd1c7f9b21437f69ec91510a3cece',   // SEAT1c (2026-09-30, Mac: "Finish the seats"; NOT YET DEPLOYED; world137 on this branch until that merge - its hash the branch's then - world139 on this branch until the merge of main's HERALD, LOOT7, WB11 and CLIMB5, which took world138-world141 first): THE SEATS' TITLES AND GLYPHS, reaching the relay before the service mints them - identityToken.js TITLES gains warden, protector, crowned, keeper and champion with a bounded `ts` claim beside them ([the seat key, the Season], refused beside any other title), GLYPHS tower, crownDF, crownWR and crownSN; `_named` and the hello's attachment carry `ts`, `badged` stamps it beside a seat title and `readBadge` reads it back
  world146: '9bc80fa0d9eb28adb1f312d72e1bfa2ffeaf4db5371ef028378053e2dd564a92',   // PVP-REF (2026-10-01, Mac: "Finish the seats"; "Continue"; NOT YET DEPLOYED; world138 on this branch until that merge - world140 on this branch until the merge of main's HERALD, LOOT7, WB11 and CLIMB5, which took world138-world141 first): A SIEGE'S REFEREED ROOM - net/siegeRef.js joins the bundle (a leaf: DFU's damage tables copied and pinned equal, never imported); `siege:<seat>:<week>` rooms admitting the developers alone until SEAT2a, the relay holding every fighter's vitality and judging every blow, cast and step
  world147: 'cf2998d3029a2aab273b2a85f53cc0960e95551292954c2d2896a23f92a39498',   // SEAT2a (2026-10-01, Mac: "Finish the seats"; "Or we could go ahead and do sieges"; "Continue"; NOT YET DEPLOYED; re-recorded at part three, which drew identityToken.js's field check out as siegeFieldValid, and at part four, whose wire.js grew the client's projection validSiegeOut - the same relay law, never shipped under either earlier hash - world141 on this branch until the merge of main's HERALD, LOOT7, WB11 and CLIMB5, which took world138-world141 first): A SIEGE'S BATTLE - net/siegeReceipt.js joins the bundle (the relay's fourth signature, `s1`); a siege's room admits by the service's pass (identityToken.js's `siege` order on the hello's `sp`), keeps the sides, raises the fallen at their camp on the tier's wave, beats the battle each second (net/siegeRef.js battleStep) and fans its `f` frame, and hands each fighter its own receipt at the end
  world148: 'c12104312c35023af1706340d308001dbd431dccd1d4b52e691d0e9bb400a925',   // CROWN1 part two (2026-10-01, Mac: "Finish the seats"; "Continue"; "Hurry up"; NOT YET DEPLOYED - world142 on this branch until the merge of main's HERALD, LOOT7, WB11 and CLIMB5, which took world138-world141 first): THE ROYAL TOURNEY - a crown's `royal:` room by its pass (`sn` 'royal'), bouts in DUEL1's ring refereed by PVP-REF, the room's ladder, the winner's `t1` receipt (net/siegeRef.js, net/siegeReceipt.js, identityToken.js's royal pass, wire.js's royal frames). No file joined the graph.
  world149: '906b13a4a78fa2fbc9cfc8ac61f9d855a109b4ea0da9a4b69c4d01e206f066ff',   // SEASON1 part two, the banner ribbon (2026-10-01, Mac: "Finish the seats"; "Continue"; "Hurry up"; NOT YET DEPLOYED - world143 on this branch until the merge of main's HERALD, LOOT7, WB11 and CLIMB5, which took world138-world141 first; re-hashed in place at that merge, over the merged bundle): A SEASON'S BANNER RIBBON - the token's `rb` (identityToken.js claimsValid, mintToken) carried onto the socket and `badged` onto every row that names its wearer; TOKEN_RE's body 640 (it was 512); net/heraldryLaw.js joins the bundle; re-recorded at AUDIT-SEATS (still undeployed) - a guild taken off a socket takes its ribbon too
  world150: 'efa11e42e9f7e844a44a2d59696563dfcf4aae1fba05fa314350b0d884d3cbf7',   // SEAT2b part two (b) (2026-10-01, Mac: "Finish the seats"; "Let's pick up 482"; NOT YET DEPLOYED - world148 on this branch until the merge of main's FRIENDS-SYNC (#517), which took world142 first; the arc's seven (world142-world148) moved up one; world149 until the merge of main's ELITE FOES (#523), which took world143 first - the seven moved up one again, re-hashed in place at that merge over the merged bundle; re-hashed in place at that merge, main's FRIENDS-SYNC joining the graph (undeployed); and again at AUDIT SEATS-2 (the relay's own fighters' reach and provocation, the Throne's clamp); and again at AUDIT SEATS-3 (a fighter held to the field's ground - its step, its blow, a bout's marks' ground and its level ring (siegeRef.js siegeStepLevel, siegeGroundOf, royalLevel); a fighter back from a drop put at its camp at the door; a returning contender counted; an `in` answered once each SIEGE_IN_MS (wire.js); a held receipt collected past a taken place)): THE WORKS IN BATTLE - a siege's pass carries its works (identityToken.js `sx`, net/siegeRef.js worksOf - identityToken.js imports the leaf, already in the bundle, so the graph is the same); the room's Gatehouse at the Throne and the camp's Rams before it, a blow on either (`gh`, `rm` - wire.js validSiegeIn, siegeRef.js refereeWorkBlow), a crewed Ram's stroke, the breach that unbars the Throne, the next Ram at the attackers' wave, the defenders' wave the Walls' quicker; the field's frame's `g`, `r` and `w` (validSiegeOut); RE-HASHED IN PLACE, still undeployed, by SEAT2b part two (c): the relay's own fighters - the Barracks' guards and a revolt's Captain and rebels (siegeRef.js siegeGuards, revoltRising, npcStep; a blow or a cast on one, `n0`-`n12` - validSiegeIn; the field's `np` and `v`, `hp` and `fell` naming one - validSiegeOut; a revolt's pass, identityToken.js `sn` 'revolt'; index.js _siegeNpcBlow)
  world151: '4b99ff120252da795f1e9bd39767fae81bac6c2178200239b17aec1c65200bb4',   // WB12 (2026-10-01, Mac: "getting feedback that our oblivion gates arent lore friendly to the current daggerfall timeline" - "Dagon's Breach"; NOT YET DEPLOYED - world141 on its branch, main's CLIMB5 and CLIMB6, FRIENDS-SYNC, ELITE FOES and the Seats arc took world141-world150 first): DAGON'S BREACH - the breach's words in the omen's lines and the herald's posts (WB12a); the Flame Nova's ring to 16 m (WB13a), the omen's, the marks' and the herald's words (WB13b) the state's opening's end (WB13e) and his rhythm (WB13f), the faithful's rite (WB12d) and its audit (AUDIT WB12d) - each re-hashed in place; at the merge, gateLaw.js's omenLine, openLine and sealLine retired (TIME1: the client says them in local time)
  world152: '33f7426cf1825923f1835f6680831c8d6f774911bde90819e2f1838ece427b6c',   // GLYPH-WEAR (2026-10-02, Mac: "can we make it where players can also equip/unequip their glyphs"): the token's `gx` kept on the attachment, and `badged` leaves those glyphs out of every row; the rights still read the whole `glyphs`
  world153: 'd13c9374af68e0ef11e594a46719d66b5a0e6dc456c153b4ae1ae3fe0d610d15',   // REVENANT-WIRE (2026-10-02, Mac: "Definitely finish this with love"; NOT YET DEPLOYED - world144, then world152, on its branch until main took them first): the foe record's `nm` (a revenant's name), and REVENANT-FATE's `yd`, `ex` and `sp` (a beaten revenant kneeling, being executed, spared into its portal)
  world154: '95879e04edc7e68065eab5a1b56c73867af69551ff0beef3f167b9d519d99afe',   // BROKER-CAGE (2026-10-02; world153 on its branch, renumbered past main's REVENANT-WIRE (world153) at the merge; re-hashed in place for AUDIT BROKER-CAGE (undeployed): the hub keeps a cleared word told after an early kill's collapse, a tell in flight arms the retry and lets go at it, relaySupportsCage; Mac: "she should be present at the site in a jailed gate, and the gate opens after all the enemies are cleared"; NOT YET DEPLOYED): the rite word's `c` (every one of the faithful seen to fall) kept by the circle's cell and told the hub; the hub says the Sigil Broker's cage open (`rite` `cl`) once to everyone online and at every hello until midnight (net/gateRite.js riteRosterFell, cageStands)
  world155: '0cb41f9f3e40b5b12ac44029b3e4018548eb91585ccba0b50b9d909700630c41',   // ARENA4 (2026-10-02, NOT YET DEPLOYED - world142 on its branch, renumbered past main's world154 at the merge, which re-hashed it): the arena's rooms - `arena:hall` (the queue by the token's season rating `ar`, the offers, the bouts to watch) and `arena:b<id>` (one bout under the bout law, PVP-REF's referee, the relay-run ladder fighters, the stands); the `arena` frame both ways (net/arenaLaw.js), a bout's receipt (net/arenaReceipt.js `a1`), the arena's titles and the laurel on the token; ARENA4b (2026-10-03, still undeployed, re-hashed in place): the hour's exhibition's room `arena:x<hour>` (net/arenaExhibition.js), the token's signed character level `cl` carried onto a ladder fighter's socket for its vitality, a spell's cast counted once by its sequence, each fighter's banner billed as their word claims it (cosmetic); AUDIT PRE-MERGE 1003 (2026-10-03, still undeployed, re-hashed in place): a seat a socket's once and the bout's words to its sand and its stands alone (S1), a ladder fighter's signed level held to the tier's cap (S2), a rated bout's level the token's, never the queue word's (S3), a finished bout's own fighter answered with it and its receipt (S5), the bout's room minted at the go, never the offer's id (S7), every fighter healed at the law's 'heal', so the `hp` riding with it says them whole (O1)
};

const rd = (p) => readFileSync(new URL('../' + p, import.meta.url));

test('SLAM8: RELAY_VERSION names exactly one relay law - change the worker or the wire without bumping it and this fails (mutants: the relay edited under a version already shipped, which is SLAM5 verbatim; a row rewritten in place, which relabels bytes that are already deployed)', () => {
  // MERGE onto main (SRV-N / CHAT-G): wire.js reaches net/nameFilter.js now - the chat's third gate - and this pin caught the graph growing, as it is for
  // ACC1d: identityToken.js JOINED THE BUNDLE, which is the expensive line in the accounts arc - the relay verifies the name it is told, so the token module is the worker now, and this deploy drops every connected player. The order is the walk's own (index.js reaches the token module before relay.js re-exports the wire).
  // DICE1: net/dice.js JOINED THE BUNDLE - the relay rolls, and the dice's law is one home for both ends (wire.js imports it, so it walks after nameFilter.js); it imports nothing, so the graph stays flat.
  // WB3: net/gateLaw.js, net/gateBrain.js and net/gateReceipt.js JOINED THE BUNDLE - the relay runs a gate's boss: the day's window, the fight and the kill's receipt. gateLaw imports wire.js and gateReceipt identityToken.js, both walked already; gateBrain imports nothing, so the graph stays flat.
  // GUILD1c: net/guildLaw.js JOINED THE BUNDLE - the token carries a guild and `badged` stamps its tag, both read against the law's own shapes (wire.js imports it after the dice, and identityToken.js too); it imports nothing, so the graph stays flat.
  // RAID3: net/raidLaw.js and net/raidReceipt.js JOINED THE BUNDLE - the relay keeps a town raid's ledger and signs its receipts: wire.js imports the law after the guild's (it imports nothing, so the graph stays flat), and the receipt walks after the gate's (it imports identityToken.js and raidLaw.js, both here already).
  // DISCORD-GATES: net/gateHerald.js JOINED THE BUNDLE - the hub posts each gate's omen and kill to a Discord channel and folds the players' word of where it stands: it walks after the raid's receipt (it imports gateLaw.js and wire.js, both here already).
  // WB8b: net/gateMods.js JOINED THE BUNDLE - the Warden's marks: wire.js validates a state's `md` against it (after the raid's law), and gateLaw.js and gateBrain.js read its tables; it imports nothing, so the graph stays flat.
  // PVP-REF: net/siegeRef.js JOINED THE BUNDLE - a siege's referee: wire.js imports its blow kinds after the raid's law and the relay its referee; it imports nothing, so the graph stays flat.
  // SEASON1 part two: net/heraldryLaw.js JOINED THE BUNDLE - a token's banner ribbon is two of its sixteen colours, checked by identityToken.js claimsValid and wire.js badged (wire.js imports it after the dice); it imports nothing, so the graph stays flat.
  // OW6L: net/overworldLaw.js JOINED THE BUNDLE - a cell keeps its overworld ledger (the bands and raiders spent, its spawned dungeons' clocks): it walks after the herald (it imports wire.js, gateLaw.js and raidLaw.js, all three here already) - and NOTHING from systems/ or world/: the bands', the raiders' and the spawns' numbers are pinned equal in it (test/ow6_ledger.test.js), since their modules reach the map files and every byte here is a deploy.
  // ARENA4: net/arenaLaw.js, net/arenaBrain.js, systems/arenaBout.js, net/duelSession.js and net/arenaReceipt.js JOINED THE BUNDLE - the relay runs the arena's rooms: wire.js validates the arena's words against arenaLaw.js (after the raid's law - it imports nothing); the bout room runs the bout law every screen runs (arenaBrain.js reaches systems/arenaBout.js, which reaches net/duelSession.js for the duel's ring and count, which reaches wire.js, walked already) and signs a bout's receipt (arenaReceipt.js imports identityToken.js and arenaLaw.js, both here).
  // ARENA4b: net/arenaExhibition.js and systems/wind.js JOINED THE BUNDLE - the relay runs the hour's exhibition in its room `arena:x<hour>`: the schedule and the hour's pair moved out of systems/arenaLadder.js (which hands them on - its mobile and text tables are no worker's) into arenaExhibition.js, walked from index.js after the herald (it imports arenaLaw.js, here already, and systems/wind.js for the port's one seeded die, mulberry32 - wind.js imports nothing).
  assert.deepEqual(RELAY_GRAPH, ['server/src/index.js', 'src/net/identityToken.js', 'src/net/wire.js', 'src/world/mat4.js', 'src/net/nameFilter.js', 'src/net/dice.js', 'src/net/heraldryLaw.js', 'src/net/guildLaw.js', 'src/net/raidLaw.js', 'src/net/siegeRef.js', 'src/net/arenaLaw.js', 'src/net/gateMods.js', 'src/net/gateLaw.js', 'src/net/gateRite.js', 'src/net/siegeReceipt.js', 'src/net/gateBrain.js', 'src/net/gateReceipt.js', 'src/net/raidReceipt.js', 'src/net/watchReceipt.js', 'src/net/gateHerald.js', 'src/net/arenaExhibition.js', 'src/systems/wind.js', 'src/net/arenaBrain.js', 'src/systems/arenaBout.js', 'src/net/duelSession.js', 'src/net/arenaReceipt.js', 'src/net/overworldLaw.js', 'server/src/relay.js'], 'the bundle the worker is: a new file here is a new law, and this row says so until it is written down');
  const h = createHash('sha256');
  for (const f of RELAY_GRAPH) h.update(rd(f));
  const hash = h.digest('hex');
  assert.ok(LAW[RELAY_VERSION], `RELAY_VERSION is '${RELAY_VERSION}' and this file has no law recorded for it - add the row`);
  assert.equal(hash, LAW[RELAY_VERSION],
    `THE RELAY'S LAW CHANGED UNDER '${RELAY_VERSION}'.\n`
    + `  Bump RELAY_VERSION in src/net/wire.js and add a row here in the SAME commit:\n`
    + `      ${'<new version>'}: '${hash}',\n`
    + `  /health is the only pre-flight check the event has, and it has to mean something.`);
  assert.equal(new Set(Object.values(LAW)).size, Object.keys(LAW).length, 'two versions cannot name the same bytes');
  assert.ok(/^world\d+$/.test(RELAY_VERSION), 'the shape law (nine test files hard-code this spelling)');
});
