// DAGGER_SPEC v1 (Characters C6, fork step 1) - GENERATED by
// tools/paperdoll-spec.mjs from the classic paperdoll body
// (BODY00I0/I1.IMG, 69x145 - both genders share the template rows).
// Pose-invariant landmarks adopted: crotch row 72 -> pelvisY 0.961,
// armpit row 33 -> chest.y1 1.478, leg stance hipX 0.1392, classic
// leg length 0.961 split by the engine thigh/calf ratio. NOT
// adopted in v1 (documented): torso WIDTHS (arms overlap the posed
// trunk - await the pose-matched stance, step 2) and SHOULDER/NECK
// verticals (classic shoulders sit ~1.75 with an 11px head, colliding
// with the rig's literal head prisms at 1.62 - the spec-v2 driver:
// head enters the seam). Do not hand-edit; regenerate.
import { VOXLIGHT_SPEC } from './rewrite/bodySpec.js';

export const DAGGER_SPEC = {
 'pelvis': {
  'y0': 0.821,
  'y1': 0.981,
  'rx0': 0.195,
  'rz0': 0.1176,
  'rx1': 0.23,
  'rz1': 0.1323
 },
 'chest': {
  'y0': 0.901,
  'y1': 1.478,
  'rx0': 0.2125,
  'rz0': 0.125,
  'rx1': 0.25,
  'rz1': 0.1903
 },
 'upperChest': {
  'y1': 1.52,
  'rx1': 0.33,
  'rz1': 0.174
 },
 'neck': {
  'y0': 1.45,
  'z0': 0.011,
  'y1': 1.63,
  'z1': 0.014,
  'rx0': 0.115,
  'rz0': 0.098,
  'rx1': 0.072,
  'rz1': 0.072
 },
 'deltoid': {
  'x0': 0.17,
  'y0': 1.545,
  'x1': 0.24,
  'y1': 1.45,
  'rU0': 0.0738,
  'rV0': 0.09,
  'rU1': 0.0801,
  'rV1': 0.0945
 },
 'hipX': 0.1392,
 'pelvisY': 0.961,
 'leg': {
  'thigh': 0.5298,
  'calf': 0.4312
 }
};
export { VOXLIGHT_SPEC };
