// PAPERDOLL_POSE (C6k) - GENERATED by tools/fit-pose.mjs:
// coordinate descent over the contrapposto stance + hanging-arm
// targets, maximizing front-silhouette IoU vs BODY00I0. Fit IoU:
// 0.7212. Regenerate, never hand-edit.
export const PAPERDOLL_POSE = {
 'weightSide': -1,
 'weightIn': 0.8,
 'freeOut': 0.11,
 'freeFwd': 0,
 'hipShift': 0.07,
 'footYaw': 0,
 'armL': {
  'x': 0.28,
  'y': 0.99,
  'curl': 0.1,
  'poleX': 0.3
 },
 'armR': {
  'x': 0.16,
  'y': 1.02,
  'curl': 0.25,
  'poleX': 0.3
 }
};
export const FIT_IOU = 0.7212;
