// PAPERDOLL_POSE (C6k) - GENERATED by tools/fit-pose.mjs:
// coordinate descent over the contrapposto stance + hanging-arm
// targets, maximizing front-silhouette IoU vs BODY00I0. Fit IoU:
// 0.6649. Regenerate, never hand-edit.
export const PAPERDOLL_POSE = {
 'weightSide': -1,
 'weightIn': 0.65,
 'freeOut': 0.14,
 'freeFwd': 0,
 'hipShift': 0.07,
 'armX': 0.18,
 'armY': 1.2,
 'armZ': 0,
 'armCurl': 0.3
};
export const FIT_IOU = 0.6649;
