export default [
  {
    files: ['src/**/*.js'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module' },
    rules: {
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-constant-binary-expression': 'error',
      'no-dupe-keys': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-self-compare': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
      'use-isnan': ['error', { enforceForSwitchCase: true, enforceForIndexOf: true }],
      'valid-typeof': ['error', { requireStringLiterals: true }],
      'no-compare-neg-zero': 'error',
      'array-callback-return': ['error', { checkForEach: false }],
      'no-unmodified-loop-condition': 'error',
      'no-self-assign': ['error', { props: true }],
      'no-fallthrough': 'error',
      'no-sparse-arrays': 'error',
      'no-useless-backreference': 'error',
      'no-empty-character-class': 'error',
      'no-loss-of-precision': 'error',
      'getter-return': 'error',
      'no-setter-return': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-obj-calls': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-unused-private-class-members': 'error',
      'no-dupe-class-members': 'error',
      'no-const-assign': 'error',
      'no-class-assign': 'error',
      'no-async-promise-executor': 'error',
      'no-promise-executor-return': 'error',
      'no-template-curly-in-string': 'error',
      'no-unreachable-loop': 'error',
      'no-useless-assignment': 'error',
    },
  },
];
