export default [
  {
    files: ['src/**/*.js'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module' },
    rules: {
      'no-redeclare': ['error', { builtinGlobals: false }],
      'no-shadow-restricted-names': 'error',
      'no-dupe-args': 'error',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-undef-init': 'off',
      'no-inner-declarations': ['error', 'both'],
      'no-case-declarations': 'error',
      'default-case-last': 'error',
      'no-eq-null': 'off',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-implicit-coercion': 'off',
      'no-return-assign': ['error', 'always'],
      'no-sequences': 'error',
      'no-unsafe-finally': 'error',
      'consistent-return': 'off',
      'no-throw-literal': 'error',
      'radix': 'error',
      'no-extend-native': 'error',
      'no-global-assign': 'error',
      'no-with': 'error',
      'no-void': 'off',
      'no-nested-ternary': 'off',
      'no-bitwise': 'off',
    },
  },
];
