// Argonian body detail: a layer of raised scale bumps tiled over the
// whole body plus wider belly scutes down the front. Generated by
// sampling the actual body faces, so each scale sits exactly on the
// surface and inherits that face's animation group (body/armL/armR/
// legL/legR) - it moves with the rig and never floats. Built in FINAL
// (compressed) body space; shown for Argonian.

// Catlike fur tones - a warm tabby coat + a lighter cream underbelly
// (cats are counter-shaded: dark back/top, pale belly/chest/inner legs).
export const KHAJIIT_FUR   = [[34, 26, 18], [58, 44, 30], [88, 66, 44], [120, 92, 62], [154, 122, 86], [188, 156, 116]];
export const KHAJIIT_BELLY = [[70, 60, 46], [104, 90, 70], [138, 122, 96], [170, 154, 124], [200, 186, 156], [226, 214, 188]];

function shadeScales(faces, ramp) {
  const Lx = 0.5, Ly = 0.55, Lz = 0.67, Ln = Math.hypot(Lx, Ly, Lz);
  const snap = (t) => ramp[Math.max(0, Math.min(ramp.length - 1, Math.round(t * (ramp.length - 1))))];
  for (const f of faces) { const it = Math.max(0.08, (f.n[0]*Lx + f.n[1]*Ly + f.n[2]*Lz) / Ln * 0.9 + 0.18); f.c = snap(Math.min(1, it)); }
  return faces;
}

// small raised pyramid scale at point P with outward normal n, tagged g.
function scaleBump(out, P, n, size, lift, g) {
  // tangent basis
  let up = Math.abs(n[1]) > 0.9 ? [1, 0, 0] : [0, 1, 0];
  let t1 = [n[1]*up[2]-n[2]*up[1], n[2]*up[0]-n[0]*up[2], n[0]*up[1]-n[1]*up[0]];
  let l1 = Math.hypot(...t1) || 1; t1 = [t1[0]/l1, t1[1]/l1, t1[2]/l1];
  let t2 = [n[1]*t1[2]-n[2]*t1[1], n[2]*t1[0]-n[0]*t1[2], n[0]*t1[1]-n[1]*t1[0]];
  const base = [P[0]+n[0]*lift, P[1]+n[1]*lift, P[2]+n[2]*lift];
  const apex = [base[0]+n[0]*size*0.9, base[1]+n[1]*size*0.9, base[2]+n[2]*size*0.9];
  // diamond base (points up-tail): top vertex biased along +t2
  const s = size;
  const A = [base[0]+t2[0]*s, base[1]+t2[1]*s, base[2]+t2[2]*s];
  const B = [base[0]+t1[0]*s, base[1]+t1[1]*s, base[2]+t1[2]*s];
  const C = [base[0]-t2[0]*s, base[1]-t2[1]*s, base[2]-t2[2]*s];
  const D = [base[0]-t1[0]*s, base[1]-t1[1]*s, base[2]-t1[2]*s];
  const tri = (a, b, c) => {
    const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2], vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2];
    let nx=uy*vz-uz*vy, ny=uz*vx-ux*vz, nz=ux*vy-uy*vx; const L=Math.hypot(nx,ny,nz)||1;
    out.push({ p:[...a,...b,...c,...c], n:[nx/L,ny/L,nz/L], g });
  };
  tri(A, B, apex); tri(B, C, apex); tri(C, D, apex); tri(D, A, apex);
}

export function buildBodyScales(bodyFaces, skin) {
  const faces = [];
  let idx = 0;
  for (const f of bodyFaces) {
    const n = f.n;
    if (f.g === 'head') continue;                // head is scaled separately
    if (n[2] < -0.35) continue;                 // skip the pure back
    let cx=0, cy=0, cz=0; for (let i=0;i<4;i++){ cx+=f.p[i*3]; cy+=f.p[i*3+1]; cz+=f.p[i*3+2]; }
    cx/=4; cy/=4; cz/=4;
    if (cy > 1.62) continue;                     // head handled separately
    if ((idx++ % 2) !== 0) continue;             // subsample -> tidy density
    // scale size by region: torso a touch bigger than limbs
    const big = (f.g === 'body' && cy < 1.35 && cy > 0.85);
    scaleBump(faces, [cx, cy, cz], n, big ? 0.024 : 0.017, 0.006, f.g);
  }
  // Belly scutes: wider banded plates down the FRONT centre (chest ->
  // abdomen), overlapping like a lizard's underside.
  for (let y = 1.52; y > 0.86; y -= 0.058) {
    // find the frontmost torso point near the centreline at this height
    let best = null, bz = -1e9;
    for (const f of bodyFaces) {
      if (f.g !== 'body') continue;
      let mx=0,my=0,mz=0; for (let i=0;i<4;i++){ mx+=f.p[i*3]; my+=f.p[i*3+1]; mz+=f.p[i*3+2]; }
      mx/=4; my/=4; mz/=4;
      if (Math.abs(my - y) > 0.03 || Math.abs(mx) > 0.05 || f.n[2] < 0.4) continue;
      if (mz > bz) { bz = mz; best = [mx, my, mz]; }
    }
    if (!best) continue;
    const w = 0.052, z = best[2] + 0.006, py = best[1];
    // a shield: wide top, point at the bottom, raised centre
    const tl=[-w, py+0.026, z], tr=[w, py+0.026, z];
    const ml=[-w*0.9, py, z+0.010], mr=[w*0.9, py, z+0.010];
    const bot=[0, py-0.034, z];
    const q = (a,b,c,d) => { const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=d[0]-a[0],vy=d[1]-a[1],vz=d[2]-a[2]; let nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx; const L=Math.hypot(nx,ny,nz)||1; faces.push({p:[...a,...b,...c,...d],n:[nx/L,ny/L,nz/L],g:'body'}); };
    q(tl, tr, mr, ml); q(ml, mr, bot, bot);
  }
  return shadeScales(faces, skin);
}

// short fur tuft at P: a thin blade angled outward then swept DOWN (fur
// lies down the body) and a touch back. One tri, tagged g.
function furTuft(out, P, n, len, g) {
  let up = Math.abs(n[1]) > 0.9 ? [1, 0, 0] : [0, 1, 0];
  let t1 = [n[1]*up[2]-n[2]*up[1], n[2]*up[0]-n[0]*up[2], n[0]*up[1]-n[1]*up[0]];
  const l1 = Math.hypot(...t1) || 1; t1 = [t1[0]/l1, t1[1]/l1, t1[2]/l1];
  const base = [P[0]+n[0]*0.003, P[1]+n[1]*0.003, P[2]+n[2]*0.003];
  const w = len * 0.22;
  const a = [base[0]+t1[0]*w, base[1]+t1[1]*w, base[2]+t1[2]*w];
  const b = [base[0]-t1[0]*w, base[1]-t1[1]*w, base[2]-t1[2]*w];
  // tip: out along normal, then down + slightly back
  const tip = [base[0]+n[0]*len*0.5, base[1]+n[1]*len*0.5 - len*0.85, base[2]+n[2]*len*0.5 - len*0.15];
  const ux=a[0]-base[0],uy=a[1]-base[1],uz=a[2]-base[2], vx=tip[0]-base[0],vy=tip[1]-base[1],vz=tip[2]-base[2];
  let nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx; const L=Math.hypot(nx,ny,nz)||1;
  out.push({ p:[...a,...b,...tip,...tip], n:[nx/L,ny/L,nz/L], g });
}

// Khajiit fur pass: dense short tufts over the whole body, tagged per
// group so they move with the rig. No scutes.
export function buildBodyFur(bodyFaces, coat = KHAJIIT_FUR, belly = KHAJIIT_BELLY) {
  const coatF = [], bellyF = [];
  for (const f of bodyFaces) {
    if (f.g === 'head') continue;              // head furred separately
    const n = f.n;
    if (n[2] < -0.45) continue;                // skip deep back
    let cx=0, cy=0, cz=0; for (let i=0;i<4;i++){ cx+=f.p[i*3]; cy+=f.p[i*3+1]; cz+=f.p[i*3+2]; }
    cx/=4; cy/=4; cz/=4;
    if (cy > 1.62) continue;                    // neck/head boundary
    const len = (f.g === 'body') ? 0.030 : 0.024;
    // counter-shading: underside (normal points down) + front-lower chest
    // + inner limbs read as the pale belly tone; everything else the coat.
    const ventral = n[1] < -0.05 || (n[2] > 0.30 && cy < 1.30) || (Math.abs(cx) < 0.10 && cy < 1.15);
    furTuft(ventral ? bellyF : coatF, [cx, cy, cz], n, len, f.g);
  }
  shadeScales(coatF, coat); shadeScales(bellyF, belly);
  return coatF.concat(bellyF);
}
