// VC2 (2026-09-07): THE RENDER TARGET. The first offscreen machinery in
// the tree - the world has always drawn straight to the default
// framebuffer, and the character-sprite target inside renderer.js is a
// private one. Volumetric clouds need three: the 3D noise volumes are
// GENERATED by drawing into their layers (VC2), the sky-space cloud
// map is marched into a texture a stripe per frame (VC3), and the
// ground's shadow map likewise (VC4).
//
// THE UPLOAD LAW (bible/01-Overview/Audit-47.md): an UPLOAD path may
// create, fill and parameterise, and may not draw, bind a framebuffer,
// clear, set a viewport or leave a binding. Everything here that binds
// a framebuffer is therefore a DRAW path by name - `withTarget` - and
// it leaves the default framebuffer bound and the viewport as the
// caller asked when it returns. Creation (`createRenderTarget`,
// `createVolume`) binds a texture to size it and unbinds it, nothing
// else - the framebuffer is attached on the draw path. EV6 (no program
// save/restore, no getParameter round-trip) holds: the caller says
// what viewport to restore, this file never asks GL.

/** A 2D colour target: one RGBA8 texture on one framebuffer, no
 *  depth. `filter` NEAREST or LINEAR; `wrap` (or `wrapS` / `wrapT`
 *  apart) REPEAT for an axis that tiles - the sky map's azimuth -
 *  CLAMP_TO_EDGE otherwise. */
export function createRenderTarget(gl, width, height, { filter = 'LINEAR', wrap = 'CLAMP_TO_EDGE', wrapS = wrap, wrapT = wrap } = {}) {
  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D, tex);
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA8, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, null);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl[filter]);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl[filter]);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl[wrapS]);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl[wrapT]);
  gl.bindTexture(gl.TEXTURE_2D, null);
  // the framebuffer is created here and ATTACHED on the first draw path
  // (`withTarget`): creation binds no framebuffer, by the upload law
  return { fbo: gl.createFramebuffer(), tex, width, height, attached: false };
}

/** A 3D RGBA8 volume, sized and parameterised, its texels to be drawn
 *  layer by layer (`withVolumeLayer`). REPEAT on every axis - a noise
 *  volume tiles - and a mip chain so a far march can read a coarser
 *  level (`generateMipmap` after the layers are filled). */
export function createVolume(gl, size) {
  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_3D, tex);
  gl.texImage3D(gl.TEXTURE_3D, 0, gl.RGBA8, size, size, size, 0, gl.RGBA, gl.UNSIGNED_BYTE, null);
  gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_LINEAR);
  gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_S, gl.REPEAT);
  gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_T, gl.REPEAT);
  gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_R, gl.REPEAT);
  gl.bindTexture(gl.TEXTURE_3D, null);
  const fbo = gl.createFramebuffer();
  return { fbo, tex, size };
}

/** DRAW PATH. Bind the target, set its viewport, run `draw`, then
 *  restore the default framebuffer and the viewport the caller names
 *  (the host's world viewport - the caller knows it, GL is not asked). */
export function withTarget(gl, target, restoreViewport, draw) {
  gl.bindFramebuffer(gl.FRAMEBUFFER, target.fbo);
  if (!target.attached) { gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, target.tex, 0); target.attached = true; }
  gl.viewport(0, 0, target.width, target.height);
  draw();
  gl.bindFramebuffer(gl.FRAMEBUFFER, null);
  gl.viewport(restoreViewport[0], restoreViewport[1], restoreViewport[2], restoreViewport[3]);
}

/** DRAW PATH. Attach layer `z` of a volume as the colour target, set
 *  the viewport to its face, run `draw`. The caller restores the
 *  default framebuffer and viewport once, after the last layer. */
export function withVolumeLayer(gl, volume, z, draw) {
  gl.bindFramebuffer(gl.FRAMEBUFFER, volume.fbo);
  gl.framebufferTextureLayer(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, volume.tex, 0, z);
  gl.viewport(0, 0, volume.size, volume.size);
  draw();
}

/** After the layers: the default framebuffer back, the caller's
 *  viewport back, the mip chain built. */
export function finishVolume(gl, volume, restoreViewport) {
  gl.bindFramebuffer(gl.FRAMEBUFFER, null);
  gl.viewport(restoreViewport[0], restoreViewport[1], restoreViewport[2], restoreViewport[3]);
  gl.bindTexture(gl.TEXTURE_3D, volume.tex);
  gl.generateMipmap(gl.TEXTURE_3D);
  gl.bindTexture(gl.TEXTURE_3D, null);
}
