// Bake vendor/dfu-settings/GameSettings.txt (DFU's own settings text
// table, MIT - see the vendor README) into src/systems/settingsText.js.
//
// This is why the settings screen can speak plain English without
// inventing a word: DFU already wrote the label and the tooltip for
// every setting it exposes, plus the titles of its pages and section
// headings. Porting the words is porting a law, exactly like porting
// the defaults - and it is what keeps `LypyL_GameConsole` off the
// screen in favour of DFU's own "Game Console".
//
// Format (the file's own `schema: *key,text`): `key, text` per line,
// `-` starts a comment, blank lines ignored. A key ending `Info` is
// the TOOLTIP for the key without that suffix.
// Run:  node scripts/bakeSettingsText.mjs
// test/settingsText.test.js pins baked === vendored.
import { readFileSync, writeFileSync } from 'node:fs';

export function parseSettingsText(text) {
  const out = {};
  for (const raw of String(text).split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    const c = line.indexOf(',');
    if (c < 0) continue;
    const key = line.slice(0, c).trim();
    const value = line.slice(c + 1).trim();
    if (key) out[key] = value;
  }
  return out;
}

/** Split the flat table into labels and tooltips: `fooInfo` is foo's
 *  tooltip. A key whose base has no label of its own still keeps its
 *  Info entry - DFU has a few - so nothing is dropped silently. */
export function splitLabels(table) {
  const labels = {}, info = {};
  for (const [k, v] of Object.entries(table)) {
    if (k.endsWith('Info') && k.length > 4) info[k.slice(0, -4)] = v;
    else labels[k] = v;
  }
  return { labels, info };
}

const table = parseSettingsText(readFileSync(new URL('../vendor/dfu-settings/GameSettings.txt', import.meta.url), 'utf8'));
const { labels, info } = splitLabels(table);
const obj = (o) => Object.entries(o).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
writeFileSync(new URL('../src/systems/settingsText.js', import.meta.url),
  `// GENERATED by scripts/bakeSettingsText.mjs from
// vendor/dfu-settings/GameSettings.txt (DFU's settings text table,
// MIT). Do not hand-edit; test/settingsText.test.js pins this against
// the vendored source.
//
// SETTINGS_LABELS: the human label for a setting, a settings PAGE or a
// section heading - DFU keys all three out of one table.
// SETTINGS_INFO: the one-line tooltip DFU shows for a setting.
export const SETTINGS_LABELS = Object.freeze({
${obj(labels)}
});

export const SETTINGS_INFO = Object.freeze({
${obj(info)}
});
`);
console.log(`baked ${Object.keys(labels).length} labels + ${Object.keys(info).length} tooltips`);
