// Bake vendor/dfu-settings/defaults.ini.txt (DFU's shipped settings
// defaults, MIT - see the vendor README) into
// src/systems/settingsDefaults.js. Hand-transcribing 171 defaults
// across 13 sections is the lossy-second-copy shape AUDIT 17e F9
// caught in the item templates, so the bake reads the real bytes.
// Run:  node scripts/bakeSettings.mjs
// test/settings.test.js pins baked === vendored, so a drifted bake
// fails rather than silently shipping stale defaults.
import { readFileSync, writeFileSync } from 'node:fs';

/** DFU's ini shape: [Section] headers, key=value lines, ';' comments.
 *  The shipped file mixes `Key=Value` and `Key = Value`, so both
 *  halves are trimmed. Values stay STRINGS - SettingsManager's
 *  GetData returns a string and each typed getter parses it. */
export function parseIni(text) {
  const out = {};
  let section = null;
  for (const raw of String(text).split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith(';') || line.startsWith('#')) continue;
    const head = /^\[(.+)\]$/.exec(line);
    if (head) { section = head[1]; out[section] ??= {}; continue; }
    const eq = line.indexOf('=');
    if (eq < 0 || section === null) continue;
    out[section][line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

const ini = parseIni(readFileSync(new URL('../vendor/dfu-settings/defaults.ini.txt', import.meta.url), 'utf8'));
const body = Object.entries(ini).map(([section, keys]) => {
  const rows = Object.entries(keys).map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
  return `  ${JSON.stringify(section)}: {\n${rows}\n  },`;
}).join('\n');
writeFileSync(new URL('../src/systems/settingsDefaults.js', import.meta.url),
  `// GENERATED by scripts/bakeSettings.mjs from
// vendor/dfu-settings/defaults.ini.txt (DFU's shipped settings
// defaults, MIT). Do not hand-edit; test/settings.test.js pins this
// against the vendored source.
//
// Every value is the RAW STRING the ini carries, because that is what
// SettingsManager.GetData returns - the typed getters in settings.js
// parse it, and their failure modes depend on seeing the raw text.
export const SETTINGS_DEFAULTS = Object.freeze({
${body}
});
`);
const n = Object.values(ini).reduce((a, k) => a + Object.keys(k).length, 0);
console.log(`baked ${n} settings across ${Object.keys(ini).length} sections`);
