// Bake vendor/dfu-books/books.txt (DFU's classic book id -> title
// mapping, MIT - see the vendor README) into src/systems/booksData.js.
// The vendored file keeps its trailing comma verbatim; the bake
// tolerates it exactly as Unity's deserializer does. Run:
//   node scripts/bakeBooks.mjs
// test/books.test.js pins baked === vendored, so a drifted bake fails.
import { readFileSync, writeFileSync } from 'node:fs';

export function parseBookMapping(text) {
  // Unity's FullSerializer tolerates the trailing comma; JSON.parse
  // does not - strip ",]" tails only (never touching string content,
  // which carries no ']' in this data and is pinned by the sync test).
  return JSON.parse(text.replace(/,\s*\]/g, ']'));
}

const entries = parseBookMapping(readFileSync(new URL('../vendor/dfu-books/books.txt', import.meta.url), 'utf8'));
const rows = entries.map((e) => `  [${e.id}, ${JSON.stringify(e.title)}],`).join('\n');
writeFileSync(new URL('../src/systems/booksData.js', import.meta.url),
  `// GENERATED by scripts/bakeBooks.mjs from vendor/dfu-books/books.txt
// (DFU's classic book id -> title mapping, MIT). Do not hand-edit;
// test/books.test.js pins this against the vendored source.
export const BOOK_ID_TITLES = new Map([
${rows}
]);
`);
console.log(`baked ${entries.length} book ids`);
