// Bake vendor/windmills-kamer/interior.json (the interior of the
// subrecord Kamer ADDS to each farm block, vendored with the author's
// permission - his room, built to his mill and centred on machinery he
// animated himself; see the vendor README) into
// src/world/windmillInterior.js, in blocksFile's own parsed shape.
//
//   node scripts/bakeWindmillInterior.mjs
//
// WHY A CONVERSION AND NOT A COPY: his file is DFU's serialization,
// PascalCase and with the record fields DFU chose to write. The port's
// consumers - interiorLayout, interiorPeople, interiorContext - read
// what src/formats/blocksFile.js parses out of BLOCKS.BSA, which is
// camelCase and a different set. Converting here means the interior
// arrives as an ordinary parsed subrecord and NOTHING downstream needs
// to know where it came from.
//
// THE HEADER COUNTS ARE REBUILT FROM THE ARRAYS, deliberately. His
// header declares 44 models, 12 flats and 10 door records over arrays
// of 16, 11 and 0 - the third header-versus-data mismatch in these
// files. A consumer that trusted the count would walk off the end of
// the array. The arrays are the truth.
import { readFileSync, writeFileSync } from 'node:fs';

const src = JSON.parse(
  readFileSync(new URL('../vendor/windmills-kamer/interior.json', import.meta.url), 'utf8')).interior;

const model = (o) => ({
  modelId: String(o.ModelIdNum), modelIdNum: o.ModelIdNum,
  objectType: o.ObjectType ?? 0,
  xPos: o.XPos, yPos: o.YPos, zPos: o.ZPos,
  xRotation: o.XRotation ?? 0, yRotation: o.YRotation ?? 0, zRotation: o.ZRotation ?? 0,
});
const flat = (o) => ({
  xPos: o.XPos, yPos: o.YPos, zPos: o.ZPos,
  textureBitfield: ((o.TextureArchive << 7) | (o.TextureRecord & 0x7f)) >>> 0,
  textureArchive: o.TextureArchive, textureRecord: o.TextureRecord,
  factionID: o.FactionID ?? 0, flags: o.Flags ?? 0,
});
const section3 = (o) => ({
  xPos: o.XPos, yPos: o.YPos, zPos: o.ZPos,
  unknown1: o.Unknown1 ?? 0, unknown2: o.Unknown2 ?? 0, unknown3: o.Unknown3 ?? 0,
});
const person = (o) => ({
  xPos: o.XPos, yPos: o.YPos, zPos: o.ZPos,
  textureBitfield: ((o.TextureArchive << 7) | (o.TextureRecord & 0x7f)) >>> 0,
  textureArchive: o.TextureArchive, textureRecord: o.TextureRecord,
  factionID: o.FactionID ?? 0, flags: o.Flags ?? 0,
});
const door = (o) => ({
  xPos: o.XPos, yPos: o.YPos, zPos: o.ZPos,
  yRotation: o.YRotation ?? 0, openRotation: o.OpenRotation ?? 0,
  doorModelIndex: o.DoorModelIndex ?? 0, unknown: 0, nullValue1: 0,
});

const models = (src.Block3dObjectRecords ?? []).map(model);
const flats = (src.BlockFlatObjectRecords ?? []).map(flat);
const s3 = (src.BlockSection3Records ?? []).map(section3);
const people = (src.BlockPeopleRecords ?? []).map(person);
const doors = (src.BlockDoorRecords ?? []).map(door);

const j = (v) => JSON.stringify(v);
writeFileSync(new URL('../src/world/windmillInterior.js', import.meta.url),
  `// GENERATED by scripts/bakeWindmillInterior.mjs from
// vendor/windmills-kamer/interior.json. Do not hand-edit; re-run the
// bake. test/windmillinterior.test.js pins this against the vendored
// source, so a drifted bake fails.
//
// The interior of the subrecord Kamer adds to each of the seven farm
// blocks - identical in all seven, so one copy serves them all. In
// blocksFile's own parsed shape, so every consumer treats it as an
// ordinary subrecord and none of them needs to know where it came from.
//
// HEADER COUNTS ARE THE ARRAY LENGTHS, not his: he declares 44 models,
// 12 flats and 10 doors over arrays of ${models.length}, ${flats.length} and ${doors.length}.

export const WINDMILL_INTERIOR = Object.freeze({
  header: Object.freeze({
    position: 0,
    num3dObjectRecords: ${models.length},
    numFlatObjectRecords: ${flats.length},
    numSection3Records: ${s3.length},
    numPeopleRecords: ${people.length},
    numDoorRecords: ${doors.length},
    unknown1: 0, unknown2: 0, unknown3: 0, unknown4: 0, unknown5: 0, unknown6: 0,
  }),
  block3dObjectRecords: Object.freeze(${j(models)}),
  blockFlatObjectRecords: Object.freeze(${j(flats)}),
  blockSection3Records: Object.freeze(${j(s3)}),
  blockPeopleRecords: Object.freeze(${j(people)}),
  blockDoorRecords: Object.freeze(${j(doors)}),
});
`);
console.log(`wrote src/world/windmillInterior.js - ${models.length} models, ${flats.length} flats, `
  + `${s3.length} markers, ${people.length} person, ${doors.length} doors`);
