// THE LOW POLY TREES' CROWNS, baked from the vendored mod into a module the world reads.
//
//     node tools/bakeLptCrowns.mjs
//
// VERGE1 (2026-10-07, Mac: "Making sure objects, like trees, avoid pathways and roads. Currently they slightly
// overlap"). A wilderness flat keeps its whole footprint off the roads (world/roadVerge.js), and where Low Poly Trees
// stands a tree for it the footprint is that tree's crown - 5 to 11 metres about the trunk in the temperate woods,
// against a classic picture's few. Where the flats stand must not hang on the mod's switch (it is the player's own
// online: it draws the trees, it never moves them - systems/onlineLane.js), so the crowns are read here, off the
// vendored files, into a table every client has whether or not it draws the trees.
//
// A crown is the farthest any vertex of the prototype's mesh reaches from its root across the ground (x and z, under
// the prefab's own scale) - a disc, because DFU turns each tree at random (world/lowPolyTrees.js lptVariety). Rounded
// UP to the centimetre, so the table is never short of the mesh. test/verge1.test.js re-runs the bake and holds the
// module to it byte for byte.
import { readFileSync, writeFileSync } from 'node:fs';
import { isMain } from './lib/isMain.mjs';

export const SOURCE = 'vendor/low-poly-trees/Trees';
export const OUT = 'src/world/lptCrowns.js';
/** The floats a vertex of trees.bin (position, normal, uv) - world/lowPolyTrees.js renderImpostor's stride. */
const VERTEX_FLOATS = 8;

/**
 * Every prototype's crown (m), keyed `ARCHIVE_RECORD` as trees.json keys its prefabs.
 * @param {any} json trees.json @param {Uint8Array} bin trees.bin
 * @returns {Record<string, number>}
 */
export function lptCrowns(json, bin) {
  const f = new Float32Array(bin.buffer, bin.byteOffset, json.vertexBytes / 4);
  /** @type {Record<string, number>} */
  const out = {};
  for (const [key, p] of Object.entries(json.prefabs)) {
    const m = json.meshes[p.mesh];
    const [sx, , sz] = p.scale;
    let reach = 0;
    for (let v = 0; v < m.vertices; v++) {
      const o = (m.vertex + v) * VERTEX_FLOATS;
      reach = Math.max(reach, Math.hypot(f[o] * sx, f[o + 2] * sz));
    }
    out[key] = Math.ceil(reach * 100) / 100;
  }
  return out;
}

/** The module's text: the table in trees.json's own key order, one prototype a line. */
export function bakeLptCrowns(json, bin) {
  const crowns = lptCrowns(json, bin);
  const rows = Object.keys(crowns).sort((a, b) => {
    const [aa, ar] = a.split('_').map(Number), [ba, br] = b.split('_').map(Number);
    return aa - ba || ar - br;
  }).map((k) => `  '${k}': ${crowns[k]},`);
  return [
    '// GENERATED by tools/bakeLptCrowns.mjs from vendor/low-poly-trees/Trees (SquidKamer\'s LowpolyTrees 5, LPT1) - do not edit.',
    '// VERGE1: each prototype\'s CROWN - the farthest its mesh reaches from the root across the ground, metres, under the',
    '// prefab\'s own scale and before the tree\'s own (lptVariety) - rounded up to the centimetre. world/roadVerge.js keeps a',
    '// wilderness flat\'s footprint off the roads by it, on every client, whether or not that client draws the trees.',
    '/** @type {Readonly<Record<string, number>>} */',
    'export const LPT_CROWNS = Object.freeze({',
    ...rows,
    '});',
    '',
  ].join('\n');
}

if (isMain(import.meta.url)) {
  const json = JSON.parse(readFileSync(`${SOURCE}/trees.json`, 'utf8'));
  const bin = readFileSync(`${SOURCE}/trees.bin`);
  const text = bakeLptCrowns(json, new Uint8Array(bin.buffer, bin.byteOffset, bin.byteLength));
  writeFileSync(OUT, text);
  console.log(`${OUT}: ${Object.keys(json.prefabs).length} crowns`);
}
