// THE MEADOW'S SPRITES, baked from the owner's PNGs into a module the renderer imports.
//
//     node tools/bakeMeadow.mjs
//
// MEADOW1 (2026-10-06, Mac: "These are 4 textures I want to blend into our
// grass system, all with varying sizes so its not monotonous everywhere" -
// then a fifth, "specifically is a bush, so it should be of different
// sizes"). Five pixel-art sprites, supplied as indexed PNGs: a tall green
// tuft, the same tuft cut short, a tuft of flowers, a dry tuft (32x32 each)
// and a bush (64x64). They are committed as he supplied them under
// src/assets/grass/source/ (test/doctrine.test.js rows), and this bake turns
// them into src/render/meadowArt.js: each sprite as its palette and its rows,
// one character a texel, '.' for air - the picture stays readable in a diff,
// and the grass builds its atlas at boot with nothing to fetch or decode, the
// way the pixel style's sheet always has (render/grassPixelArt.js).
//
// The order of SOURCES is the order of the atlas, so it is the variant index
// the shader picks (render/grassMeadow.js MEADOW_VARIANTS names them).
// test/grassmeadow.test.js re-runs the bake and holds the module to it byte
// for byte, and holds every texel of it to the PNG it came from.
import { readFileSync, writeFileSync } from 'node:fs';
import { readPng } from './pngIO.mjs';
import { isMain } from './lib/isMain.mjs';

/** The owner's PNGs, in atlas order - the variant index is the position here. */
export const SOURCES = Object.freeze([
  Object.freeze({ name: 'tall', png: 'src/assets/grass/source/tuft-tall.png' }),
  Object.freeze({ name: 'short', png: 'src/assets/grass/source/tuft-short.png' }),
  Object.freeze({ name: 'flowers', png: 'src/assets/grass/source/flowers.png' }),
  Object.freeze({ name: 'dry', png: 'src/assets/grass/source/tuft-dry.png' }),
  Object.freeze({ name: 'bush', png: 'src/assets/grass/source/bush.png' }),
]);
export const OUT = 'src/render/meadowArt.js';
/** a palette entry's letter - '.' is air and never a colour */
export const MEADOW_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

/**
 * One sprite: its colours in the order they are first met (rows top first, as the PNG stores them) and its rows as
 * letters of MEADOW_ALPHABET. A texel is a colour or air, never between - a soft edge is refused, not rounded,
 * because a pixel sprite that has one was not drawn as one.
 * @param {{ width: number, height: number, data: Uint8ClampedArray }} img readPng's RGBA
 */
export function spriteOf(img, name = 'sprite') {
  const { width, height, data } = img;
  const index = new Map();
  const palette = [];
  const rows = [];
  for (let y = 0; y < height; y++) {
    let row = '';
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      const a = data[i + 3];
      if (a !== 0 && a !== 255) throw new Error(`${name}: texel ${x},${y} has alpha ${a} - a meadow sprite is hard-edged`);
      if (a === 0) { row += '.'; continue; }
      const hex = [data[i], data[i + 1], data[i + 2]].map((v) => v.toString(16).padStart(2, '0')).join('');
      let k = index.get(hex);
      if (k === undefined) {
        if (palette.length >= MEADOW_ALPHABET.length) throw new Error(`${name}: more than ${MEADOW_ALPHABET.length} colours`);
        k = palette.length; index.set(hex, k); palette.push(hex);
      }
      row += MEADOW_ALPHABET[k];
    }
    rows.push(row);
  }
  return { name, width, height, palette, rows };
}

/** The module's text, from the five PNGs' bytes (in SOURCES order). Pure. */
export function bakeMeadow(pngs) {
  if (pngs.length !== SOURCES.length) throw new Error(`the meadow bakes ${SOURCES.length} sprites, handed ${pngs.length}`);
  const sprites = SOURCES.map((s, i) => ({ ...spriteOf(readPng(pngs[i]), s.name), source: s.png }));
  const q = (v) => `'${v}'`;
  const lines = [
    '// @ts-check',
    '// GENERATED by tools/bakeMeadow.mjs from the owner\'s PNGs under src/assets/grass/source/ - do not edit; re-run the',
    '// bake. MEADOW1 (2026-10-06): the meadow\'s five sprites, each as its palette (RGB hex) and its rows (top row first,',
    '// as the PNG stores it; one letter a texel, \'.\' for air). render/grassMeadow.js builds the atlas from these, and',
    '// test/grassmeadow.test.js holds them to the PNGs texel for texel.',
    '',
    '/** a row\'s letter is its colour\'s index in this; \'.\' is air */',
    `export const MEADOW_ALPHABET = ${q(MEADOW_ALPHABET)};`,
    '/** @type {ReadonlyArray<Readonly<{ name: string, source: string, width: number, height: number, palette: readonly string[], rows: readonly string[] }>>} */',
    'export const MEADOW_SPRITES = Object.freeze([',
  ];
  for (const s of sprites) {
    lines.push(`  Object.freeze({ name: ${q(s.name)}, source: ${q(s.source)}, width: ${s.width}, height: ${s.height},`);
    lines.push(`    palette: Object.freeze([${s.palette.map(q).join(', ')}]),`);
    lines.push('    rows: Object.freeze([');
    for (const r of s.rows) lines.push(`      ${q(r)},`);
    lines.push('    ]) }),');
  }
  lines.push(']);', '');
  return lines.join('\n');
}

if (isMain(import.meta.url)) {
  const text = bakeMeadow(SOURCES.map((s) => readFileSync(s.png)));
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (${text.length} bytes, ${SOURCES.length} sprites)`);
}
