// DW2 - THE SPRITE INDEX, from the mod's own manifest.
//
// Which names public/art/diverse-weapons/ carries is the bundle's own
// file list (vendor/diverse-weapons/diverse-weapons.dfmod.json, verbatim
// - the same authority test/doctrine.test.js derives the folder's
// membership from), not a listing of the folder: the door must answer a
// miss WITHOUT a fetch (a weapon's every frame is asked, and a name the
// set lacks - a `w_` for record 3, an icon in a metal nobody painted -
// would be a 404 per ask), and a listing is what the tool that wrote the
// folder happened to write.
//
// 12,624 names is 350 KB of strings; almost every one is a STEM in ten
// metals (`LONGSWORD.CIF_0-0` in Iron..Daedric), so the index is 1,298
// stems with a bitmask over MetalTypes' order (itemInfo.js
// MATERIAL_NAMES), bit 10 for the bare stem, and the one name that fits
// no grammar on its own. ~40 KB, decoded by combat/diverseWeaponsAssets
// .js hasDiverseWeaponsSprite.
//
//   node tools/diverseWeaponsIndex.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isMain } from './lib/isMain.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const MANIFEST = 'vendor/diverse-weapons/diverse-weapons.dfmod.json';
export const INDEX_FILE = 'src/combat/diverseWeaponsIndex.js';
/** MetalTypes' order - itemInfo.js MATERIAL_NAMES, restated so the tool needs no src import. */
export const METALS = Object.freeze(['Iron', 'Steel', 'Silver', 'Elven', 'Dwarven', 'Mithril', 'Adamantium', 'Ebony', 'Orcish', 'Daedric']);
export const BARE_BIT = 1 << METALS.length;

/** The manifest's PNG basenames, deduplicated (the bundle names 310 twice). */
export function manifestSpriteNames(manifestJson) {
  const files = JSON.parse(manifestJson).Files ?? [];
  return [...new Set(files.filter((f) => /\.png$/i.test(f)).map((f) => f.slice(f.lastIndexOf('/') + 1).replace(/\.png$/i, '')))];
}

/** The names as stems -> bitmask, plus the names no grammar holds. */
export function encodeIndex(names) {
  const stems = new Map();
  const odd = [];
  for (const n of names) {
    const m = /^(.*?_\d+-\d+)(?:_([A-Za-z]+))?$/.exec(n);
    const bit = !m ? -1 : m[2] === undefined ? BARE_BIT : METALS.includes(m[2]) ? 1 << METALS.indexOf(m[2]) : -1;
    if (bit < 0) { odd.push(n); continue; }
    stems.set(m[1], (stems.get(m[1]) ?? 0) | bit);
  }
  return { stems: new Map([...stems].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))), odd: odd.sort() };
}

export function renderIndex({ stems, odd }, version) {
  const rows = [...stems].map(([s, bits]) => `  ${JSON.stringify(s)}: ${bits},`);
  return `// GENERATED by tools/diverseWeaponsIndex.mjs from ${MANIFEST} (Diverse Weapons ${version}) - do not edit.
// The names public/art/diverse-weapons/ carries, as stems with a bitmask
// over METALS' order (bit 10 = the bare stem); DIVERSE_WEAPONS_ODD are the
// names no grammar holds. combat/diverseWeaponsAssets.js decodes it.
export const DIVERSE_WEAPONS_METALS = Object.freeze(${JSON.stringify(METALS)});
export const DIVERSE_WEAPONS_BARE = ${BARE_BIT};
export const DIVERSE_WEAPONS_ODD = Object.freeze(${JSON.stringify(odd)});
export const DIVERSE_WEAPONS_STEMS = Object.freeze({
${rows.join('\n')}
});
`;
}

if (isMain(import.meta.url)) {
  const json = readFileSync(join(ROOT, MANIFEST), 'utf8');
  const names = manifestSpriteNames(json);
  const index = encodeIndex(names);
  const total = [...index.stems.values()].reduce((n, b) => n + b.toString(2).split('1').length - 1, 0) + index.odd.length;
  if (total !== names.length) throw new Error(`the index holds ${total} names, the manifest ${names.length}`);
  writeFileSync(join(ROOT, INDEX_FILE), renderIndex(index, JSON.parse(json).ModVersion));
  console.log(`${INDEX_FILE}: ${index.stems.size} stems, ${index.odd.length} odd, ${names.length} names`);
}
