// C6k pose fit: coordinate descent over the paperdoll stance + hanging
// arms, maximizing the front-silhouette IoU against BODY00I0. Emits
// src/characters/paperdollPose.js (generated). The pose is FIT, not
// guessed - the first stance defaults were mirrored guesses and the
// gate caught them at 0.5172.
// Usage: ARENA2_PATH=... node tools/fit-pose.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { buildBody, BARE_PLUGS } from '../src/characters/rewrite/body.js';
import { silhouetteIoU } from '../src/characters/silhouetteIoU.js';
import { DAGGER_SPEC } from '../src/characters/daggerBodySpec.js';
import { ImgFile } from '../src/formats/imgFile.js';
import { DFPalette } from '../src/formats/dfPalette.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const A = process.env.ARENA2_PATH;
const pal = new DFPalette();
pal.load(readFileSync(`${A}/ART_PAL.COL`), 'ART_PAL.COL');
const img = new ImgFile();
img.load(readFileSync(`${A}/BODY00I0.IMG`), 'BODY00I0.IMG', pal);
const bmp = img.getDFBitmap();

const evalPose = (pose) => silhouetteIoU(
  buildBody({ loco: 'stand', hold: 'idle', phase: 0, weapon: 'none', paperdoll: pose }, BARE_PLUGS, DAGGER_SPEC),
  bmp).iou;

const AXES = {
  weightSide: [-1, 1],
  weightIn: [0.2, 0.35, 0.5, 0.65, 0.8],
  freeOut: [0.06, 0.1, 0.14, 0.18, 0.22],
  freeFwd: [0.0, 0.04, 0.1, 0.16],
  hipShift: [0.045, 0.07, 0.09, 0.11],
  armX: [0.12, 0.18, 0.24, 0.3],
  armY: [0.8, 0.9, 1.0, 1.1, 1.2],
  armZ: [0.0, 0.06, 0.12],
  armCurl: [0.25, 0.4, 0.55, 0.7],
  armPoleX: [0.5, 0.85, 1.2, 1.7, 2.3],
  footYaw: [0, 0.4, 0.7, 1.0, 1.3],
};
let pose = { weightSide: -1, weightIn: 0.8, freeOut: 0.14, freeFwd: 0, hipShift: 0.07, armX: 0.18, armY: 1.2, armZ: 0, armCurl: 0.55, armPoleX: 0.85, footYaw: 0 };
let best = evalPose(pose);
console.log('start IoU', best.toFixed(4));
// Joint 2D sweep first: (armX, armY) interact (out-and-low forearms),
// single-axis descent corner-locks on them.
for (const ax of [0.15, 0.2, 0.25, 0.3, 0.35, 0.4]) {
  for (const ay of [0.85, 0.95, 1.05, 1.15, 1.25]) {
    const trial = { ...pose, armX: ax, armY: ay };
    const iou = evalPose(trial);
    if (iou > best) { best = iou; pose = trial; }
  }
}
console.log('after armXY sweep: IoU', best.toFixed(4), 'armX', pose.armX, 'armY', pose.armY);
for (let pass = 0; pass < 3; pass++) {
  for (const [k, vals] of Object.entries(AXES)) {
    for (const v of vals) {
      if (v === pose[k]) continue;
      const trial = { ...pose, [k]: v };
      const iou = evalPose(trial);
      if (iou > best) { best = iou; pose = trial; }
    }
  }
  console.log(`pass ${pass + 1}: IoU ${best.toFixed(4)}`, JSON.stringify(pose));
}
const body = `// PAPERDOLL_POSE (C6k) - GENERATED by tools/fit-pose.mjs:
// coordinate descent over the contrapposto stance + hanging-arm
// targets, maximizing front-silhouette IoU vs BODY00I0. Fit IoU:
// ${best.toFixed(4)}. Regenerate, never hand-edit.
export const PAPERDOLL_POSE = ${JSON.stringify(pose, null, 1).replace(/"/g, "'")};
export const FIT_IOU = ${best.toFixed(4)};
`;
writeFileSync(resolve(ROOT, 'src/characters/paperdollPose.js'), body);
console.log('fit IoU', best.toFixed(4), JSON.stringify(pose));
