// C6k pose fit: coordinate descent over the paperdoll stance + hanging
// arms, maximizing the front-silhouette IoU against BODY00I0. Emits
// src/characters/paperdollPose.js (generated). The pose is FIT, not
// guessed - the first stance defaults were mirrored guesses and the
// gate caught them at 0.5172.
// Usage: ARENA2_PATH=... node tools/fit-pose.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { buildBody, BARE_PLUGS } from '../src/characters/rewrite/body.js';
import { silhouetteIoU } from '../src/characters/silhouetteIoU.js';
import { DAGGER_SPEC } from '../src/characters/daggerBodySpec.js';
import { ImgFile } from '../src/formats/imgFile.js';
import { DFPalette } from '../src/formats/dfPalette.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const A = process.env.ARENA2_PATH;
const pal = new DFPalette();
pal.load(readFileSync(`${A}/ART_PAL.COL`), 'ART_PAL.COL');
const img = new ImgFile();
img.load(readFileSync(`${A}/BODY00I0.IMG`), 'BODY00I0.IMG', pal);
const bmp = img.getDFBitmap();

// Objective (Mac): staying INSIDE the lines beats coverage - excess
// (model beyond the sprite outline) costs DOUBLE a miss.
const score = (r) => {
  const miss = r.union - r.inter - (r.modelArea - r.inter);
  const excess = r.modelArea - r.inter;
  return r.inter / (r.inter + miss + 2 * excess);
};
const evalPose = (pose) => score(silhouetteIoU(
  buildBody({ loco: 'stand', hold: 'idle', phase: 0, weapon: 'none', paperdoll: pose }, BARE_PLUGS, DAGGER_SPEC),
  bmp));

const AXES = {
  weightSide: [-1, 1],
  weightIn: [0.5, 0.65, 0.8],
  freeOut: [0.02, 0.05, 0.08, 0.11],
  freeFwd: [0, 0.06],
  hipShift: [0.03, 0.05, 0.07, 0.09],
};
const toPaperdoll = (p) => ({
  weightSide: p.weightSide, weightIn: p.weightIn, freeOut: p.freeOut,
  freeFwd: p.freeFwd, hipShift: p.hipShift,
});
const evalP = (p) => evalPose(toPaperdoll(p));
// Seeds from the sprite's own arm bars.
let pose = { weightSide: -1, weightIn: 0.8, freeOut: 0.14, freeFwd: 0, hipShift: 0.07 };
let best = evalP(pose);
console.log('start IoU', best.toFixed(4));
for (let pass = 0; pass < 3; pass++) {
  for (const [k, vals] of Object.entries(AXES)) {
    for (const v of vals) {
      if (v === pose[k]) continue;
      const t = { ...pose, [k]: v };
      const iou = evalP(t);
      if (iou > best) { best = iou; pose = t; }
    }
  }
  console.log(`pass ${pass + 1}: IoU ${best.toFixed(4)}`, JSON.stringify(pose));
}
const FINAL = toPaperdoll(pose);
const body = `// PAPERDOLL_POSE (C6k) - GENERATED by tools/fit-pose.mjs:
// coordinate descent over the contrapposto stance + hanging-arm
// targets, maximizing front-silhouette IoU vs BODY00I0. Fit IoU:
// ${best.toFixed(4)}. Regenerate, never hand-edit.
export const PAPERDOLL_POSE = ${JSON.stringify(FINAL, null, 1).replace(/"/g, "'")};
export const FIT_IOU = ${best.toFixed(4)};
`;
writeFileSync(resolve(ROOT, 'src/characters/paperdollPose.js'), body);
console.log('fit IoU', best.toFixed(4), JSON.stringify(pose));
