// C6k pose fit: coordinate descent over the paperdoll stance + hanging
// arms, maximizing the front-silhouette IoU against BODY00I0. Emits
// src/characters/paperdollPose.js (generated). The pose is FIT, not
// guessed - the first stance defaults were mirrored guesses and the
// gate caught them at 0.5172.
// Usage: ARENA2_PATH=... node tools/fit-pose.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { buildBody, BARE_PLUGS } from '../src/characters/rewrite/body.js';
import { silhouetteIoU } from '../src/characters/silhouetteIoU.js';
import { DAGGER_SPEC } from '../src/characters/daggerBodySpec.js';
import { ImgFile } from '../src/formats/imgFile.js';
import { DFPalette } from '../src/formats/dfPalette.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const A = process.env.ARENA2_PATH;
const pal = new DFPalette();
pal.load(readFileSync(`${A}/ART_PAL.COL`), 'ART_PAL.COL');
const img = new ImgFile();
img.load(readFileSync(`${A}/BODY00I0.IMG`), 'BODY00I0.IMG', pal);
const bmp = img.getDFBitmap();

const evalPose = (pose) => silhouetteIoU(
  buildBody({ loco: 'stand', hold: 'idle', phase: 0, weapon: 'none', paperdoll: pose }, BARE_PLUGS, DAGGER_SPEC),
  bmp).iou;

const AXES = {
  weightSide: [-1, 1],
  weightIn: [0.5, 0.65, 0.8],
  freeOut: [0.1, 0.14, 0.18],
  freeFwd: [0, 0.06],
  hipShift: [0.045, 0.07, 0.09],
  footYaw: [0, 0.4, 0.7, 1.0, 1.3],
  // Per-arm (the classic arms are ASYMMETRIC): L = image-left slack
  // arm (bar at |x| 0.33-0.37, wrist low), R = elbow out, forearm
  // tucked to the hip.
  aLx: [0.3, 0.34, 0.38, 0.42],
  aLy: [0.92, 0.99, 1.06],
  aLcurl: [0.1, 0.25, 0.4],
  aLpole: [0.3, 0.7, 1.1],
  aRx: [0.2, 0.24, 0.28, 0.32],
  aRy: [0.98, 1.05, 1.12],
  aRcurl: [0.25, 0.4, 0.55],
  aRpole: [0.3, 0.7, 1.1, 1.5],
};
const toPaperdoll = (p) => ({
  weightSide: p.weightSide, weightIn: p.weightIn, freeOut: p.freeOut,
  freeFwd: p.freeFwd, hipShift: p.hipShift, footYaw: p.footYaw,
  armL: { x: p.aLx, y: p.aLy, curl: p.aLcurl, poleX: p.aLpole },
  armR: { x: p.aRx, y: p.aRy, curl: p.aRcurl, poleX: p.aRpole },
});
const evalP = (p) => evalPose(toPaperdoll(p));
// Seeds from the sprite's own arm bars.
let pose = { weightSide: -1, weightIn: 0.8, freeOut: 0.14, freeFwd: 0, hipShift: 0.07, footYaw: 0.4,
  aLx: 0.38, aLy: 0.99, aLcurl: 0.25, aLpole: 0.7, aRx: 0.24, aRy: 1.05, aRcurl: 0.4, aRpole: 0.7 };
let best = evalP(pose);
console.log('start IoU', best.toFixed(4));
// Joint 2D sweeps per arm first (x*y interact; descent corner-locks).
for (const [kx, ky] of [['aLx', 'aLy'], ['aRx', 'aRy']]) {
  for (const vx of AXES[kx]) for (const vy of AXES[ky]) {
    const t = { ...pose, [kx]: vx, [ky]: vy };
    const iou = evalP(t);
    if (iou > best) { best = iou; pose = t; }
  }
  console.log(`after ${kx}*${ky} sweep: IoU`, best.toFixed(4));
}
for (let pass = 0; pass < 3; pass++) {
  for (const [k, vals] of Object.entries(AXES)) {
    for (const v of vals) {
      if (v === pose[k]) continue;
      const t = { ...pose, [k]: v };
      const iou = evalP(t);
      if (iou > best) { best = iou; pose = t; }
    }
  }
  console.log(`pass ${pass + 1}: IoU ${best.toFixed(4)}`, JSON.stringify(pose));
}
// Spec-stage: handScale (the fist widens the bar bottom; a spec knob,
// swept here and written back into the generator by hand with the
// winning value).
import('../src/characters/daggerBodySpec.js');
let bestHand = 1;
{
  const base = DAGGER_SPEC;
  for (const hs of [2.0, 2.2, 2.4]) {
    const spec = { ...base, handScale: hs };
    const iou = silhouetteIoU(
      buildBody({ loco: 'stand', hold: 'idle', phase: 0, weapon: 'none', paperdoll: toPaperdoll(pose) }, BARE_PLUGS, spec),
      bmp).iou;
    console.log('handScale', hs, '-> IoU', iou.toFixed(4));
    if (iou > best) { best = iou; bestHand = hs; }
  }
}
console.log('best handScale', bestHand, '(write into gen-dagger-spec if != 1)');
const FINAL = toPaperdoll(pose);
const body = `// PAPERDOLL_POSE (C6k) - GENERATED by tools/fit-pose.mjs:
// coordinate descent over the contrapposto stance + hanging-arm
// targets, maximizing front-silhouette IoU vs BODY00I0. Fit IoU:
// ${best.toFixed(4)}. Regenerate, never hand-edit.
export const PAPERDOLL_POSE = ${JSON.stringify(FINAL, null, 1).replace(/"/g, "'")};
export const FIT_IOU = ${best.toFixed(4)};
`;
writeFileSync(resolve(ROOT, 'src/characters/paperdollPose.js'), body);
console.log('fit IoU', best.toFixed(4), JSON.stringify(pose));
