from pathlib import Path

# paperdoll payload: expose every wearable armour template (102..108) in
# Leather/Chain/Plate families. Body armour is a moved-face delta; standoff
# pauldrons/helm are independent piece packs.
p = Path('src/characters/paperdollPayload.js')
s = p.read_text()
s = s.replace(
    "import { armorZones } from './armorSet.js';",
    "import { armorZones, ARMOR_CATALOG, MATERIAL_FAMILY } from './armorSet.js';",
    1,
)
anchor = """  // Per-race body colours: same geometry, re-shaded with the race hide/fur.\n"""
insert = """  // ── COMPLETE WEARABLE ARMOUR CATALOG ───────────────────────────\n  // Armour material is an item-instance axis in Daggerfall, not a different\n  // template. Ship each of the seven wearable templates in all three art/shape\n  // families so the viewer can independently equip every slot. Body-fitted\n  // pieces reuse the rig and therefore ship only moved faces; pauldrons/helm\n  // remain true standoff meshes. Shields are held equipment and intentionally\n  // stay out of this wearable catalog until the hand-mounted shield mesh lands.\n  const armorMats = { steel: STEEL_RAMP, mail: MAIL_RAMP, leather: LEATHER_RAMP };\n  const armorRamp = (family) => family === MATERIAL_FAMILY.Leather ? LEATHER_RAMP\n    : family === MATERIAL_FAMILY.Chain ? MAIL_RAMP : STEEL_RAMP;\n  const armorFamilies = [MATERIAL_FAMILY.Leather, MATERIAL_FAMILY.Chain, MATERIAL_FAMILY.Plate];\n  const armorPacks = ARMOR_CATALOG.map((item) => {\n    const families = {};\n    for (const family of armorFamilies) {\n      const ramp = armorRamp(family);\n      if (item.kind === 'body') {\n        const af = buildNeutralBody(\n          { ...ramps, ...armorMats },\n          { face, armorZones: armorZones(item.index, family), mats: armorMats },\n        );\n        families[family] = clothingSurfaceDelta(faces, af);\n      } else if (item.index === 105) {\n        families[family] = packPiece(buildPauldrons(ramp, 'left'));\n      } else if (item.index === 106) {\n        families[family] = packPiece(buildPauldrons(ramp, 'right'));\n      } else if (item.index === 107) {\n        families[family] = packPiece(buildHelm(ramp));\n      }\n    }\n    return { ...item, families };\n  });\n\n"""
assert anchor in s, 'paperdoll payload armor insertion anchor drifted'
s = s.replace(anchor, insert + anchor, 1)
old = "cloth: CLOTH_D, clothing: clothingPacks, drapedNames: DRAPED_NAMES"
new = "cloth: CLOTH_D, clothing: clothingPacks, armor: armorPacks, armorFamilies: MATERIAL_FAMILY, drapedNames: DRAPED_NAMES"
assert old in s, 'paperdoll payload return seam drifted'
s = s.replace(old, new, 1)
p.write_text(s)

# Viewer: build all armour piece variants, layer body armour after clothing,
# and replace the legacy two-toggle path with independent slot state.
p = Path('src/tools/paperdollViewer.js')
s = p.read_text()
old = """function setLoosePieces(on) {\n  for (const name of ['pauldrons', 'helm']) {\n    const m = pieceMesh[name];\n    if (!m) continue;\n    m.visible = on;\n    const btn = document.getElementById(name);\n    if (btn) btn.classList.toggle('on', on);\n  }\n}\n"""
new = """function setLoosePieces(on) {\n  if (!on) {\n    armorOn.clear();\n    for (const byFamily of Object.values(armorPieceMeshes))\n      for (const m of Object.values(byFamily)) if (m) m.visible = false;\n    for (const id of Object.keys(ARMOR_BUTTONS)) {\n      const btn = document.getElementById(id);\n      if (btn) btn.classList.remove('on');\n    }\n    return;\n  }\n  syncArmorPieceVisibility();\n}\n"""
assert old in s, 'setLoosePieces block drifted'
s = s.replace(old, new, 1)
old = """const pieceMesh = {};\nfor (const name of ['pauldrons','helm']) if (D[name]) pieceMesh[name] = buildPiece(D[name]);\n"""
new = """// Legacy combined meshes remain in the payload for compatibility, but the\n// dress-up UI below is item-slot driven and owns separate left/right pauldrons.\nconst pieceMesh = {};\nfor (const name of ['pauldrons','helm']) if (D[name]) {\n  pieceMesh[name] = buildPiece(D[name]);\n  pieceMesh[name].visible = false;\n}\n\nconst ARMOR_BUTTONS = Object.freeze({\n  'armor-cuirass': 'cuirass',\n  'armor-gauntlets': 'gauntlets',\n  'armor-greaves': 'greaves',\n  'armor-pauldronL': 'pauldronL',\n  'armor-pauldronR': 'pauldronR',\n  'armor-helm': 'helm',\n  'armor-boots': 'boots',\n});\nconst ARMOR_FAMILY_NAMES = ['Leather', 'Chain', 'Plate'];\nlet armorFamily = D.armorFamilies?.Plate ?? 2;\nconst armorOn = new Set();\nconst armorBySlot = Object.fromEntries((D.armor || []).map((a) => [a.slot, a]));\nconst armorPieceMeshes = {};\nfor (const a of (D.armor || [])) {\n  if (a.kind !== 'piece') continue;\n  armorPieceMeshes[a.slot] = {};\n  for (const family of [0, 1, 2]) {\n    const pack = a.families?.[family];\n    const m = pack ? buildPiece(pack) : null;\n    if (m) m.visible = false;\n    armorPieceMeshes[a.slot][family] = m;\n  }\n}\n\nfunction armorPack(slot) {\n  return armorBySlot[slot]?.families?.[armorFamily] || null;\n}\nfunction applyArmorBodyDelta(d) {\n  if (!d?.idx) return;\n  for (let k = 0; k < d.idx.length; k++) {\n    const f = d.idx[k], pb = k * 12, cb = k * 3;\n    if ((D.G ? D.G[f] : 0) === 1) continue;\n    const r = d.C[cb] / 255, g = d.C[cb + 1] / 255, b = d.C[cb + 2] / 255;\n    let oo = f * 18;\n    for (const vi of TRI) {\n      pos[oo] = d.P[pb + vi * 3] / 1000;\n      pos[oo + 1] = d.P[pb + vi * 3 + 1] / 1000;\n      pos[oo + 2] = d.P[pb + vi * 3 + 2] / 1000;\n      col[oo] = r; col[oo + 1] = g; col[oo + 2] = b;\n      oo += 3;\n    }\n  }\n}\nfunction applySelectedBodyArmor() {\n  // Stable inner->outer order. Greaves own their hip fauld; cuirass wins the\n  // tiny 1.12..1.14 overlap, matching their higher classic draw order.\n  for (const slot of ['boots', 'greaves', 'gauntlets', 'cuirass']) {\n    if (!armorOn.has(slot)) continue;\n    applyArmorBodyDelta(armorPack(slot));\n  }\n}\nfunction syncArmorPieceVisibility() {\n  for (const [slot, byFamily] of Object.entries(armorPieceMeshes)) {\n    for (const [family, m] of Object.entries(byFamily))\n      if (m) m.visible = armorOn.has(slot) && Number(family) === armorFamily;\n  }\n}\nfunction syncArmorButtons() {\n  for (const [id, slot] of Object.entries(ARMOR_BUTTONS)) {\n    const btn = document.getElementById(id);\n    if (btn) btn.classList.toggle('on', armorOn.has(slot));\n  }\n  const matBtn = document.getElementById('armormat');\n  if (matBtn) matBtn.textContent = 'armor: ' + (ARMOR_FAMILY_NAMES[armorFamily] || 'Plate');\n}\nasync function rebuildArmorWardrobe() {\n  const c = classicClothingOn;\n  applyClassicClothing(c);\n  syncArmorPieceVisibility();\n  syncArmorButtons();\n  if (c) await syncClassicClothingTexture(c);\n}\n"""
assert old in s, 'pieceMesh seam drifted'
s = s.replace(old, new, 1)
old = """  basePos.set(pos);\n  geo.getAttribute('position').needsUpdate = true;\n  geo.getAttribute('color').needsUpdate = true;\n\n  for (const nm in drapedMeshes) drapedMeshes[nm].visible = false;\n"""
new = """  // Clothing is the under-layer; selected body armour is then written over\n  // the same exact rig faces. The skin compositor sees those final face colours\n  // as isolated atlas overrides, so armour never disables the skin texture.\n  applySelectedBodyArmor();\n  basePos.set(pos);\n  geo.getAttribute('position').needsUpdate = true;\n  geo.getAttribute('color').needsUpdate = true;\n  syncArmorPieceVisibility();\n\n  for (const nm in drapedMeshes) drapedMeshes[nm].visible = false;\n"""
assert old in s, 'applyClassicClothing body seam drifted'
s = s.replace(old, new, 1)
old = """for (const name of ['pauldrons','helm']) { const btn = document.getElementById(name); if (btn) btn.onclick = (e) => { const m = pieceMesh[name]; if (m) { m.visible = !m.visible; e.target.classList.toggle('on', m.visible); if (name === 'helm') syncRace(); } }; }\n"""
new = """for (const [id, slot] of Object.entries(ARMOR_BUTTONS)) {\n  const btn = document.getElementById(id);\n  if (!btn) continue;\n  btn.onclick = async () => {\n    if (armorOn.has(slot)) armorOn.delete(slot); else armorOn.add(slot);\n    await rebuildArmorWardrobe();\n  };\n}\n{\n  const btn = document.getElementById('armormat');\n  if (btn) btn.onclick = async () => {\n    armorFamily = (armorFamily + 1) % 3;\n    await rebuildArmorWardrobe();\n  };\n}\nsyncArmorButtons();\n"""
assert old in s, 'legacy armor control seam drifted'
s = s.replace(old, new, 1)
p.write_text(s)

# Viewer controls: seven independent wearable slots + one material-family cycle.
p = Path('viewer.html')
s = p.read_text()
old = """  <button id=\"pauldrons\" class=\"on\">pauldrons</button>\n  <button id=\"helm\" class=\"on\">helm</button>\n"""
new = """  <button id=\"armormat\">armor: Plate</button>\n  <button id=\"armor-cuirass\">cuirass</button>\n  <button id=\"armor-gauntlets\">gauntlets</button>\n  <button id=\"armor-greaves\">greaves</button>\n  <button id=\"armor-pauldronL\">pauldron L</button>\n  <button id=\"armor-pauldronR\">pauldron R</button>\n  <button id=\"armor-helm\">helm</button>\n  <button id=\"armor-boots\">armor boots</button>\n"""
assert old in s, 'viewer armor buttons drifted'
s = s.replace(old, new, 1)
p.write_text(s)

# Permanent non-manifest probe. It verifies the full seven-slot roster, three
# material families, body-delta ownership and split pauldron pieces without
# needing ARENA2.
p = Path('tools/armorViewerProbe.mjs')
p.write_text("""import assert from 'node:assert/strict';\nimport fs from 'node:fs';\nimport { ARMOR_CATALOG, MATERIAL_FAMILY } from '../src/characters/armorSet.js';\nimport { buildNeutralBody } from '../src/characters/neutralBody.js';\nimport { buildPaperdollPayload } from '../src/characters/paperdollPayload.js';\n\nconst expected = [102,103,104,105,106,107,108];\nassert.deepEqual(ARMOR_CATALOG.map((a) => a.index), expected);\nassert.equal(new Set(ARMOR_CATALOG.map((a) => a.slot)).size, 7);\n\nconst D = buildPaperdollPayload(null, null, null);\nassert.deepEqual(D.armor.map((a) => a.index), expected);\nconst base = buildNeutralBody({\n  skin: [[48,38,30],[96,72,54],[160,120,88],[220,180,140]],\n  boot: [[30,24,20],[80,60,44],[130,100,72]],\n});\nfor (const a of D.armor) {\n  for (const family of [MATERIAL_FAMILY.Leather, MATERIAL_FAMILY.Chain, MATERIAL_FAMILY.Plate]) {\n    const pack = a.families[family];\n    assert.ok(pack, `${a.name} missing family ${family}`);\n    if (a.kind === 'body') {\n      assert.ok(pack.idx.length > 0, `${a.name} must move body faces`);\n      for (let k = 0; k < pack.idx.length; k++) {\n        const f = pack.idx[k];\n        assert.notEqual(base[f].g, 'head', `${a.name} must never own head faces`);\n        let moved = false;\n        for (let j = 0; j < 12; j++) {\n          if (Math.round(base[f].p[j] * 1000) !== pack.P[k*12+j]) { moved = true; break; }\n        }\n        assert.ok(moved, `${a.name} face ${f} must be geometry-owned`);\n      }\n    } else {\n      assert.ok(pack.P.length > 0 && pack.C.length > 0, `${a.name} piece must have geometry`);\n    }\n  }\n}\nconst left = D.armor.find((a) => a.index === 105).families[MATERIAL_FAMILY.Plate];\nconst right = D.armor.find((a) => a.index === 106).families[MATERIAL_FAMILY.Plate];\nassert.equal(new Set(left.G).size, 1, 'left pauldron must be one limb group');\nassert.equal(new Set(right.G).size, 1, 'right pauldron must be one limb group');\nassert.notEqual(left.G[0], right.G[0], 'left/right pauldrons must animate on different arms');\n\nconst html = fs.readFileSync(new URL('../viewer.html', import.meta.url), 'utf8');\nfor (const id of ['armor-cuirass','armor-gauntlets','armor-greaves','armor-pauldronL','armor-pauldronR','armor-helm','armor-boots','armormat'])\n  assert.ok(html.includes(`id=\\"${id}\\"`), `viewer missing ${id}`);\nconsole.log('armor viewer probe: PASS');\n""")
