// RRI1 - ROLEPLAY & REALISM: ITEMS' ART INTO THE CODEBASE. Reads the
// shipped `roleplayrealism-items.dfmod` with the port's UnityFS reader
// and writes every Texture2D out under public/art/roleplay-realism-items/
// by the exact name DFU asks for (`520_10-0_Iron`, `522_13-0_Mask`), the
// way Diverse Weapons' sprites went out (tools/diverseWeaponsExtract.mjs):
// indexed PNG where the picture fits one, RGBA where not, each file read
// back against its texel. The bundle's XML beside each texture - the
// `<rect>` TextureReplacement.OverridePaperdollItemRect reads for the
// paper doll (TextureReplacement.cs:919-926) - is written into the
// generated index (src/systems/rriIndex.js) as the sprite's offset.
//
//   node tools/rriExtract.mjs "<path to roleplayrealism-items.dfmod>"
//
// What the folder may hold is the mod's own manifest (vendor/roleplay-
// realism-items/roleplay-realism-items.dfmod.json; test/doctrine.test.js
// derives the folder's membership from it).
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readUnityBundle } from '../src/formats/unityBundle.js';
import { readPng } from './pngIO.mjs';
import { encodeSprite, sameOnScreen } from './diverseWeaponsExtract.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const OUT_DIR = 'public/art/roleplay-realism-items';
export const INDEX_FILE = 'src/systems/rriIndex.js';
export const MANIFEST = 'vendor/roleplay-realism-items/roleplay-realism-items.dfmod.json';

/** The `<rect>` of one XML text asset, or null. XMLManager.GetRect
 *  (:148-160): x, y, width, height, each divided by the rect's own
 *  `scale` attribute (1 in every file the mod ships). */
export function rectOf(xmlText) {
  const m = /<rect\s+scale="([\d.]+)"\s*>[\s\S]*?<x>(-?[\d.]+)<\/x>\s*<y>(-?[\d.]+)<\/y>\s*<width>(-?[\d.]+)<\/width>\s*<height>(-?[\d.]+)<\/height>/.exec(xmlText);
  if (!m) return null;
  const scale = Number(m[1]) || 1;
  return { x: Number(m[2]) / scale, y: Number(m[3]) / scale, width: Number(m[4]) / scale, height: Number(m[5]) / scale };
}

export function renderIndex(entries, version) {
  const rows = entries.map((e) => `  ${JSON.stringify(e.name)}: [${e.width}, ${e.height}${e.rect ? `, ${e.rect.x}, ${e.rect.y}, ${e.rect.width}, ${e.rect.height}` : ''}],`);
  return `// GENERATED by tools/rriExtract.mjs from the shipped bundle (Roleplay & Realism: Items ${version}) - do not edit.
// Every sprite under ${OUT_DIR}/ by the name DFU asks for: [width, height] and,
// where the bundle carried a <rect> beside it, [x, y, width, height] of that
// rect (TextureReplacement.OverridePaperdollItemRect's paper-doll placement).
export const RRI_SPRITES = Object.freeze({
${rows.join('\n')}
});
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const src = process.argv[2];
  if (!src) { console.error('usage: node tools/rriExtract.mjs "<roleplayrealism-items.dfmod>"'); process.exit(2); }
  const t0 = Date.now();
  const bundle = readUnityBundle(new Uint8Array(readFileSync(src)));
  const manifest = bundle.textAssets.map((t) => { try { return JSON.parse(t.text); } catch { return null; } }).find((m) => m?.GUID);
  const vendored = JSON.parse(readFileSync(join(ROOT, MANIFEST), 'utf8'));
  if (manifest?.GUID !== vendored.GUID) throw new Error(`the bundle is ${manifest?.ModTitle} (${manifest?.GUID}); the port carries ${vendored.ModTitle} (${vendored.GUID})`);
  const allowed = new Set(vendored.Files.filter((f) => /\.png$/i.test(f)).map((f) => f.slice(f.lastIndexOf('/') + 1).replace(/\.png$/i, '')));
  const rects = new Map();
  for (const t of bundle.textAssets) { const r = rectOf(t.text); if (r) rects.set(t.name, r); }
  const out = join(ROOT, OUT_DIR);
  mkdirSync(out, { recursive: true });
  for (const f of readdirSync(out)) if (/\.png$/i.test(f)) unlinkSync(join(out, f));
  const entries = [];
  const written = new Set();
  let bytes = 0, indexed = 0, strangers = 0;
  for (const t of bundle.textures) {
    if (written.has(t.name)) continue;
    if (!allowed.has(t.name)) { strangers++; continue; }
    const img = t.rgba();
    const { png, indexed: isIndexed } = encodeSprite(img);
    if (!sameOnScreen(img, readPng(png))) throw new Error(`${t.name}: the PNG read back differs from the texel`);
    writeFileSync(join(out, `${t.name}.png`), png);
    written.add(t.name);
    entries.push({ name: t.name, width: t.width, height: t.height, rect: rects.get(t.name) ?? null });
    bytes += png.length; indexed += isIndexed ? 1 : 0;
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  writeFileSync(join(ROOT, INDEX_FILE), renderIndex(entries, manifest.ModVersion));
  const missing = [...allowed].filter((n) => !written.has(n));
  console.log(`wrote ${written.size} PNGs (${indexed} indexed) - ${(bytes / 1e6).toFixed(2)} MB - and ${INDEX_FILE} (${entries.filter((e) => e.rect).length} with a rect) in ${Date.now() - t0} ms`);
  if (strangers) console.warn(`${strangers} textures the manifest does not name were NOT written`);
  if (missing.length) console.warn(`${missing.length} manifest names the bundle does not carry:`, missing.slice(0, 10).join(', '));
}
